<template>
  <DescriptionMarkdown
    :title="t('what-is-crc')"
    :description="t('what-is-crc-description-markdown')"
  />
</template>

<script setup lang="ts">
import { DescriptionMarkdown } from '@shared/ui/base'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()
</script>

<i18n lang="json">
{
  "en": {
    "what-is-crc": "What is CRC?",
    "what-is-crc-description-markdown": "CRC (Cyclic Redundancy Check) is a type of checksum algorithm used to detect errors in digital data and storage devices. It produces a fixed-size checksum value, commonly ranging from 8 to 64 bits, that serves as a digital fingerprint of the data.\n\n**Key characteristics:**\n- **Error detection**: Designed specifically to catch common types of errors in data transmission and storage\n- **Deterministic**: The same input always produces the same CRC value\n- **Fast computation**: Efficient to calculate using polynomial division algorithms\n- **Cyclic property**: Based on polynomial arithmetic in finite fields\n- **Collision detection**: Different data will typically produce different CRC values\n\n**Common CRC variants:**\n- **CRC-8**: 8-bit checksum, used in small embedded systems\n- **CRC-16**: 16-bit checksum, used in MODBUS and USB protocols\n- **CRC-32**: 32-bit checksum, widely used in Ethernet, ZIP files, and PNG images\n- **CRC-64**: 64-bit checksum, used for larger data sets requiring higher reliability\n\n**Common uses:**\n- Network protocols (Ethernet frames, TCP checksums)\n- File formats (ZIP, PNG, MPEG)\n- Storage systems (hard drives, SSDs)\n- Data transmission verification\n- Embedded systems and IoT devices"
  },
  "zh": {
    "what-is-crc": "什么是 CRC？",
    "what-is-crc-description-markdown": "CRC（循环冗余校验）是一种用于检测数字数据和存储设备中错误的校验和算法。它生成固定大小的校验和值，通常范围从 8 到 64 位，作为数据的数字指纹。\n\n**主要特征：**\n- **错误检测**：专门设计用于捕获数据传输和存储中常见类型的错误\n- **确定性**：相同的输入总是产生相同的 CRC 值\n- **快速计算**：使用多项式除法算法高效计算\n- **循环特性**：基于有限域中的多项式运算\n- **碰撞检测**：不同数据通常会产生不同的 CRC 值\n\n**常见 CRC 变体：**\n- **CRC-8**：8 位校验和，用于小型嵌入式系统\n- **CRC-16**：16 位校验和，用于 MODBUS 和 USB 协议\n- **CRC-32**：32 位校验和，广泛用于以太网、ZIP 文件和 PNG 图像\n- **CRC-64**：64 位校验和，用于需要更高可靠性的大型数据集\n\n**常见用途：**\n- 网络协议（以太网帧、TCP 校验和）\n- 文件格式（ZIP、PNG、MPEG）\n- 存储系统（硬盘、SSD）\n- 数据传输验证\n- 嵌入式系统和物联网设备"
  },
  "zh-CN": {
    "what-is-crc": "什么是 CRC？",
    "what-is-crc-description-markdown": "CRC（循环冗余校验）是一种用于检测数字数据和存储设备中错误的校验和算法。它生成固定大小的校验和值，通常范围从 8 到 64 位，作为数据的数字指纹。\n\n**主要特征：**\n- **错误检测**：专门设计用于捕获数据传输和存储中常见类型的错误\n- **确定性**：相同的输入总是产生相同的 CRC 值\n- **快速计算**：使用多项式除法算法高效计算\n- **循环特性**：基于有限域中的多项式运算\n- **碰撞检测**：不同数据通常会产生不同的 CRC 值\n\n**常见 CRC 变体：**\n- **CRC-8**：8 位校验和，用于小型嵌入式系统\n- **CRC-16**：16 位校验和，用于 MODBUS 和 USB 协议\n- **CRC-32**：32 位校验和，广泛用于以太网、ZIP 文件和 PNG 图像\n- **CRC-64**：64 位校验和，用于需要更高可靠性的大型数据集\n\n**常见用途：**\n- 网络协议（以太网帧、TCP 校验和）\n- 文件格式（ZIP、PNG、MPEG）\n- 存储系统（硬盘、SSD）\n- 数据传输验证\n- 嵌入式系统和物联网设备"
  },
  "zh-TW": {
    "what-is-crc": "什麼是 CRC？",
    "what-is-crc-description-markdown": "CRC（循環冗餘校驗）是一種用於檢測數位資料和儲存裝置中錯誤的校驗和演算法。它產生固定大小的校驗和值，通常範圍從 8 到 64 位元，作為資料的數位指紋。\n\n**主要特徵：**\n- **錯誤檢測**：專門設計用於捕獲資料傳輸和儲存中常見類型的錯誤\n- **確定性**：相同的輸入總是產生相同的 CRC 值\n- **快速計算**：使用多項式除法演算法高效計算\n- **循環特性**：基於有限域中的多項式運算\n- **碰撞檢測**：不同資料通常會產生不同的 CRC 值\n\n**常見 CRC 變體：**\n- **CRC-8**：8 位元校驗和，用於小型嵌入式系統\n- **CRC-16**：16 位元校驗和，用於 MODBUS 和 USB 協定\n- **CRC-32**：32 位元校驗和，廣泛用於乙太網、ZIP 檔案和 PNG 影像\n- **CRC-64**：64 位元校驗和，用於需要更高可靠性的大型資料集\n\n**常見用途：**\n- 網路協定（乙太網幀、TCP 校驗和）\n- 檔案格式（ZIP、PNG、MPEG）\n- 儲存系統（硬碟、SSD）\n- 資料傳輸驗證\n- 嵌入式系統和物聯網裝置"
  },
  "zh-HK": {
    "what-is-crc": "什麼是 CRC？",
    "what-is-crc-description-markdown": "CRC（循環冗餘校驗）是一種用於檢測數碼資料和儲存裝置中錯誤的校驗和演算法。它產生固定大小的校驗和值，通常範圍從 8 到 64 位元，作為資料的數碼指紋。\n\n**主要特徵：**\n- **錯誤檢測**：專門設計用於捕獲資料傳輸和儲存中常見類型的錯誤\n- **確定性**：相同的輸入總是產生相同的 CRC 值\n- **快速計算**：使用多項式除法演算法高效計算\n- **循環特性**：基於有限域中的多項式運算\n- **碰撞檢測**：不同資料通常會產生不同的 CRC 值\n\n**常見 CRC 變體：**\n- **CRC-8**：8 位元校驗和，用於小型嵌入式系統\n- **CRC-16**：16 位元校驗和，用於 MODBUS 和 USB 協定\n- **CRC-32**：32 位元校驗和，廣泛用於以太網、ZIP 檔案和 PNG 影像\n- **CRC-64**：64 位元校驗和，用於需要更高可靠性的大型資料集\n\n**常見用途：**\n- 網絡協定（以太網幀、TCP 校驗和）\n- 檔案格式（ZIP、PNG、MPEG）\n- 儲存系統（硬碟、SSD）\n- 資料傳輸驗證\n- 嵌入式系統和物聯網裝置"
  },
  "es": {
    "what-is-crc": "¿Qué es CRC?",
    "what-is-crc-description-markdown": "CRC (Verificación de Redundancia Cíclica) es un tipo de algoritmo de suma de verificación utilizado para detectar errores en datos digitales y dispositivos de almacenamiento. Produce un valor de suma de verificación de tamaño fijo, comúnmente de 8 a 64 bits, que sirve como huella digital de los datos.\n\n**Características clave:**\n- **Detección de errores**: Diseñado específicamente para capturar tipos comunes de errores en transmisión y almacenamiento de datos\n- **Determinístico**: La misma entrada siempre produce el mismo valor CRC\n- **Computación rápida**: Eficiente de calcular usando algoritmos de división polinomial\n- **Propiedad cíclica**: Basado en aritmética polinomial en campos finitos\n- **Detección de colisiones**: Datos diferentes típicamente producen valores CRC diferentes\n\n**Variantes CRC comunes:**\n- **CRC-8**: Suma de verificación de 8 bits, usada en sistemas embebidos pequeños\n- **CRC-16**: Suma de verificación de 16 bits, usada en protocolos MODBUS y USB\n- **CRC-32**: Suma de verificación de 32 bits, ampliamente usada en Ethernet, archivos ZIP e imágenes PNG\n- **CRC-64**: Suma de verificación de 64 bits, usada para conjuntos de datos más grandes que requieren mayor confiabilidad\n\n**Usos comunes:**\n- Protocolos de red (tramas Ethernet, sumas de verificación TCP)\n- Formatos de archivo (ZIP, PNG, MPEG)\n- Sistemas de almacenamiento (discos duros, SSD)\n- Verificación de transmisión de datos\n- Sistemas embebidos y dispositivos IoT"
  },
  "fr": {
    "what-is-crc": "Qu'est-ce que CRC ?",
    "what-is-crc-description-markdown": "CRC (Contrôle de Redondance Cyclique) est un type d'algorithme de somme de contrôle utilisé pour détecter les erreurs dans les données numériques et les dispositifs de stockage. Il produit une valeur de somme de contrôle de taille fixe, généralement de 8 à 64 bits, qui sert d'empreinte numérique des données.\n\n**Caractéristiques clés :**\n- **Détection d'erreurs** : Conçu spécifiquement pour détecter les types courants d'erreurs dans la transmission et le stockage de données\n- **Déterministe** : La même entrée produit toujours la même valeur CRC\n- **Calcul rapide** : Efficace à calculer en utilisant des algorithmes de division polynomiale\n- **Propriété cyclique** : Basé sur l'arithmétique polynomiale dans des corps finis\n- **Détection de collisions** : Différentes données produisent généralement différentes valeurs CRC\n\n**Variantes CRC courantes :**\n- **CRC-8** : Somme de contrôle 8 bits, utilisée dans les petits systèmes embarqués\n- **CRC-16** : Somme de contrôle 16 bits, utilisée dans les protocoles MODBUS et USB\n- **CRC-32** : Somme de contrôle 32 bits, largement utilisée dans Ethernet, fichiers ZIP et images PNG\n- **CRC-64** : Somme de contrôle 64 bits, utilisée pour de plus grands ensembles de données nécessitant une fiabilité plus élevée\n\n**Utilisations courantes :**\n- Protocoles réseau (trames Ethernet, sommes de contrôle TCP)\n- Formats de fichiers (ZIP, PNG, MPEG)\n- Systèmes de stockage (disques durs, SSD)\n- Vérification de transmission de données\n- Systèmes embarqués et appareils IoT"
  },
  "de": {
    "what-is-crc": "Was ist CRC?",
    "what-is-crc-description-markdown": "CRC (Cyclic Redundancy Check) ist ein Typ von Prüfsummen-Algorithmus, der verwendet wird, um Fehler in digitalen Daten und Speichergeräten zu erkennen. Es erzeugt einen Prüfsummenwert fester Größe, üblicherweise von 8 bis 64 Bit, der als digitaler Fingerabdruck der Daten dient.\n\n**Hauptmerkmale:**\n- **Fehlererkennung**: Speziell entwickelt, um häufige Fehlertypen bei Datenübertragung und -speicherung zu erkennen\n- **Deterministisch**: Dieselbe Eingabe erzeugt immer denselben CRC-Wert\n- **Schnelle Berechnung**: Effizient zu berechnen mit polynomialen Divisionsalgorithmen\n- **Zyklische Eigenschaft**: Basiert auf polynomialer Arithmetik in endlichen Körpern\n- **Kollisionserkennung**: Verschiedene Daten erzeugen typischerweise verschiedene CRC-Werte\n\n**Häufige CRC-Varianten:**\n- **CRC-8**: 8-Bit-Prüfsumme, verwendet in kleinen eingebetteten Systemen\n- **CRC-16**: 16-Bit-Prüfsumme, verwendet in MODBUS- und USB-Protokollen\n- **CRC-32**: 32-Bit-Prüfsumme, weit verbreitet in Ethernet, ZIP-Dateien und PNG-Bildern\n- **CRC-64**: 64-Bit-Prüfsumme, verwendet für größere Datensätze, die höhere Zuverlässigkeit erfordern\n\n**Häufige Verwendungen:**\n- Netzwerkprotokolle (Ethernet-Frames, TCP-Prüfsummen)\n- Dateiformate (ZIP, PNG, MPEG)\n- Speichersysteme (Festplatten, SSDs)\n- Datenübertragungsverifizierung\n- Eingebettete Systeme und IoT-Geräte"
  },
  "it": {
    "what-is-crc": "Cos'è CRC?",
    "what-is-crc-description-markdown": "CRC (Controllo di Ridondanza Ciclica) è un tipo di algoritmo checksum utilizzato per rilevare errori nei dati digitali e nei dispositivi di memorizzazione. Produce un valore checksum di dimensione fissa, comunemente da 8 a 64 bit, che serve come impronta digitale dei dati.\n\n**Caratteristiche chiave:**\n- **Rilevamento errori**: Progettato specificamente per catturare tipi comuni di errori nella trasmissione e memorizzazione dati\n- **Deterministico**: Lo stesso input produce sempre lo stesso valore CRC\n- **Calcolo veloce**: Efficiente da calcolare usando algoritmi di divisione polinomiale\n- **Proprietà ciclica**: Basato sull'aritmetica polinomiale in campi finiti\n- **Rilevamento collisioni**: Dati diversi tipicamente producono valori CRC diversi\n\n**Varianti CRC comuni:**\n- **CRC-8**: Checksum a 8 bit, usato in piccoli sistemi embedded\n- **CRC-16**: Checksum a 16 bit, usato nei protocolli MODBUS e USB\n- **CRC-32**: Checksum a 32 bit, ampiamente usato in Ethernet, file ZIP e immagini PNG\n- **CRC-64**: Checksum a 64 bit, usato per set di dati più grandi che richiedono maggiore affidabilità\n\n**Usi comuni:**\n- Protocolli di rete (frame Ethernet, checksum TCP)\n- Formati di file (ZIP, PNG, MPEG)\n- Sistemi di archiviazione (hard disk, SSD)\n- Verifica trasmissione dati\n- Sistemi embedded e dispositivi IoT"
  },
  "ja": {
    "what-is-crc": "CRCとは？",
    "what-is-crc-description-markdown": "CRC（巡回冗長検査）は、デジタルデータとストレージデバイスのエラーを検出するために使用されるチェックサムアルゴリズムの一種です。一般的に8ビットから64ビットの範囲で、固定サイズのチェックサム値を生成し、データのデジタル指紋として機能します。\n\n**主な特徴：**\n- **エラー検出**：データ送信と保存における一般的なエラータイプを捕捉するために特別に設計\n- **決定論的**：同じ入力は常に同じCRC値を生成\n- **高速計算**：多項式除算アルゴリズムを使用して効率的に計算\n- **循環特性**：有限体における多項式演算に基づく\n- **衝突検出**：異なるデータは通常異なるCRC値を生成\n\n**一般的なCRC変種：**\n- **CRC-8**：8ビットチェックサム、小型組み込みシステムで使用\n- **CRC-16**：16ビットチェックサム、MODBUSとUSBプロトコルで使用\n- **CRC-32**：32ビットチェックサム、イーサネット、ZIPファイル、PNG画像で広く使用\n- **CRC-64**：64ビットチェックサム、より高い信頼性を必要とする大型データセットで使用\n\n**一般的な用途：**\n- ネットワークプロトコル（イーサネットフレーム、TCPチェックサム）\n- ファイル形式（ZIP、PNG、MPEG）\n- ストレージシステム（ハードドライブ、SSD）\n- データ送信検証\n- 組み込みシステムとIoTデバイス"
  },
  "ko": {
    "what-is-crc": "CRC란?",
    "what-is-crc-description-markdown": "CRC(순환 중복 검사)는 디지털 데이터와 저장 장치의 오류를 감지하는 데 사용되는 체크섬 알고리즘의 한 유형입니다. 일반적으로 8비트에서 64비트 범위의 고정 크기 체크섬 값을 생성하여 데이터의 디지털 지문 역할을 합니다.\n\n**주요 특징:**\n- **오류 감지**: 데이터 전송 및 저장에서 일반적인 오류 유형을 포착하도록 특별히 설계\n- **결정론적**: 동일한 입력은 항상 동일한 CRC 값을 생성\n- **빠른 계산**: 다항식 나눗셈 알고리즘을 사용하여 효율적으로 계산\n- **순환 속성**: 유한체에서의 다항식 산술에 기반\n- **충돌 감지**: 다른 데이터는 일반적으로 다른 CRC 값을 생성\n\n**일반적인 CRC 변형:**\n- **CRC-8**: 8비트 체크섬, 소형 임베디드 시스템에서 사용\n- **CRC-16**: 16비트 체크섬, MODBUS 및 USB 프로토콜에서 사용\n- **CRC-32**: 32비트 체크섬, 이더넷, ZIP 파일, PNG 이미지에서 널리 사용\n- **CRC-64**: 64비트 체크섬, 더 높은 신뢰성이 필요한 대용량 데이터 세트에서 사용\n\n**일반적인 용도:**\n- 네트워크 프로토콜(이더넷 프레임, TCP 체크섬)\n- 파일 형식(ZIP, PNG, MPEG)\n- 저장 시스템(하드 드라이브, SSD)\n- 데이터 전송 검증\n- 임베디드 시스템 및 IoT 장치"
  },
  "ru": {
    "what-is-crc": "Что такое CRC?",
    "what-is-crc-description-markdown": "CRC (Циклическая Избыточная Проверка) — это тип алгоритма контрольной суммы, используемый для обнаружения ошибок в цифровых данных и устройствах хранения. Он производит значение контрольной суммы фиксированного размера, обычно от 8 до 64 бит, которое служит цифровым отпечатком данных.\n\n**Ключевые характеристики:**\n- **Обнаружение ошибок**: Специально разработан для выявления распространенных типов ошибок при передаче и хранении данных\n- **Детерминированность**: Одинаковый ввод всегда производит одинаковое значение CRC\n- **Быстрое вычисление**: Эффективно вычисляется с использованием алгоритмов полиномиального деления\n- **Циклическое свойство**: Основан на полиномиальной арифметике в конечных полях\n- **Обнаружение коллизий**: Разные данные обычно производят разные значения CRC\n\n**Распространенные варианты CRC:**\n- **CRC-8**: 8-битная контрольная сумма, используется в малых встроенных системах\n- **CRC-16**: 16-битная контрольная сумма, используется в протоколах MODBUS и USB\n- **CRC-32**: 32-битная контрольная сумма, широко используется в Ethernet, ZIP-файлах и PNG-изображениях\n- **CRC-64**: 64-битная контрольная сумма, используется для больших наборов данных, требующих повышенной надежности\n\n**Обычные применения:**\n- Сетевые протоколы (кадры Ethernet, контрольные суммы TCP)\n- Форматы файлов (ZIP, PNG, MPEG)\n- Системы хранения (жесткие диски, SSD)\n- Проверка передачи данных\n- Встроенные системы и IoT-устройства"
  },
  "pt": {
    "what-is-crc": "O que é CRC?",
    "what-is-crc-description-markdown": "CRC (Verificação de Redundância Cíclica) é um tipo de algoritmo de checksum usado para detectar erros em dados digitais e dispositivos de armazenamento. Produz um valor de checksum de tamanho fixo, comumente variando de 8 a 64 bits, que serve como uma impressão digital dos dados.\n\n**Características principais:**\n- **Detecção de erros**: Projetado especificamente para capturar tipos comuns de erros na transmissão e armazenamento de dados\n- **Determinístico**: A mesma entrada sempre produz o mesmo valor CRC\n- **Computação rápida**: Eficiente para calcular usando algoritmos de divisão polinomial\n- **Propriedade cíclica**: Baseado em aritmética polinomial em campos finitos\n- **Detecção de colisões**: Dados diferentes tipicamente produzem valores CRC diferentes\n\n**Variantes CRC comuns:**\n- **CRC-8**: Checksum de 8 bits, usado em pequenos sistemas embarcados\n- **CRC-16**: Checksum de 16 bits, usado em protocolos MODBUS e USB\n- **CRC-32**: Checksum de 32 bits, amplamente usado em Ethernet, arquivos ZIP e imagens PNG\n- **CRC-64**: Checksum de 64 bits, usado para conjuntos de dados maiores que requerem maior confiabilidade\n\n**Usos comuns:**\n- Protocolos de rede (quadros Ethernet, checksums TCP)\n- Formatos de arquivo (ZIP, PNG, MPEG)\n- Sistemas de armazenamento (discos rígidos, SSDs)\n- Verificação de transmissão de dados\n- Sistemas embarcados e dispositivos IoT"
  },
  "ar": {
    "what-is-crc": "ما هو CRC؟",
    "what-is-crc-description-markdown": "CRC (فحص التكرار الدوري) هو نوع من خوارزمية المجموع التحققي المستخدمة لاكتشاف الأخطاء في البيانات الرقمية وأجهزة التخزين. ينتج قيمة مجموع تحقق بحجم ثابت، عادة تتراوح من 8 إلى 64 بت، والتي تعمل كبصمة رقمية للبيانات.\n\n**الخصائص الرئيسية:**\n- **اكتشاف الأخطاء**: مصمم خصيصاً لالتقاط الأنواع الشائعة من الأخطاء في نقل وتخزين البيانات\n- **حتمية**: نفس المدخل ينتج دائماً نفس قيمة CRC\n- **حوسبة سريعة**: فعال في الحساب باستخدام خوارزميات القسمة متعددة الحدود\n- **الخاصية الدورية**: قائم على الحساب متعدد الحدود في الحقول المحدودة\n- **اكتشاف التصادمات**: البيانات المختلفة عادة تنتج قيم CRC مختلفة\n\n**أنواع CRC الشائعة:**\n- **CRC-8**: مجموع تحقق 8 بت، مستخدم في الأنظمة المدمجة الصغيرة\n- **CRC-16**: مجموع تحقق 16 بت، مستخدم في بروتوكولات MODBUS و USB\n- **CRC-32**: مجموع تحقق 32 بت، مستخدم على نطاق واسع في إيثرنت وملفات ZIP وصور PNG\n- **CRC-64**: مجموع تحقق 64 بت، مستخدم لمجموعات البيانات الأكبر التي تتطلب موثوقية أعلى\n\n**الاستخدامات الشائعة:**\n- بروتوكولات الشبكة (إطارات إيثرنت، مجاميع تحقق TCP)\n- تنسيقات الملفات (ZIP، PNG، MPEG)\n- أنظمة التخزين (الأقراص الصلبة، SSD)\n- التحقق من نقل البيانات\n- الأنظمة المدمجة وأجهزة إنترنت الأشياء"
  },
  "hi": {
    "what-is-crc": "CRC क्या है?",
    "what-is-crc-description-markdown": "CRC (Cyclic Redundancy Check) एक प्रकार का चेकसम एल्गोरिदम है जो डिजिटल डेटा और स्टोरेज डिवाइस में त्रुटियों का पता लगाने के लिए उपयोग किया जाता है। यह एक निश्चित आकार का चेकसम मान उत्पन्न करता है, आमतौर पर 8 से 64 बिट्स तक, जो डेटा के डिजिटल फिंगरप्रिंट के रूप में कार्य करता है।\n\n**मुख्य विशेषताएं:**\n- **त्रुटि पहचान**: डेटा ट्रांसमिशन और स्टोरेज में सामान्य प्रकार की त्रुटियों को पकड़ने के लिए विशेष रूप से डिज़ाइन किया गया\n- **निर्धारक**: समान इनपुट हमेशा समान CRC मान उत्पन्न करता है\n- **तेज़ गणना**: पॉलिनोमियल डिवीजन एल्गोरिदम का उपयोग करके कुशलतापूर्वक गणना\n- **चक्रीय गुण**: परिमित क्षेत्रों में पॉलिनोमियल अंकगणित पर आधारित\n- **टक्करा पहचान**: अलग डेटा आमतौर पर अलग CRC मान उत्पन्न करता है\n\n**सामान्य CRC वेरिएंट:**\n- **CRC-8**: 8-बिट चेकसम, छोटे एम्बेडेड सिस्टम में उपयोग\n- **CRC-16**: 16-बिट चेकसम, MODBUS और USB प्रोटोकॉल में उपयोग\n- **CRC-32**: 32-बिट चेकसम, ईथरनेट, ZIP फाइलों और PNG छवियों में व्यापक रूप से उपयोग\n- **CRC-64**: 64-बिट चेकसम, उच्च विश्वसनीयता की आवश्यकता वाले बड़े डेटा सेट के लिए उपयोग\n\n**सामान्य उपयोग:**\n- नेटवर्क प्रोटोकॉल (ईथरनेट फ्रेम, TCP चेकसम)\n- फ़ाइल प्रारूप (ZIP, PNG, MPEG)\n- स्टोरेज सिस्टम (हार्ड ड्राइव, SSD)\n- डेटा ट्रांसमिशन सत्यापन\n- एम्बेडेड सिस्टम और IoT डिवाइस"
  },
  "tr": {
    "what-is-crc": "CRC nedir?",
    "what-is-crc-description-markdown": "CRC (Cyclic Redundancy Check), dijital verilerde ve depolama cihazlarında hataları tespit etmek için kullanılan bir tür sağlama toplamı algoritmasıdır. Genellikle 8 ila 64 bit arasında değişen, sabit boyutlu bir sağlama toplamı değeri üretir ve verinin dijital parmak izi görevi görür.\n\n**Temel özellikler:**\n- **Hata tespiti**: Veri iletimi ve depolamasında yaygın hata türlerini yakalamak için özel olarak tasarlanmış\n- **Deterministik**: Aynı girdi her zaman aynı CRC değerini üretir\n- **Hızlı hesaplama**: Polinom bölme algoritmaları kullanarak verimli hesaplama\n- **Döngüsel özellik**: Sonlu alanlarda polinom aritmetiğine dayalı\n- **Çarpışma tespiti**: Farklı veriler genellikle farklı CRC değerleri üretir\n\n**Yaygın CRC varyantları:**\n- **CRC-8**: 8-bit sağlama toplamı, küçük gömülü sistemlerde kullanılır\n- **CRC-16**: 16-bit sağlama toplamı, MODBUS ve USB protokollerinde kullanılır\n- **CRC-32**: 32-bit sağlama toplamı, Ethernet, ZIP dosyaları ve PNG görüntülerinde yaygın olarak kullanılır\n- **CRC-64**: 64-bit sağlama toplamı, daha yüksek güvenilirlik gerektiren büyük veri kümeleri için kullanılır\n\n**Yaygın kullanımlar:**\n- Ağ protokolleri (Ethernet çerçeveleri, TCP sağlama toplamları)\n- Dosya formatları (ZIP, PNG, MPEG)\n- Depolama sistemleri (sabit diskler, SSD'ler)\n- Veri iletimi doğrulama\n- Gömülü sistemler ve IoT cihazları"
  },
  "nl": {
    "what-is-crc": "Wat is CRC?",
    "what-is-crc-description-markdown": "CRC (Cyclic Redundancy Check) is een type checksumalgoritme dat wordt gebruikt om fouten in digitale gegevens en opslagapparaten te detecteren. Het produceert een checksum-waarde van vaste grootte, gewoonlijk variërend van 8 tot 64 bits, die dient als digitale vingerafdruk van de gegevens.\n\n**Belangrijkste kenmerken:**\n- **Foutdetectie**: Speciaal ontworpen om veelvoorkomende fouttypes in gegevensoverdracht en -opslag te onderscheppen\n- **Deterministisch**: Dezelfde invoer produceert altijd dezelfde CRC-waarde\n- **Snelle berekening**: Efficiënt te berekenen met polynoomdelingsalgoritmen\n- **Cyclische eigenschap**: Gebaseerd op polynoom-rekenkunde in eindige velden\n- **Botsingsdetectie**: Verschillende gegevens produceren doorgaans verschillende CRC-waarden\n\n**Veelvoorkomende CRC-varianten:**\n- **CRC-8**: 8-bits checksum, gebruikt in kleine ingebedde systemen\n- **CRC-16**: 16-bits checksum, gebruikt in MODBUS- en USB-protocollen\n- **CRC-32**: 32-bits checksum, veel gebruikt in Ethernet, ZIP-bestanden en PNG-afbeeldingen\n- **CRC-64**: 64-bits checksum, gebruikt voor grotere datasets die hogere betrouwbaarheid vereisen\n\n**Veelvoorkomende toepassingen:**\n- Netwerkprotocollen (Ethernet-frames, TCP-checksums)\n- Bestandsformaten (ZIP, PNG, MPEG)\n- Opslagsystemen (harde schijven, SSD's)\n- Gegevensoverdracht verificatie\n- Ingebedde systemen en IoT-apparaten"
  },
  "sv": {
    "what-is-crc": "Vad är CRC?",
    "what-is-crc-description-markdown": "CRC (Cyclic Redundancy Check) är en typ av checksumalgoritm som används för att upptäcka fel i digital data och lagringsenheter. Den producerar ett checksumvärde med fast storlek, vanligtvis varierande från 8 till 64 bitar, som fungerar som ett digitalt fingeravtryck av datan.\n\n**Nyckelkarakteristika:**\n- **Feldetektering**: Speciellt utformad för att fånga vanliga feltyper i dataöverföring och lagring\n- **Deterministisk**: Samma indata producerar alltid samma CRC-värde\n- **Snabb beräkning**: Effektiv att beräkna med polynomdelningsalgoritmer\n- **Cyklisk egenskap**: Baserad på polynomaritmetik i ändliga fält\n- **Kollisionsdetektering**: Olika data producerar vanligtvis olika CRC-värden\n\n**Vanliga CRC-varianter:**\n- **CRC-8**: 8-bitars checksum, används i små inbäddade system\n- **CRC-16**: 16-bitars checksum, används i MODBUS- och USB-protokoll\n- **CRC-32**: 32-bitars checksum, allmänt använd i Ethernet, ZIP-filer och PNG-bilder\n- **CRC-64**: 64-bitars checksum, används för större dataset som kräver högre tillförlitlighet\n\n**Vanliga användningsområden:**\n- Nätverksprotokoll (Ethernet-ramar, TCP-checksummer)\n- Filformat (ZIP, PNG, MPEG)\n- Lagringssystem (hårddiskar, SSD:er)\n- Dataöverföringsverifiering\n- Inbäddade system och IoT-enheter"
  },
  "pl": {
    "what-is-crc": "Czym jest CRC?",
    "what-is-crc-description-markdown": "CRC (Cyclic Redundancy Check) to typ algorytmu sumy kontrolnej używanego do wykrywania błędów w danych cyfrowych i urządzeniach pamięci. Produkuje wartość sumy kontrolnej o stałym rozmiarze, zazwyczaj od 8 do 64 bitów, która służy jako cyfrowy odcisk palca danych.\n\n**Kluczowe cechy:**\n- **Wykrywanie błędów**: Specjalnie zaprojektowany do wychwytywania typowych błędów w transmisji i przechowywaniu danych\n- **Deterministyczny**: Te same dane wejściowe zawsze produkują tę samą wartość CRC\n- **Szybkie obliczenia**: Wydajny do obliczenia za pomocą algorytmów dzielenia wielomianowego\n- **Właściwość cykliczna**: Oparty na arytmetyce wielomianowej w polach skończonych\n- **Wykrywanie kolizji**: Różne dane zazwyczaj produkują różne wartości CRC\n\n**Typowe warianty CRC:**\n- **CRC-8**: 8-bitowa suma kontrolna, używana w małych systemach wbudowanych\n- **CRC-16**: 16-bitowa suma kontrolna, używana w protokołach MODBUS i USB\n- **CRC-32**: 32-bitowa suma kontrolna, szeroko używana w Ethernet, plikach ZIP i obrazach PNG\n- **CRC-64**: 64-bitowa suma kontrolna, używana dla większych zbiorów danych wymagających wyższej niezawodności\n\n**Typowe zastosowania:**\n- Protokoły sieciowe (ramki Ethernet, sumy kontrolne TCP)\n- Formaty plików (ZIP, PNG, MPEG)\n- Systemy pamięci (dyski twarde, SSD)\n- Weryfikacja transmisji danych\n- Systemy wbudowane i urządzenia IoT"
  },
  "vi": {
    "what-is-crc": "CRC là gì?",
    "what-is-crc-description-markdown": "CRC (Cyclic Redundancy Check) là một loại thuật toán tổng kiểm tra được sử dụng để phát hiện lỗi trong dữ liệu số và thiết bị lưu trữ. Nó tạo ra một giá trị tổng kiểm tra có kích thước cố định, thường từ 8 đến 64 bit, hoạt động như dấu vân tay số của dữ liệu.\n\n**Đặc điểm chính:**\n- **Phát hiện lỗi**: Được thiết kế đặc biệt để bắt các loại lỗi phổ biến trong truyền tải và lưu trữ dữ liệu\n- **Xác định**: Cùng một đầu vào luôn tạo ra cùng một giá trị CRC\n- **Tính toán nhanh**: Hiệu quả để tính toán bằng thuật toán chia đa thức\n- **Tính chất tuần hoàn**: Dựa trên số học đa thức trong trường hữu hạn\n- **Phát hiện va chạm**: Dữ liệu khác nhau thường tạo ra các giá trị CRC khác nhau\n\n**Các biến thể CRC phổ biến:**\n- **CRC-8**: Tổng kiểm tra 8-bit, được sử dụng trong các hệ thống nhúng nhỏ\n- **CRC-16**: Tổng kiểm tra 16-bit, được sử dụng trong giao thức MODBUS và USB\n- **CRC-32**: Tổng kiểm tra 32-bit, được sử dụng rộng rãi trong Ethernet, tệp ZIP và hình ảnh PNG\n- **CRC-64**: Tổng kiểm tra 64-bit, được sử dụng cho các bộ dữ liệu lớn hơn yêu cầu độ tin cậy cao hơn\n\n**Các ứng dụng phổ biến:**\n- Giao thức mạng (khung Ethernet, tổng kiểm tra TCP)\n- Định dạng tệp (ZIP, PNG, MPEG)\n- Hệ thống lưu trữ (ổ cứng, SSD)\n- Xác minh truyền tải dữ liệu\n- Hệ thống nhúng và thiết bị IoT"
  },
  "th": {
    "what-is-crc": "CRC คืออะไร?",
    "what-is-crc-description-markdown": "CRC (Cyclic Redundancy Check) เป็นประเภทของอัลกอริทึมเช็คซัมที่ใช้ในการตรวจจับข้อผิดพลาดในข้อมูลดิจิทัลและอุปกรณ์จัดเก็บข้อมูล มันสร้างค่าเช็คซัมขนาดคงที่ โดยทั่วไปตั้งแต่ 8 ถึง 64 บิต ซึ่งทำหน้าที่เป็นลายนิ้วมือดิจิทัลของข้อมูล\n\n**คุณลักษณะสำคัญ:**\n- **การตรวจจับข้อผิดพลาด**: ออกแบบมาเป็นพิเศษเพื่อจับประเภทข้อผิดพลาดทั่วไปในการส่งและจัดเก็บข้อมูล\n- **กำหนดได้**: อินพุตเดียวกันจะสร้างค่า CRC เดียวกันเสมอ\n- **การคำนวณที่รวดเร็ว**: มีประสิทธิภาพในการคำนวณโดยใช้อัลกอริทึมการหารพหุนาม\n- **คุณสมบัติแบบวงจร**: อิงตามเลขคณิตพหุนามในฟิลด์จำกัด\n- **การตรวจจับการชน**: ข้อมูลที่แตกต่างกันมักจะสร้างค่า CRC ที่แตกต่างกัน\n\n**รูปแบบ CRC ที่พบบ่อย:**\n- **CRC-8**: เช็คซัม 8 บิต ใช้ในระบบฝังตัวขนาดเล็ก\n- **CRC-16**: เช็คซัม 16 บิต ใช้ในโปรโตคอล MODBUS และ USB\n- **CRC-32**: เช็คซัม 32 บิต ใช้อย่างแพร่หลายใน Ethernet, ไฟล์ ZIP และภาพ PNG\n- **CRC-64**: เช็คซัม 64 บิต ใช้สำหรับชุดข้อมูลขนาดใหญ่ที่ต้องการความน่าเชื่อถือสูงกว่า\n\n**การใช้งานทั่วไป:**\n- โปรโตคอลเครือข่าย (เฟรม Ethernet, เช็คซัม TCP)\n- รูปแบบไฟล์ (ZIP, PNG, MPEG)\n- ระบบจัดเก็บข้อมูล (ฮาร์ดไดรฟ์, SSD)\n- การตรวจสอบการส่งข้อมูล\n- ระบบฝังตัวและอุปกรณ์ IoT"
  },
  "id": {
    "what-is-crc": "Apa itu CRC?",
    "what-is-crc-description-markdown": "CRC (Cyclic Redundancy Check) adalah jenis algoritma checksum yang digunakan untuk mendeteksi kesalahan dalam data digital dan perangkat penyimpanan. Ini menghasilkan nilai checksum berukuran tetap, biasanya berkisar dari 8 hingga 64 bit, yang berfungsi sebagai sidik jari digital dari data.\n\n**Karakteristik utama:**\n- **Deteksi kesalahan**: Dirancang khusus untuk menangkap jenis kesalahan umum dalam transmisi dan penyimpanan data\n- **Deterministik**: Input yang sama selalu menghasilkan nilai CRC yang sama\n- **Komputasi cepat**: Efisien untuk dihitung menggunakan algoritma pembagian polinomial\n- **Properti siklik**: Berdasarkan aritmatika polinomial dalam bidang terbatas\n- **Deteksi tabrakan**: Data yang berbeda biasanya menghasilkan nilai CRC yang berbeda\n\n**Varian CRC umum:**\n- **CRC-8**: Checksum 8-bit, digunakan dalam sistem tertanam kecil\n- **CRC-16**: Checksum 16-bit, digunakan dalam protokol MODBUS dan USB\n- **CRC-32**: Checksum 32-bit, banyak digunakan dalam Ethernet, file ZIP, dan gambar PNG\n- **CRC-64**: Checksum 64-bit, digunakan untuk dataset yang lebih besar yang memerlukan keandalan lebih tinggi\n\n**Penggunaan umum:**\n- Protokol jaringan (frame Ethernet, checksum TCP)\n- Format file (ZIP, PNG, MPEG)\n- Sistem penyimpanan (hard drive, SSD)\n- Verifikasi transmisi data\n- Sistem tertanam dan perangkat IoT"
  },
  "he": {
    "what-is-crc": "מה זה CRC?",
    "what-is-crc-description-markdown": "CRC (Cyclic Redundancy Check) הוא סוג של אלגוריתם סכום ביקורת המשמש לזיהוי שגיאות בנתונים דיגיטליים ובהתקני אחסון. הוא מייצר ערך סכום ביקורת בגודל קבוע, בדרך כלל בטווח של 8 עד 64 ביט, המשמש כטביעת אצבע דיגיטלית של הנתונים.\n\n**מאפיינים עיקריים:**\n- **זיהוי שגיאות**: מעוצב במיוחד ללכידת סוגים נפוצים של שגיאות בהעברה ואחסון נתונים\n- **דטרמיניסטי**: אותו קלט תמיד מייצר אותו ערך CRC\n- **חישוב מהיר**: יעיל לחישוב באמצעות אלגוריתמי חלוקה פולינומית\n- **תכונה מחזורית**: מבוסס על אריתמטיקה פולינומית בשדות סופיים\n- **זיהוי התנגשויות**: נתונים שונים בדרך כלל מייצרים ערכי CRC שונים\n\n**גרסאות CRC נפוצות:**\n- **CRC-8**: סכום ביקורת 8 ביט, משמש במערכות משובצות קטנות\n- **CRC-16**: סכום ביקורת 16 ביט, משמש בפרוטוקולי MODBUS ו-USB\n- **CRC-32**: סכום ביקורת 32 ביט, נפוץ ב-Ethernet, קבצי ZIP ותמונות PNG\n- **CRC-64**: סכום ביקורת 64 ביט, משמש למערכי נתונים גדולים יותר הדורשים אמינות גבוהה יותר\n\n**שימושים נפוצים:**\n- פרוטוקולי רשת (מסגרות Ethernet, סכומי ביקורת TCP)\n- פורמטי קבצים (ZIP, PNG, MPEG)\n- מערכות אחסון (כוננים קשיחים, SSD)\n- אימות העברת נתונים\n- מערכות משובצות והתקני IoT"
  },
  "ms": {
    "what-is-crc": "Apakah CRC?",
    "what-is-crc-description-markdown": "CRC (Cyclic Redundancy Check) adalah sejenis algoritma jumlah semak yang digunakan untuk mengesan ralat dalam data digital dan peranti storan. Ia menghasilkan nilai jumlah semak bersaiz tetap, biasanya berkisar dari 8 hingga 64 bit, yang berfungsi sebagai cap jari digital data.\n\n**Ciri-ciri utama:**\n- **Pengesanan ralat**: Direka khas untuk menangkap jenis ralat biasa dalam penghantaran dan penyimpanan data\n- **Deterministik**: Input yang sama sentiasa menghasilkan nilai CRC yang sama\n- **Pengiraan pantas**: Cekap untuk dikira menggunakan algoritma pembahagian polinomial\n- **Sifat kitaran**: Berdasarkan aritmetik polinomial dalam medan terhingga\n- **Pengesanan perlanggaran**: Data yang berbeza biasanya menghasilkan nilai CRC yang berbeza\n\n**Varian CRC biasa:**\n- **CRC-8**: Jumlah semak 8-bit, digunakan dalam sistem terbenam kecil\n- **CRC-16**: Jumlah semak 16-bit, digunakan dalam protokol MODBUS dan USB\n- **CRC-32**: Jumlah semak 32-bit, digunakan secara meluas dalam Ethernet, fail ZIP dan imej PNG\n- **CRC-64**: Jumlah semak 64-bit, digunakan untuk set data yang lebih besar yang memerlukan kebolehpercayaan yang lebih tinggi\n\n**Kegunaan biasa:**\n- Protokol rangkaian (bingkai Ethernet, jumlah semak TCP)\n- Format fail (ZIP, PNG, MPEG)\n- Sistem storan (cakera keras, SSD)\n- Pengesahan penghantaran data\n- Sistem terbenam dan peranti IoT"
  },
  "no": {
    "what-is-crc": "Hva er CRC?",
    "what-is-crc-description-markdown": "CRC (Cyclic Redundancy Check) er en type sjekksum-algoritme som brukes til å oppdage feil i digitale data og lagringsenheter. Den produserer en sjekksum-verdi av fast størrelse, vanligvis fra 8 til 64 bits, som fungerer som et digitalt fingeravtrykk av dataene.\n\n**Nøkkelegenskaper:**\n- **Feiloppdagelse**: Spesielt designet for å fange vanlige feiltyper i dataoverføring og lagring\n- **Deterministisk**: Samme inndata produserer alltid samme CRC-verdi\n- **Rask beregning**: Effektiv å beregne med polynomiske delingsalgoritmer\n- **Syklisk egenskap**: Basert på polynomisk aritmetikk i endelige felt\n- **Kollisjonsdeteksjon**: Forskjellige data produserer vanligvis forskjellige CRC-verdier\n\n**Vanlige CRC-varianter:**\n- **CRC-8**: 8-bits sjekksum, brukt i små innebygde systemer\n- **CRC-16**: 16-bits sjekksum, brukt i MODBUS- og USB-protokoller\n- **CRC-32**: 32-bits sjekksum, mye brukt i Ethernet, ZIP-filer og PNG-bilder\n- **CRC-64**: 64-bits sjekksum, brukt for større datasett som krever høyere pålitelighet\n\n**Vanlige bruksområder:**\n- Nettverksprotokoller (Ethernet-rammer, TCP-sjekksummer)\n- Filformater (ZIP, PNG, MPEG)\n- Lagringssystemer (harddisker, SSD-er)\n- Dataoverføring verifisering\n- Innebygde systemer og IoT-enheter"
  }
}
</i18n>
