<template>
  <n-p>
    Version-5 UUIDs are generated by hashing a namespace identifier and name. Version 5 uses SHA-1
    as the hashing algorithm.
  </n-p>
</template>

<script setup lang="ts">
import { NP } from 'naive-ui'
</script>
