<template>
  <n-p>
    Version-3 UUIDs are generated by hashing a namespace identifier and name. Version 3 uses MD5 as
    the hashing algorithm.
  </n-p>
</template>

<script setup lang="ts">
import { NP } from 'naive-ui'
</script>
