<template>
  <DescriptionMarkdown
    :title="t('what-is-keccak')"
    :description="t('what-is-keccak-description-markdown')"
  />
</template>

<script setup lang="ts">
import { DescriptionMarkdown } from '@shared/ui/base'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()
</script>

<i18n lang="json">
{
  "en": {
    "what-is-keccak": "What is Keccak?",
    "what-is-keccak-description-markdown": "Keccak is a family of cryptographic hash functions that serves as the foundation for the SHA-3 (Secure Hash Algorithm 3) standard. Developed by Guido Bertoni, Joan Daemen, Michaël Peeters, and Gilles Van Assche, it won the NIST hash function competition in 2012.\n\n**Key characteristics:**\n- **Sponge construction**: Uses an innovative sponge function design with absorbing and squeezing phases\n- **Variable output length**: Can produce hash outputs of any desired length\n- **High security margin**: Designed with substantial security reserves\n- **Different from SHA-1/SHA-2**: Based on entirely different mathematical principles\n- **Keccak[c=2d] variant**: This implementation uses the original Keccak specification with capacity c = 2d (where d is the output length)\n\n**Keccak vs SHA-3 (FIPS 202) differences:**\n🔍 **Important distinction**: The original Keccak and the standardized SHA-3 are **not identical**:\n- **Original Keccak**: Uses capacity c = 2d and different padding (Keccak padding: 0x01)\n- **FIPS 202 SHA-3**: Uses capacity c = 2d but different padding (SHA-3 padding: 0x06)\n- **Domain separation**: The padding difference ensures that Keccak and SHA-3 produce different outputs for the same input\n- **This tool implements**: The **original Keccak specification** with Keccak[c=2d] parameterization\n\n**Security status:**\n✅ **Keccak is considered highly secure** with no known practical attacks. It provides excellent security margins and resistance against various cryptanalytic techniques.\n\n**Common uses:**\n- Ethereum blockchain (uses original Keccak-256)\n- Academic research and cryptographic protocols\n- Applications requiring variable-length hash outputs\n- Systems needing alternatives to SHA-2 family\n- Blockchain and cryptocurrency implementations\n\n**Advantages over traditional hashes:**\n- Fundamentally different design reduces risk of related attacks\n- Flexible output length (not limited to fixed sizes)\n- Strong theoretical security foundation\n- Resistance to length extension attacks\n- Excellent performance on various platforms\n\n**Technical note:**\n- **Keccak-256**: Produces 256-bit output (most common variant)\n- **Capacity formula**: c = 2d ensures appropriate security level\n- **Ethereum usage**: Ethereum specifically uses original Keccak-256, not SHA3-256"
  },
  "zh": {
    "what-is-keccak": "什么是 Keccak？",
    "what-is-keccak-description-markdown": "Keccak 是一系列加密散列函数，是 SHA-3（安全散列算法 3）标准的基础。由 Guido Bertoni、Joan Daemen、Michaël Peeters 和 Gilles Van Assche 开发，在 2012 年赢得了 NIST 散列函数竞赛。\n\n**主要特征：**\n- **海绵结构**：使用创新的海绵函数设计，包含吸收和挤压阶段\n- **可变输出长度**：可以产生任何所需长度的散列输出\n- **高安全边际**：设计时具有大量安全储备\n- **不同于 SHA-1/SHA-2**：基于完全不同的数学原理\n- **Keccak[c=2d] 变体**：此实现使用原始 Keccak 规范，容量 c = 2d（其中 d 是输出长度）\n\n**Keccak 与 SHA-3 (FIPS 202) 的区别：**\n🔍 **重要区别**：原始 Keccak 和标准化的 SHA-3 **并不相同**：\n- **原始 Keccak**：使用容量 c = 2d 和不同的填充（Keccak 填充：0x01）\n- **FIPS 202 SHA-3**：使用容量 c = 2d 但不同的填充（SHA-3 填充：0x06）\n- **域分离**：填充差异确保 Keccak 和 SHA-3 对相同输入产生不同输出\n- **此工具实现**：**原始 Keccak 规范**，使用 Keccak[c=2d] 参数化\n\n**安全状态：**\n✅ **Keccak 被认为是高度安全的**，没有已知的实际攻击。它提供了出色的安全边际和对各种密码分析技术的抗性。\n\n**常见用途：**\n- 以太坊区块链（使用原始 Keccak-256）\n- 学术研究和加密协议\n- 需要可变长度散列输出的应用\n- 需要 SHA-2 系列替代品的系统\n- 区块链和加密货币实现\n\n**相对于传统散列的优势：**\n- 根本不同的设计降低了相关攻击的风险\n- 灵活的输出长度（不限于固定大小）\n- 强大的理论安全基础\n- 抗长度扩展攻击\n- 在各种平台上的出色性能\n\n**技术说明：**\n- **Keccak-256**：产生 256 位输出（最常见的变体）\n- **容量公式**：c = 2d 确保适当的安全级别\n- **以太坊使用**：以太坊特别使用原始 Keccak-256，而不是 SHA3-256"
  },
  "zh-CN": {
    "what-is-keccak": "什么是 Keccak？",
    "what-is-keccak-description-markdown": "Keccak 是一系列加密散列函数，是 SHA-3（安全散列算法 3）标准的基础。由 Guido Bertoni、Joan Daemen、Michaël Peeters 和 Gilles Van Assche 开发，在 2012 年赢得了 NIST 散列函数竞赛。\n\n**主要特征：**\n- **海绵结构**：使用创新的海绵函数设计，包含吸收和挤压阶段\n- **可变输出长度**：可以产生任何所需长度的散列输出\n- **高安全边际**：设计时具有大量安全储备\n- **不同于 SHA-1/SHA-2**：基于完全不同的数学原理\n- **Keccak[c=2d] 变体**：此实现使用原始 Keccak 规范，容量 c = 2d（其中 d 是输出长度）\n\n**Keccak 与 SHA-3 (FIPS 202) 的区别：**\n🔍 **重要区别**：原始 Keccak 和标准化的 SHA-3 **并不相同**：\n- **原始 Keccak**：使用容量 c = 2d 和不同的填充（Keccak 填充：0x01）\n- **FIPS 202 SHA-3**：使用容量 c = 2d 但不同的填充（SHA-3 填充：0x06）\n- **域分离**：填充差异确保 Keccak 和 SHA-3 对相同输入产生不同输出\n- **此工具实现**：**原始 Keccak 规范**，使用 Keccak[c=2d] 参数化\n\n**安全状态：**\n✅ **Keccak 被认为是高度安全的**，没有已知的实际攻击。它提供了出色的安全边际和对各种密码分析技术的抗性。\n\n**常见用途：**\n- 以太坊区块链（使用原始 Keccak-256）\n- 学术研究和加密协议\n- 需要可变长度散列输出的应用\n- 需要 SHA-2 系列替代品的系统\n- 区块链和加密货币实现\n\n**相对于传统散列的优势：**\n- 根本不同的设计降低了相关攻击的风险\n- 灵活的输出长度（不限于固定大小）\n- 强大的理论安全基础\n- 抗长度扩展攻击\n- 在各种平台上的出色性能\n\n**技术说明：**\n- **Keccak-256**：产生 256 位输出（最常见的变体）\n- **容量公式**：c = 2d 确保适当的安全级别\n- **以太坊使用**：以太坊特别使用原始 Keccak-256，而不是 SHA3-256"
  },
  "zh-TW": {
    "what-is-keccak": "什麼是 Keccak？",
    "what-is-keccak-description-markdown": "Keccak 是一系列加密雜湊函數，是 SHA-3（安全雜湊演算法 3）標準的基礎。由 Guido Bertoni、Joan Daemen、Michaël Peeters 和 Gilles Van Assche 開發，在 2012 年贏得了 NIST 雜湊函數競賽。\n\n**主要特徵：**\n- **海綿結構**：使用創新的海綿函數設計，包含吸收和擠壓階段\n- **可變輸出長度**：可以產生任何所需長度的雜湊輸出\n- **高安全邊際**：設計時具有大量安全儲備\n- **不同於 SHA-1/SHA-2**：基於完全不同的數學原理\n- **Keccak[c=2d] 變體**：此實作使用原始 Keccak 規範，容量 c = 2d（其中 d 是輸出長度）\n\n**Keccak 與 SHA-3 (FIPS 202) 的區別：**\n🔍 **重要區別**：原始 Keccak 和標準化的 SHA-3 **並不相同**：\n- **原始 Keccak**：使用容量 c = 2d 和不同的填充（Keccak 填充：0x01）\n- **FIPS 202 SHA-3**：使用容量 c = 2d 但不同的填充（SHA-3 填充：0x06）\n- **域分離**：填充差異確保 Keccak 和 SHA-3 對相同輸入產生不同輸出\n- **此工具實作**：**原始 Keccak 規範**，使用 Keccak[c=2d] 參數化\n\n**安全狀態：**\n✅ **Keccak 被認為是高度安全的**，沒有已知的實際攻擊。它提供了出色的安全邊際和對各種密碼分析技術的抗性。\n\n**常見用途：**\n- 以太坊區塊鏈（使用原始 Keccak-256）\n- 學術研究和加密協定\n- 需要可變長度雜湊輸出的應用\n- 需要 SHA-2 系列替代品的系統\n- 區塊鏈和加密貨幣實作\n\n**相對於傳統雜湊的優勢：**\n- 根本不同的設計降低了相關攻擊的風險\n- 靈活的輸出長度（不限於固定大小）\n- 強大的理論安全基礎\n- 抗長度擴展攻擊\n- 在各種平台上的出色效能\n\n**技術說明：**\n- **Keccak-256**：產生 256 位元輸出（最常見的變體）\n- **容量公式**：c = 2d 確保適當的安全級別\n- **以太坊使用**：以太坊特別使用原始 Keccak-256，而不是 SHA3-256"
  },
  "zh-HK": {
    "what-is-keccak": "什麼是 Keccak？",
    "what-is-keccak-description-markdown": "Keccak 是一系列加密雜湊函數，是 SHA-3（安全雜湊演算法 3）標準的基礎。由 Guido Bertoni、Joan Daemen、Michaël Peeters 和 Gilles Van Assche 開發，在 2012 年贏得了 NIST 雜湊函數競賽。\n\n**主要特徵：**\n- **海綿結構**：使用創新的海綿函數設計，包含吸收和擠壓階段\n- **可變輸出長度**：可以產生任何所需長度的雜湊輸出\n- **高安全邊際**：設計時具有大量安全儲備\n- **不同於 SHA-1/SHA-2**：基於完全不同的數學原理\n- **Keccak[c=2d] 變體**：此實作使用原始 Keccak 規範，容量 c = 2d（其中 d 是輸出長度）\n\n**Keccak 與 SHA-3 (FIPS 202) 的區別：**\n🔍 **重要區別**：原始 Keccak 和標準化的 SHA-3 **並不相同**：\n- **原始 Keccak**：使用容量 c = 2d 和不同的填充（Keccak 填充：0x01）\n- **FIPS 202 SHA-3**：使用容量 c = 2d 但不同的填充（SHA-3 填充：0x06）\n- **域分離**：填充差異確保 Keccak 和 SHA-3 對相同輸入產生不同輸出\n- **此工具實作**：**原始 Keccak 規範**，使用 Keccak[c=2d] 參數化\n\n**安全狀態：**\n✅ **Keccak 被認為是高度安全的**，沒有已知的實際攻擊。它提供了出色的安全邊際和對各種密碼分析技術的抗性。\n\n**常見用途：**\n- 以太坊區塊鏈（使用原始 Keccak-256）\n- 學術研究和加密協定\n- 需要可變長度雜湊輸出的應用\n- 需要 SHA-2 系列替代品的系統\n- 區塊鏈和加密貨幣實作\n\n**相對於傳統雜湊的優勢：**\n- 根本不同的設計降低了相關攻擊的風險\n- 靈活的輸出長度（不限於固定大小）\n- 強大的理論安全基礎\n- 抗長度擴展攻擊\n- 在各種平台上的出色效能\n\n**技術說明：**\n- **Keccak-256**：產生 256 位元輸出（最常見的變體）\n- **容量公式**：c = 2d 確保適當的安全級別\n- **以太坊使用**：以太坊特別使用原始 Keccak-256，而不是 SHA3-256"
  },
  "es": {
    "what-is-keccak": "¿Qué es Keccak?",
    "what-is-keccak-description-markdown": "Keccak es una familia de funciones hash criptográficas que sirve como base para el estándar SHA-3 (Secure Hash Algorithm 3). Desarrollado por Guido Bertoni, Joan Daemen, Michaël Peeters y Gilles Van Assche, ganó la competencia de funciones hash NIST en 2012.\n\n**Características clave:**\n- **Construcción esponja**: Usa un diseño innovador de función esponja con fases de absorción y exprimido\n- **Longitud de salida variable**: Puede producir salidas hash de cualquier longitud deseada\n- **Alto margen de seguridad**: Diseñado con reservas de seguridad sustanciales\n- **Diferente de SHA-1/SHA-2**: Basado en principios matemáticos completamente diferentes\n- **Variante Keccak[c=2d]**: Esta implementación usa la especificación Keccak original con capacidad c = 2d (donde d es la longitud de salida)\n\n**Diferencias entre Keccak y SHA-3 (FIPS 202):**\n🔍 **Distinción importante**: El Keccak original y el SHA-3 estandarizado **no son idénticos**:\n- **Keccak original**: Usa capacidad c = 2d y relleno diferente (relleno Keccak: 0x01)\n- **FIPS 202 SHA-3**: Usa capacidad c = 2d pero relleno diferente (relleno SHA-3: 0x06)\n- **Separación de dominio**: La diferencia de relleno asegura que Keccak y SHA-3 produzcan salidas diferentes para la misma entrada\n- **Esta herramienta implementa**: La **especificación Keccak original** con parametrización Keccak[c=2d]\n\n**Estado de seguridad:**\n✅ **Keccak se considera altamente seguro** sin ataques prácticos conocidos. Proporciona excelentes márgenes de seguridad y resistencia contra varias técnicas criptoanalíticas.\n\n**Usos comunes:**\n- Blockchain de Ethereum (usa Keccak-256 original)\n- Investigación académica y protocolos criptográficos\n- Aplicaciones que requieren salidas hash de longitud variable\n- Sistemas que necesitan alternativas a la familia SHA-2\n- Implementaciones de blockchain y criptomonedas\n\n**Ventajas sobre hashes tradicionales:**\n- Diseño fundamentalmente diferente reduce el riesgo de ataques relacionados\n- Longitud de salida flexible (no limitada a tamaños fijos)\n- Base de seguridad teórica sólida\n- Resistencia a ataques de extensión de longitud\n- Excelente rendimiento en varias plataformas\n\n**Nota técnica:**\n- **Keccak-256**: Produce salida de 256 bits (variante más común)\n- **Fórmula de capacidad**: c = 2d asegura el nivel de seguridad apropiado\n- **Uso en Ethereum**: Ethereum específicamente usa Keccak-256 original, no SHA3-256"
  },
  "fr": {
    "what-is-keccak": "Qu'est-ce que Keccak ?",
    "what-is-keccak-description-markdown": "Keccak est une famille de fonctions de hachage cryptographiques qui sert de base au standard SHA-3 (Secure Hash Algorithm 3). Développé par Guido Bertoni, Joan Daemen, Michaël Peeters et Gilles Van Assche, il a remporté la compétition de fonctions de hachage NIST en 2012.\n\n**Caractéristiques clés :**\n- **Construction éponge** : Utilise un design innovant de fonction éponge avec des phases d'absorption et d'essorage\n- **Longueur de sortie variable** : Peut produire des sorties de hachage de n'importe quelle longueur désirée\n- **Marge de sécurité élevée** : Conçu avec des réserves de sécurité substantielles\n- **Différent de SHA-1/SHA-2** : Basé sur des principes mathématiques entièrement différents\n- **Variante Keccak[c=2d]** : Cette implémentation utilise la spécification Keccak originale avec capacité c = 2d (où d est la longueur de sortie)\n\n**Différences entre Keccak et SHA-3 (FIPS 202) :**\n🔍 **Distinction importante** : Le Keccak original et le SHA-3 standardisé **ne sont pas identiques** :\n- **Keccak original** : Utilise la capacité c = 2d et un remplissage différent (remplissage Keccak : 0x01)\n- **FIPS 202 SHA-3** : Utilise la capacité c = 2d mais un remplissage différent (remplissage SHA-3 : 0x06)\n- **Séparation de domaine** : La différence de remplissage garantit que Keccak et SHA-3 produisent des sorties différentes pour la même entrée\n- **Cet outil implémente** : La **spécification Keccak originale** avec la paramétrisation Keccak[c=2d]\n\n**État de sécurité :**\n✅ **Keccak est considéré comme hautement sécurisé** sans attaques pratiques connues. Il fournit d'excellentes marges de sécurité et une résistance contre diverses techniques cryptanalytiques.\n\n**Utilisations courantes :**\n- Blockchain Ethereum (utilise Keccak-256 original)\n- Recherche académique et protocoles cryptographiques\n- Applications nécessitant des sorties de hachage de longueur variable\n- Systèmes nécessitant des alternatives à la famille SHA-2\n- Implémentations blockchain et cryptomonnaies\n\n**Avantages par rapport aux hachages traditionnels :**\n- Design fondamentalement différent réduit le risque d'attaques liées\n- Longueur de sortie flexible (non limitée à des tailles fixes)\n- Base de sécurité théorique solide\n- Résistance aux attaques d'extension de longueur\n- Excellente performance sur diverses plateformes\n\n**Note technique :**\n- **Keccak-256** : Produit une sortie de 256 bits (variante la plus commune)\n- **Formule de capacité** : c = 2d assure le niveau de sécurité approprié\n- **Usage Ethereum** : Ethereum utilise spécifiquement Keccak-256 original, pas SHA3-256"
  },
  "de": {
    "what-is-keccak": "Was ist Keccak?",
    "what-is-keccak-description-markdown": "Keccak ist eine Familie kryptographischer Hash-Funktionen, die als Grundlage für den SHA-3 (Secure Hash Algorithm 3) Standard dient. Entwickelt von Guido Bertoni, Joan Daemen, Michaël Peeters und Gilles Van Assche, gewann es 2012 den NIST Hash-Funktions-Wettbewerb.\n\n**Hauptmerkmale:**\n- **Schwamm-Konstruktion**: Verwendet ein innovatives Schwamm-Funktions-Design mit Absorptions- und Auspress-Phasen\n- **Variable Ausgabelänge**: Kann Hash-Ausgaben jeder gewünschten Länge produzieren\n- **Hohe Sicherheitsmarge**: Mit erheblichen Sicherheitsreserven entwickelt\n- **Anders als SHA-1/SHA-2**: Basiert auf völlig anderen mathematischen Prinzipien\n- **Keccak[c=2d] Variante**: Diese Implementierung verwendet die ursprüngliche Keccak-Spezifikation mit Kapazität c = 2d (wobei d die Ausgabelänge ist)\n\n**Unterschiede zwischen Keccak und SHA-3 (FIPS 202):**\n🔍 **Wichtige Unterscheidung**: Das ursprüngliche Keccak und das standardisierte SHA-3 sind **nicht identisch**:\n- **Ursprüngliches Keccak**: Verwendet Kapazität c = 2d und anderes Padding (Keccak-Padding: 0x01)\n- **FIPS 202 SHA-3**: Verwendet Kapazität c = 2d aber anderes Padding (SHA-3-Padding: 0x06)\n- **Domain-Trennung**: Der Padding-Unterschied stellt sicher, dass Keccak und SHA-3 unterschiedliche Ausgaben für dieselbe Eingabe produzieren\n- **Dieses Tool implementiert**: Die **ursprüngliche Keccak-Spezifikation** mit Keccak[c=2d] Parametrisierung\n\n**Sicherheitsstatus:**\n✅ **Keccak gilt als hochsicher** ohne bekannte praktische Angriffe. Es bietet exzellente Sicherheitsmargen und Widerstand gegen verschiedene kryptoanalytische Techniken.\n\n**Häufige Verwendungen:**\n- Ethereum-Blockchain (verwendet ursprüngliches Keccak-256)\n- Akademische Forschung und kryptographische Protokolle\n- Anwendungen, die Hash-Ausgaben variabler Länge benötigen\n- Systeme, die Alternativen zur SHA-2-Familie benötigen\n- Blockchain- und Kryptowährungs-Implementierungen\n\n**Vorteile gegenüber traditionellen Hashes:**\n- Grundlegend anderes Design reduziert Risiko verwandter Angriffe\n- Flexible Ausgabelänge (nicht auf feste Größen beschränkt)\n- Starke theoretische Sicherheitsgrundlage\n- Widerstand gegen Längenerweiterungs-Angriffe\n- Exzellente Leistung auf verschiedenen Plattformen\n\n**Technischer Hinweis:**\n- **Keccak-256**: Produziert 256-Bit-Ausgabe (häufigste Variante)\n- **Kapazitäts-Formel**: c = 2d stellt angemessenes Sicherheitsniveau sicher\n- **Ethereum-Verwendung**: Ethereum verwendet spezifisch ursprüngliches Keccak-256, nicht SHA3-256"
  },
  "it": {
    "what-is-keccak": "Cos'è Keccak?",
    "what-is-keccak-description-markdown": "Keccak è una famiglia di funzioni hash crittografiche che serve come base per lo standard SHA-3 (Secure Hash Algorithm 3). Sviluppato da Guido Bertoni, Joan Daemen, Michaël Peeters e Gilles Van Assche, ha vinto la competizione NIST per le funzioni hash nel 2012.\n\n**Caratteristiche chiave:**\n- **Costruzione a spugna**: Utilizza un design innovativo di funzione a spugna con fasi di assorbimento e spremitura\n- **Lunghezza di output variabile**: Può produrre output hash di qualsiasi lunghezza desiderata\n- **Alto margine di sicurezza**: Progettato con riserve di sicurezza sostanziali\n- **Diverso da SHA-1/SHA-2**: Basato su principi matematici completamente diversi\n- **Variante Keccak[c=2d]**: Questa implementazione usa la specifica Keccak originale con capacità c = 2d (dove d è la lunghezza dell'output)\n\n**Differenze tra Keccak e SHA-3 (FIPS 202):**\n🔍 **Distinzione importante**: Il Keccak originale e lo SHA-3 standardizzato **non sono identici**:\n- **Keccak originale**: Usa capacità c = 2d e padding diverso (padding Keccak: 0x01)\n- **FIPS 202 SHA-3**: Usa capacità c = 2d ma padding diverso (padding SHA-3: 0x06)\n- **Separazione di dominio**: La differenza nel padding assicura che Keccak e SHA-3 producano output diversi per lo stesso input\n- **Questo strumento implementa**: La **specifica Keccak originale** con parametrizzazione Keccak[c=2d]\n\n**Stato di sicurezza:**\n✅ **Keccak è considerato altamente sicuro** senza attacchi pratici conosciuti. Fornisce eccellenti margini di sicurezza e resistenza contro varie tecniche crittoanalitiche.\n\n**Usi comuni:**\n- Blockchain Ethereum (usa Keccak-256 originale)\n- Ricerca accademica e protocolli crittografici\n- Applicazioni che richiedono output hash di lunghezza variabile\n- Sistemi che necessitano alternative alla famiglia SHA-2\n- Implementazioni blockchain e criptovalute\n\n**Vantaggi rispetto agli hash tradizionali:**\n- Design fondamentalmente diverso riduce il rischio di attacchi correlati\n- Lunghezza di output flessibile (non limitata a dimensioni fisse)\n- Solida base di sicurezza teorica\n- Resistenza agli attacchi di estensione della lunghezza\n- Eccellenti prestazioni su varie piattaforme\n\n**Nota tecnica:**\n- **Keccak-256**: Produce output a 256 bit (variante più comune)\n- **Formula della capacità**: c = 2d assicura il livello di sicurezza appropriato\n- **Uso Ethereum**: Ethereum usa specificamente Keccak-256 originale, non SHA3-256"
  },
  "ja": {
    "what-is-keccak": "Keccakとは？",
    "what-is-keccak-description-markdown": "Keccakは暗号学的ハッシュ関数のファミリーで、SHA-3（Secure Hash Algorithm 3）標準の基礎となっています。Guido Bertoni、Joan Daemen、Michaël Peeters、Gilles Van Asscheによって開発され、2012年にNISTハッシュ関数コンペティションで優勝しました。\n\n**主な特徴：**\n- **スポンジ構造**：吸収と絞り出しフェーズを持つ革新的なスポンジ関数設計を使用\n- **可変出力長**：任意の希望する長さのハッシュ出力を生成可能\n- **高いセキュリティマージン**：十分なセキュリティ予備力を持って設計\n- **SHA-1/SHA-2とは異なる**：完全に異なる数学的原理に基づく\n- **Keccak[c=2d]バリアント**：この実装は元のKeccak仕様を使用し、容量c = 2d（dは出力長）\n\n**KeccakとSHA-3（FIPS 202）の違い：**\n🔍 **重要な区別**：元のKeccakと標準化されたSHA-3は**同一ではありません**：\n- **元のKeccak**：容量c = 2dと異なるパディング（Keccakパディング：0x01）を使用\n- **FIPS 202 SHA-3**：容量c = 2dを使用するが異なるパディング（SHA-3パディング：0x06）\n- **ドメイン分離**：パディングの違いにより、KeccakとSHA-3は同じ入力に対して異なる出力を生成\n- **このツールの実装**：Keccak[c=2d]パラメータ化を使用した**元のKeccak仕様**\n\n**セキュリティ状況：**\n✅ **Keccakは高度に安全とされています**。既知の実用的な攻撃はありません。優秀なセキュリティマージンと様々な暗号解析技術に対する耐性を提供します。\n\n**一般的な用途：**\n- Ethereumブロックチェーン（元のKeccak-256を使用）\n- 学術研究と暗号プロトコル\n- 可変長ハッシュ出力を必要とするアプリケーション\n- SHA-2ファミリーの代替を必要とするシステム\n- ブロックチェーンと暗号通貨の実装\n\n**従来のハッシュに対する利点：**\n- 根本的に異なる設計により関連攻撃のリスクを軽減\n- 柔軟な出力長（固定サイズに制限されない）\n- 強固な理論的セキュリティ基盤\n- 長さ拡張攻撃に対する耐性\n- 様々なプラットフォームでの優秀な性能\n\n**技術的注記：**\n- **Keccak-256**：256ビット出力を生成（最も一般的なバリアント）\n- **容量公式**：c = 2dが適切なセキュリティレベルを保証\n- **Ethereumでの使用**：EthereumはSHA3-256ではなく、特に元のKeccak-256を使用"
  },
  "ko": {
    "what-is-keccak": "Keccak이란?",
    "what-is-keccak-description-markdown": "Keccak은 SHA-3(Secure Hash Algorithm 3) 표준의 기초가 되는 암호화 해시 함수 계열입니다. Guido Bertoni, Joan Daemen, Michaël Peeters, Gilles Van Assche가 개발했으며, 2012년 NIST 해시 함수 경쟁에서 우승했습니다.\n\n**주요 특징:**\n- **스펀지 구조**: 흡수 및 짜내기 단계를 가진 혁신적인 스펀지 함수 설계 사용\n- **가변 출력 길이**: 원하는 길이의 해시 출력을 생성 가능\n- **높은 보안 마진**: 상당한 보안 예비력으로 설계\n- **SHA-1/SHA-2와 다름**: 완전히 다른 수학적 원리 기반\n- **Keccak[c=2d] 변형**: 이 구현은 용량 c = 2d(d는 출력 길이)인 원본 Keccak 사양 사용\n\n**Keccak vs SHA-3 (FIPS 202) 차이점:**\n🔍 **중요한 구별**: 원본 Keccak과 표준화된 SHA-3는 **동일하지 않습니다**:\n- **원본 Keccak**: 용량 c = 2d와 다른 패딩(Keccak 패딩: 0x01) 사용\n- **FIPS 202 SHA-3**: 용량 c = 2d를 사용하지만 다른 패딩(SHA-3 패딩: 0x06)\n- **도메인 분리**: 패딩 차이로 Keccak과 SHA-3가 동일한 입력에 대해 다른 출력 생성\n- **이 도구 구현**: Keccak[c=2d] 매개화를 사용한 **원본 Keccak 사양**\n\n**보안 상태:**\n✅ **Keccak은 매우 안전한 것으로 간주됩니다**. 알려진 실용적인 공격이 없습니다. 우수한 보안 마진과 다양한 암호 분석 기법에 대한 저항성을 제공합니다.\n\n**일반적인 용도:**\n- 이더리움 블록체인(원본 Keccak-256 사용)\n- 학술 연구 및 암호화 프로토콜\n- 가변 길이 해시 출력이 필요한 애플리케이션\n- SHA-2 계열의 대안이 필요한 시스템\n- 블록체인 및 암호화폐 구현\n\n**기존 해시 대비 장점:**\n- 근본적으로 다른 설계로 관련 공격 위험 감소\n- 유연한 출력 길이(고정 크기에 제한되지 않음)\n- 강력한 이론적 보안 기반\n- 길이 확장 공격에 대한 저항성\n- 다양한 플랫폼에서 우수한 성능\n\n**기술적 참고사항:**\n- **Keccak-256**: 256비트 출력 생성(가장 일반적인 변형)\n- **용량 공식**: c = 2d가 적절한 보안 수준 보장\n- **이더리움 사용**: 이더리움은 SHA3-256이 아닌 원본 Keccak-256을 특별히 사용"
  },
  "ru": {
    "what-is-keccak": "Что такое Keccak?",
    "what-is-keccak-description-markdown": "Keccak — это семейство криптографических хеш-функций, которое служит основой для стандарта SHA-3 (Secure Hash Algorithm 3). Разработанный Гвидо Бертони, Жоаном Дэменом, Микаэлем Питерсом и Жилем Ван Ассшем, он выиграл конкурс хеш-функций NIST в 2012 году.\n\n**Ключевые характеристики:**\n- **Губчатая конструкция**: Использует инновативный дизайн губчатой функции с фазами поглощения и выжимания\n- **Переменная длина вывода**: Может производить хеш-выводы любой желаемой длины\n- **Высокий запас безопасности**: Разработан с существенными резервами безопасности\n- **Отличается от SHA-1/SHA-2**: Основан на совершенно других математических принципах\n- **Вариант Keccak[c=2d]**: Эта реализация использует оригинальную спецификацию Keccak с емкостью c = 2d (где d — длина вывода)\n\n**Различия между Keccak и SHA-3 (FIPS 202):**\n🔍 **Важное различие**: Оригинальный Keccak и стандартизированный SHA-3 **не идентичны**:\n- **Оригинальный Keccak**: Использует емкость c = 2d и другое заполнение (заполнение Keccak: 0x01)\n- **FIPS 202 SHA-3**: Использует емкость c = 2d, но другое заполнение (заполнение SHA-3: 0x06)\n- **Разделение доменов**: Различие в заполнении обеспечивает, что Keccak и SHA-3 производят разные выводы для одного входа\n- **Этот инструмент реализует**: **Оригинальную спецификацию Keccak** с параметризацией Keccak[c=2d]\n\n**Статус безопасности:**\n✅ **Keccak считается высокобезопасным** без известных практических атак. Он обеспечивает отличные запасы безопасности и устойчивость против различных криптоаналитических техник.\n\n**Обычные применения:**\n- Блокчейн Ethereum (использует оригинальный Keccak-256)\n- Академические исследования и криптографические протоколы\n- Приложения, требующие хеш-выводы переменной длины\n- Системы, нуждающиеся в альтернативах семейству SHA-2\n- Реализации блокчейна и криптовалют\n\n**Преимущества перед традиционными хешами:**\n- Принципиально другой дизайн снижает риск связанных атак\n- Гибкая длина вывода (не ограничена фиксированными размерами)\n- Сильная теоретическая база безопасности\n- Устойчивость к атакам расширения длины\n- Отличная производительность на различных платформах\n\n**Техническая заметка:**\n- **Keccak-256**: Производит 256-битный вывод (наиболее распространенный вариант)\n- **Формула емкости**: c = 2d обеспечивает соответствующий уровень безопасности\n- **Использование Ethereum**: Ethereum конкретно использует оригинальный Keccak-256, а не SHA3-256"
  },
  "pt": {
    "what-is-keccak": "O que é Keccak?",
    "what-is-keccak-description-markdown": "Keccak é uma família de funções hash criptográficas que serve como base para o padrão SHA-3 (Secure Hash Algorithm 3). Desenvolvido por Guido Bertoni, Joan Daemen, Michaël Peeters e Gilles Van Assche, venceu a competição de funções hash NIST em 2012.\n\n**Características principais:**\n- **Construção esponja**: Usa um design inovador de função esponja com fases de absorção e espremida\n- **Comprimento de saída variável**: Pode produzir saídas hash de qualquer comprimento desejado\n- **Alta margem de segurança**: Projetado com reservas de segurança substanciais\n- **Diferente de SHA-1/SHA-2**: Baseado em princípios matemáticos completamente diferentes\n- **Variante Keccak[c=2d]**: Esta implementação usa a especificação Keccak original com capacidade c = 2d (onde d é o comprimento da saída)\n\n**Diferenças entre Keccak e SHA-3 (FIPS 202):**\n🔍 **Distinção importante**: O Keccak original e o SHA-3 padronizado **não são idênticos**:\n- **Keccak original**: Usa capacidade c = 2d e preenchimento diferente (preenchimento Keccak: 0x01)\n- **FIPS 202 SHA-3**: Usa capacidade c = 2d mas preenchimento diferente (preenchimento SHA-3: 0x06)\n- **Separação de domínio**: A diferença de preenchimento garante que Keccak e SHA-3 produzam saídas diferentes para a mesma entrada\n- **Esta ferramenta implementa**: A **especificação Keccak original** com parametrização Keccak[c=2d]\n\n**Status de segurança:**\n✅ **Keccak é considerado altamente seguro** sem ataques práticos conhecidos. Fornece excelentes margens de segurança e resistência contra várias técnicas criptoanalíticas.\n\n**Usos comuns:**\n- Blockchain Ethereum (usa Keccak-256 original)\n- Pesquisa acadêmica e protocolos criptográficos\n- Aplicações que requerem saídas hash de comprimento variável\n- Sistemas que precisam de alternativas à família SHA-2\n- Implementações de blockchain e criptomoedas\n\n**Vantagens sobre hashes tradicionais:**\n- Design fundamentalmente diferente reduz risco de ataques relacionados\n- Comprimento de saída flexível (não limitado a tamanhos fixos)\n- Base de segurança teórica sólida\n- Resistência a ataques de extensão de comprimento\n- Excelente desempenho em várias plataformas\n\n**Nota técnica:**\n- **Keccak-256**: Produz saída de 256 bits (variante mais comum)\n- **Fórmula de capacidade**: c = 2d garante nível de segurança apropriado\n- **Uso Ethereum**: Ethereum especificamente usa Keccak-256 original, não SHA3-256"
  },
  "ar": {
    "what-is-keccak": "ما هو Keccak؟",
    "what-is-keccak-description-markdown": "Keccak هو عائلة من دوال التشفير التي تعمل كأساس لمعيار SHA-3 (خوارزمية التشفير الآمنة 3). طُور من قبل Guido Bertoni و Joan Daemen و Michaël Peeters و Gilles Van Assche، وفاز في مسابقة دوال التشفير NIST في 2012.\n\n**الخصائص الرئيسية:**\n- **بناء الإسفنج**: يستخدم تصميم دالة إسفنج مبتكر مع مراحل الامتصاص والعصر\n- **طول إخراج متغير**: يمكن أن ينتج مخرجات تشفير بأي طول مرغوب\n- **هامش أمان عالي**: مُصمم بحتياطيات أمان كبيرة\n- **مختلف عن SHA-1/SHA-2**: مبني على مبادئ رياضية مختلفة تماماً\n- **متغير Keccak[c=2d]**: هذا التطبيق يستخدم مواصفة Keccak الأصلية مع سعة c = 2d (حيث d هو طول الإخراج)\n\n**الاختلافات بين Keccak و SHA-3 (FIPS 202):**\n🔍 **تمييز مهم**: Keccak الأصلي و SHA-3 المُعياري **ليسا متطابقين**:\n- **Keccak الأصلي**: يستخدم سعة c = 2d وحشو مختلف (حشو Keccak: 0x01)\n- **FIPS 202 SHA-3**: يستخدم سعة c = 2d لكن حشو مختلف (حشو SHA-3: 0x06)\n- **فصل النطاق**: اختلاف الحشو يضمن أن Keccak و SHA-3 ينتجان مخرجات مختلفة لنفس المدخل\n- **هذه الأداة تطبق**: **مواصفة Keccak الأصلية** مع معاملة Keccak[c=2d]\n\n**حالة الأمان:**\n✅ **Keccak يُعتبر آمناً جداً** بدون هجمات عملية معروفة. يوفر هوامش أمان ممتازة ومقاومة ضد تقنيات التحليل المختلفة.\n\n**الاستخدامات الشائعة:**\n- بلوك تشين الإيثريوم (يستخدم Keccak-256 الأصلي)\n- البحث الأكاديمي والبروتوكولات التشفيرية\n- التطبيقات التي تتطلب مخرجات تشفير بطول متغير\n- الأنظمة التي تحتاج بدائل لعائلة SHA-2\n- تطبيقات البلوك تشين والعملات المشفرة\n\n**المزايا مقارنة بالتشفير التقليدي:**\n- التصميم المختلف جذرياً يقلل مخاطر الهجمات المرتبطة\n- طول إخراج مرن (غير محدود بأحجام ثابتة)\n- أساس أمان نظري قوي\n- مقاومة لهجمات تمديد الطول\n- أداء ممتاز على منصات مختلفة\n\n**ملاحظة تقنية:**\n- **Keccak-256**: ينتج إخراج 256 بت (المتغير الأكثر شيوعاً)\n- **معادلة السعة**: c = 2d تضمن مستوى الأمان المناسب\n- **استخدام الإيثريوم**: الإيثريوم يستخدم تحديداً Keccak-256 الأصلي، وليس SHA3-256"
  },
  "hi": {
    "what-is-keccak": "Keccak क्या है?",
    "what-is-keccak-description-markdown": "Keccak क्रिप्टोग्राफिक हैश फ़ंक्शन्स का एक परिवार है जो SHA-3 (Secure Hash Algorithm 3) मानक के लिए आधार का काम करता है। Guido Bertoni, Joan Daemen, Michaël Peeters, और Gilles Van Assche द्वारा विकसित, इसने 2012 में NIST हैश फ़ंक्शन प्रतियोगिता जीती।\n\n**मुख्य विशेषताएं:**\n- **स्पंज निर्माण**: अवशोषण और निचोड़ने के चरणों के साथ एक नवाचार स्पंज फ़ंक्शन डिज़ाइन का उपयोग करता है\n- **परिवर्तनीय आउटपुट लंबाई**: किसी भी वांछित लंबाई के हैश आउटपुट उत्पन्न कर सकता है\n- **उच्च सुरक्षा मार्जिन**: पर्याप्त सुरक्षा रिज़र्व के साथ डिज़ाइन किया गया\n- **SHA-1/SHA-2 से भिन्न**: पूरी तरह से अलग गणितीय सिद्धांतों पर आधारित\n- **Keccak[c=2d] वेरिएंट**: यह कार्यान्वयन मूल Keccak विनिर्देश का उपयोग करता है जिसमें क्षमता c = 2d (जहां d आउटपुट लंबाई है)\n\n**Keccak बनाम SHA-3 (FIPS 202) अंतर:**\n🔍 **महत्वपूर्ण अंतर**: मूल Keccak और मानकीकृत SHA-3 **समान नहीं हैं**:\n- **मूल Keccak**: क्षमता c = 2d और अलग पैडिंग (Keccak पैडिंग: 0x01) का उपयोग करता है\n- **FIPS 202 SHA-3**: क्षमता c = 2d का उपयोग करता है लेकिन अलग पैडिंग (SHA-3 पैडिंग: 0x06)\n- **डोमेन पृथक्करण**: पैडिंग अंतर सुनिश्चित करता है कि Keccak और SHA-3 समान इनपुट के लिए अलग आउटपुट उत्पन्न करते हैं\n- **यह उपकरण लागू करता है**: Keccak[c=2d] पैरामीटराइज़ेशन के साथ **मूल Keccak विनिर्देश**\n\n**सुरक्षा स्थिति:**\n✅ **Keccak को अत्यधिक सुरक्षित माना जाता है** बिना किसी ज्ञात व्यावहारिक हमलों के। यह उत्कृष्ट सुरक्षा मार्जिन और विभिन्न क्रिप्टोएनालिटिक तकनीकों के खिलाफ प्रतिरोध प्रदान करता है।\n\n**सामान्य उपयोग:**\n- Ethereum ब्लॉकचेन (मूल Keccak-256 का उपयोग करता है)\n- शैक्षणिक अनुसंधान और क्रिप्टोग्राफिक प्रोटोकॉल\n- परिवर्तनीय-लंबाई हैश आउटपुट की आवश्यकता वाले एप्लिकेशन\n- SHA-2 परिवार के विकल्प की आवश्यकता वाले सिस्टम\n- ब्लॉकचेन और क्रिप्टोकरेंसी कार्यान्वयन\n\n**पारंपरिक हैश पर लाभ:**\n- मौलिक रूप से अलग डिज़ाइन संबंधित हमलों के जोखिम को कम करता है\n- लचीली आउटपुट लंबाई (निश्चित आकारों तक सीमित नहीं)\n- मजबूत सैद्धांतिक सुरक्षा आधार\n- लंबाई विस्तार हमलों के लिए प्रतिरोध\n- विभिन्न प्लेटफार्मों पर उत्कृष्ट प्रदर्शन\n\n**तकनीकी नोट:**\n- **Keccak-256**: 256-बिट आउटपुट उत्पन्न करता है (सबसे आम वेरिएंट)\n- **क्षमता सूत्र**: c = 2d उपयुक्त सुरक्षा स्तर सुनिश्चित करता है\n- **Ethereum उपयोग**: Ethereum विशेष रूप से मूल Keccak-256 का उपयोग करता है, SHA3-256 का नहीं"
  },
  "tr": {
    "what-is-keccak": "Keccak nedir?",
    "what-is-keccak-description-markdown": "Keccak, SHA-3 (Secure Hash Algorithm 3) standardının temeli olarak hizmet eden kriptografik hash fonksiyonlarının bir ailesidir. Guido Bertoni, Joan Daemen, Michaël Peeters ve Gilles Van Assche tarafından geliştirilmiş ve 2012'de NIST hash fonksiyon yarışmasını kazanmıştır.\n\n**Ana özellikler:**\n- **Sünger yapısı**: Emme ve sıkma aşamaları olan yenilikçi sünger fonksiyon tasarımı kullanır\n- **Değişken çıktı uzunluğu**: İstenilen herhangi bir uzunlukta hash çıktıları üretebilir\n- **Yüksek güvenlik marjı**: Önemli güvenlik rezervleriyle tasarlanmış\n- **SHA-1/SHA-2'den farklı**: Tamamen farklı matematiksel ilkelere dayalı\n- **Keccak[c=2d] varyantı**: Bu uygulama kapasite c = 2d olan orijinal Keccak spezifikasyonunu kullanır (d çıktı uzunluğudur)\n\n**Keccak vs SHA-3 (FIPS 202) farkları:**\n🔍 **Önemli ayrım**: Orijinal Keccak ve standartlaştırılmış SHA-3 **aynı değildir**:\n- **Orijinal Keccak**: Kapasite c = 2d ve farklı dolgu kullanır (Keccak dolgusu: 0x01)\n- **FIPS 202 SHA-3**: Kapasite c = 2d kullanır ama farklı dolgu (SHA-3 dolgusu: 0x06)\n- **Alan ayrımı**: Dolgu farkı Keccak ve SHA-3'ün aynı girdi için farklı çıktılar üretmesini sağlar\n- **Bu araç uygular**: Keccak[c=2d] parametrizasyonu ile **orijinal Keccak spezifikasyonu**\n\n**Güvenlik durumu:**\n✅ **Keccak oldukça güvenli kabul edilir** bilinen pratik saldırılar olmadan. Mükemmel güvenlik marjları ve çeşitli kriptoanalitik tekniklere karşı direnç sağlar.\n\n**Yaygın kullanımlar:**\n- Ethereum blokzinciri (orijinal Keccak-256 kullanır)\n- Akademik araştırma ve kriptografik protokoller\n- Değişken uzunlukta hash çıktıları gerektiren uygulamalar\n- SHA-2 ailesine alternatif gereken sistemler\n- Blokzincir ve kripto para uygulamaları\n\n**Geleneksel hash'lere göre avantajları:**\n- Temelden farklı tasarım ilgili saldırı riskini azaltır\n- Esnek çıktı uzunluğu (sabit boyutlarla sınırlı değil)\n- Güçlü teorik güvenlik temeli\n- Uzunluk uzatma saldırılarına direnç\n- Çeşitli platformlarda mükemmel performans\n\n**Teknik not:**\n- **Keccak-256**: 256-bit çıktı üretir (en yaygın varyant)\n- **Kapasite formülü**: c = 2d uygun güvenlik seviyesini sağlar\n- **Ethereum kullanımı**: Ethereum özellikle orijinal Keccak-256 kullanır, SHA3-256'yı değil"
  },
  "nl": {
    "what-is-keccak": "Wat is Keccak?",
    "what-is-keccak-description-markdown": "Keccak is een familie van cryptografische hashfuncties die dient als basis voor de SHA-3 (Secure Hash Algorithm 3) standaard. Ontwikkeld door Guido Bertoni, Joan Daemen, Michaël Peeters en Gilles Van Assche, won het de NIST hashfunctie competitie in 2012.\n\n**Belangrijkste kenmerken:**\n- **Spons constructie**: Gebruikt een innovatief spons functie ontwerp met absorbeer- en uitkneep-fasen\n- **Variabele uitvoerlengte**: Kan hash-uitvoer van elke gewenste lengte produceren\n- **Hoge veiligheidsmarge**: Ontworpen met aanzienlijke veiligheidsreserves\n- **Verschilt van SHA-1/SHA-2**: Gebaseerd op volledig verschillende wiskundige principes\n- **Keccak[c=2d] variant**: Deze implementatie gebruikt de originele Keccak specificatie met capaciteit c = 2d (waarbij d de uitvoerlengte is)\n\n**Keccak vs SHA-3 (FIPS 202) verschillen:**\n🔍 **Belangrijke onderscheiding**: De originele Keccak en de gestandaardiseerde SHA-3 zijn **niet identiek**:\n- **Originele Keccak**: Gebruikt capaciteit c = 2d en andere padding (Keccak padding: 0x01)\n- **FIPS 202 SHA-3**: Gebruikt capaciteit c = 2d maar andere padding (SHA-3 padding: 0x06)\n- **Domeinscheiding**: Het padding verschil zorgt ervoor dat Keccak en SHA-3 verschillende uitvoer produceren voor dezelfde invoer\n- **Deze tool implementeert**: De **originele Keccak specificatie** met Keccak[c=2d] parametrisatie\n\n**Veiligheidsstatus:**\n✅ **Keccak wordt beschouwd als zeer veilig** zonder bekende praktische aanvallen. Het biedt uitstekende veiligheidsmarges en weerstand tegen verschillende cryptoanalytische technieken.\n\n**Veelvoorkomende toepassingen:**\n- Ethereum blockchain (gebruikt originele Keccak-256)\n- Academisch onderzoek en cryptografische protocollen\n- Applicaties die hash-uitvoer van variabele lengte vereisen\n- Systemen die alternatieven voor de SHA-2 familie nodig hebben\n- Blockchain en cryptocurrency implementaties\n\n**Voordelen ten opzichte van traditionele hashes:**\n- Fundamenteel ander ontwerp vermindert risico van gerelateerde aanvallen\n- Flexibele uitvoerlengte (niet beperkt tot vaste groottes)\n- Sterke theoretische veiligheidsbasis\n- Weerstand tegen lengte-uitbreidingsaanvallen\n- Uitstekende prestaties op verschillende platforms\n\n**Technische opmerking:**\n- **Keccak-256**: Produceert 256-bit uitvoer (meest voorkomende variant)\n- **Capaciteitsformule**: c = 2d zorgt voor geschikt veiligheidsniveau\n- **Ethereum gebruik**: Ethereum gebruikt specifiek originele Keccak-256, niet SHA3-256"
  },
  "sv": {
    "what-is-keccak": "Vad är Keccak?",
    "what-is-keccak-description-markdown": "Keccak är en familj av kryptografiska hash-funktioner som fungerar som grund för SHA-3 (Secure Hash Algorithm 3) standarden. Utvecklad av Guido Bertoni, Joan Daemen, Michaël Peeters och Gilles Van Assche, vann den NIST hash-funktions tävlingen 2012.\n\n**Nyckelegenskaper:**\n- **Svamp-konstruktion**: Använder en innovativ svamp-funktions design med absorbering och utkramning faser\n- **Variabel utmatningslängd**: Kan producera hash-utmatningar av valfri önskad längd\n- **Hög säkerhetsmarginal**: Designad med betydande säkerhetsreserver\n- **Skiljer sig från SHA-1/SHA-2**: Baserad på helt olika matematiska principer\n- **Keccak[c=2d] variant**: Denna implementation använder den ursprungliga Keccak specifikationen med kapacitet c = 2d (där d är utmatningslängden)\n\n**Keccak vs SHA-3 (FIPS 202) skillnader:**\n🔍 **Viktig åtskillnad**: Den ursprungliga Keccak och den standardiserade SHA-3 är **inte identiska**:\n- **Ursprunglig Keccak**: Använder kapacitet c = 2d och olika utfyllnad (Keccak utfyllnad: 0x01)\n- **FIPS 202 SHA-3**: Använder kapacitet c = 2d men olika utfyllnad (SHA-3 utfyllnad: 0x06)\n- **Domänseparation**: Utfyllnadsskillnaden säkerställer att Keccak och SHA-3 producerar olika utmatningar för samma inmatning\n- **Detta verktyg implementerar**: Den **ursprungliga Keccak specifikationen** med Keccak[c=2d] parametrisering\n\n**Säkerhetsstatus:**\n✅ **Keccak anses vara mycket säker** utan kända praktiska attacker. Det ger utmärkta säkerhetsmarginaler och motstånd mot olika kryptoanalytiska tekniker.\n\n**Vanliga användningar:**\n- Ethereum blockchain (använder ursprunglig Keccak-256)\n- Akademisk forskning och kryptografiska protokoll\n- Applikationer som kräver hash-utmatningar av variabel längd\n- System som behöver alternativ till SHA-2 familjen\n- Blockchain och kryptovaluta implementationer\n\n**Fördelar över traditionella hasher:**\n- Fundamentalt olika design minskar risken för relaterade attacker\n- Flexibel utmatningslängd (inte begränsad till fasta storlekar)\n- Stark teoretisk säkerhetsgrund\n- Motstånd mot längdförlängningsattacker\n- Utmärkt prestanda på olika plattformar\n\n**Teknisk notering:**\n- **Keccak-256**: Producerar 256-bit utmatning (vanligaste varianten)\n- **Kapacitetsformel**: c = 2d säkerställer lämplig säkerhetsnivå\n- **Ethereum användning**: Ethereum använder specifikt ursprunglig Keccak-256, inte SHA3-256"
  },
  "pl": {
    "what-is-keccak": "Czym jest Keccak?",
    "what-is-keccak-description-markdown": "Keccak to rodzina kryptograficznych funkcji skrótu, która służy jako podstawa dla standardu SHA-3 (Secure Hash Algorithm 3). Opracowana przez Guido Bertoni, Joan Daemen, Michaël Peeters i Gilles Van Assche, wygrała konkurs funkcji skrótu NIST w 2012 roku.\n\n**Kluczowe cechy:**\n- **Konstrukcja gąbki**: Używa innowacyjnego projektu funkcji gąbki z fazami wchłaniania i wyciskania\n- **Zmienna długość wyjścia**: Może produkować wyjścia skrótu o dowolnej pożądanej długości\n- **Wysoki margines bezpieczeństwa**: Zaprojektowana z znacznymi rezerwami bezpieczeństwa\n- **Różni się od SHA-1/SHA-2**: Oparta na całkowicie różnych zasadach matematycznych\n- **Wariant Keccak[c=2d]**: Ta implementacja używa oryginalnej specyfikacji Keccak z pojemnością c = 2d (gdzie d to długość wyjścia)\n\n**Różnice między Keccak a SHA-3 (FIPS 202):**\n🔍 **Ważne rozróżnienie**: Oryginalny Keccak i znormalizowany SHA-3 **nie są identyczne**:\n- **Oryginalny Keccak**: Używa pojemności c = 2d i innego dopełniania (dopełnianie Keccak: 0x01)\n- **FIPS 202 SHA-3**: Używa pojemności c = 2d ale innego dopełniania (dopełnianie SHA-3: 0x06)\n- **Separacja domen**: Różnica w dopełnianiu zapewnia, że Keccak i SHA-3 produkują różne wyjścia dla tego samego wejścia\n- **To narzędzie implementuje**: **Oryginalną specyfikację Keccak** z parametryzacją Keccak[c=2d]\n\n**Status bezpieczeństwa:**\n✅ **Keccak jest uważane za wysoce bezpieczne** bez znanych praktycznych ataków. Zapewnia doskonałe marginesy bezpieczeństwa i odporność na różne techniki kryptoanalizy.\n\n**Powszechne zastosowania:**\n- Blockchain Ethereum (używa oryginalnego Keccak-256)\n- Badania akademickie i protokoły kryptograficzne\n- Aplikacje wymagające wyjść skrótu o zmiennej długości\n- Systemy potrzebujące alternatyw dla rodziny SHA-2\n- Implementacje blockchain i kryptowalut\n\n**Zalety nad tradycyjnymi skrótami:**\n- Fundamentalnie inny projekt zmniejsza ryzyko powiązanych ataków\n- Elastyczna długość wyjścia (nie ograniczona do stałych rozmiarów)\n- Silna teoretyczna podstawa bezpieczeństwa\n- Odporność na ataki rozszerzania długości\n- Doskonała wydajność na różnych platformach\n\n**Uwaga techniczna:**\n- **Keccak-256**: Produkuje 256-bitowe wyjście (najczęstsza odmiana)\n- **Formuła pojemności**: c = 2d zapewnia odpowiedni poziom bezpieczeństwa\n- **Użycie Ethereum**: Ethereum używa specjalnie oryginalnego Keccak-256, a nie SHA3-256"
  },
  "vi": {
    "what-is-keccak": "Keccak là gì?",
    "what-is-keccak-description-markdown": "Keccak là một họ các hàm băm mật mã phục vụ như nền tảng cho tiêu chuẩn SHA-3 (Secure Hash Algorithm 3). Được phát triển bởi Guido Bertoni, Joan Daemen, Michaël Peeters và Gilles Van Assche, nó đã thắng cuộc thi hàm băm NIST năm 2012.\n\n**Đặc điểm chính:**\n- **Cấu trúc bọt biển**: Sử dụng thiết kế hàm bọt biển sáng tạo với các giai đoạn hấp thụ và vắt\n- **Độ dài đầu ra thay đổi**: Có thể tạo ra đầu ra băm với bất kỳ độ dài mong muốn nào\n- **Biên độ bảo mật cao**: Được thiết kế với dự trữ bảo mật đáng kể\n- **Khác với SHA-1/SHA-2**: Dựa trên các nguyên lý toán học hoàn toàn khác\n- **Biến thể Keccak[c=2d]**: Triển khai này sử dụng đặc tả Keccak gốc với dung lượng c = 2d (trong đó d là độ dài đầu ra)\n\n**Sự khác biệt giữa Keccak và SHA-3 (FIPS 202):**\n🔍 **Phân biệt quan trọng**: Keccak gốc và SHA-3 được tiêu chuẩn hóa **không giống nhau**:\n- **Keccak gốc**: Sử dụng dung lượng c = 2d và padding khác (padding Keccak: 0x01)\n- **FIPS 202 SHA-3**: Sử dụng dung lượng c = 2d nhưng padding khác (padding SHA-3: 0x06)\n- **Tách biệt miền**: Sự khác biệt padding đảm bảo Keccak và SHA-3 tạo ra đầu ra khác nhau cho cùng đầu vào\n- **Công cụ này triển khai**: **Đặc tả Keccak gốc** với tham số hóa Keccak[c=2d]\n\n**Tình trạng bảo mật:**\n✅ **Keccak được coi là rất an toàn** không có cuộc tấn công thực tế nào được biết đến. Nó cung cấp biên độ bảo mật xuất sắc và khả năng chống lại các kỹ thuật phân tích mật mã khác nhau.\n\n**Sử dụng phổ biến:**\n- Blockchain Ethereum (sử dụng Keccak-256 gốc)\n- Nghiên cứu học thuật và các giao thức mật mã\n- Các ứng dụng yêu cầu đầu ra băm có độ dài thay đổi\n- Các hệ thống cần thay thế cho họ SHA-2\n- Triển khai blockchain và tiền điện tử\n\n**Ưu điểm so với băm truyền thống:**\n- Thiết kế cơ bản khác giảm nguy cơ các cuộc tấn công liên quan\n- Độ dài đầu ra linh hoạt (không giới hạn ở kích thước cố định)\n- Nền tảng bảo mật lý thuyết mạnh mẽ\n- Kháng cự với các cuộc tấn công mở rộng độ dài\n- Hiệu suất xuất sắc trên nhiều nền tảng khác nhau\n\n**Ghi chú kỹ thuật:**\n- **Keccak-256**: Tạo ra đầu ra 256-bit (biến thể phổ biến nhất)\n- **Công thức dung lượng**: c = 2d đảm bảo mức bảo mật phù hợp\n- **Sử dụng Ethereum**: Ethereum đặc biệt sử dụng Keccak-256 gốc, không phải SHA3-256"
  },
  "th": {
    "what-is-keccak": "Keccak คืออะไร?",
    "what-is-keccak-description-markdown": "Keccak เป็นตระกูลของฟังก์ชันแฮชเข้ารหัสที่ทำหน้าที่เป็นพื้นฐานสำหรับมาตรฐาน SHA-3 (Secure Hash Algorithm 3) พัฒนาโดย Guido Bertoni, Joan Daemen, Michaël Peeters และ Gilles Van Assche ชนะการแข่งขันฟังก์ชันแฮช NIST ในปี 2012\n\n**คุณลักษณะสำคัญ:**\n- **โครงสร้างฟองน้ำ**: ใช้การออกแบบฟังก์ชันฟองน้ำที่เป็นนวัตกรรมใหม่ด้วยขั้นตอนการดูดซับและการบีบ\n- **ความยาวเอาต์พุตแปรผัน**: สามารถสร้างเอาต์พุตแฮชที่มีความยาวตามต้องการ\n- **ขอบเขตความปลอดภัยสูง**: ออกแบบมาพร้อมกับสำรองความปลอดภัยที่สำคัญ\n- **แตกต่างจาก SHA-1/SHA-2**: อิงจากหลักการทางคณิตศาสตร์ที่แตกต่างโดยสิ้นเชิง\n- **ตัวแปร Keccak[c=2d]**: การนำไปใช้นี้ใช้ข้อกำหนด Keccak ต้นฉบับด้วยความจุ c = 2d (โดยที่ d คือความยาวเอาต์พุต)\n\n**ความแตกต่างระหว่าง Keccak และ SHA-3 (FIPS 202):**\n🔍 **ความแตกต่างที่สำคัญ**: Keccak ต้นฉบับและ SHA-3 ที่มาตรฐาน **ไม่เหมือนกัน**:\n- **Keccak ต้นฉบับ**: ใช้ความจุ c = 2d และการเติมที่แตกต่าง (การเติม Keccak: 0x01)\n- **FIPS 202 SHA-3**: ใช้ความจุ c = 2d แต่การเติมที่แตกต่าง (การเติม SHA-3: 0x06)\n- **การแยกโดเมน**: ความแตกต่างของการเติมทำให้ Keccak และ SHA-3 สร้างเอาต์พุตที่แตกต่างกันสำหรับอินพุตเดียวกัน\n- **เครื่องมือนี้ใช้**: **ข้อกำหนด Keccak ต้นฉบับ** ด้วยการกำหนดพารามิเตอร์ Keccak[c=2d]\n\n**สถานะความปลอดภัย:**\n✅ **Keccak ถือว่าปลอดภัยสูง** โดยไม่มีการโจมตีที่ใช้งานได้จริงที่ทราบ มันให้ขอบเขตความปลอดภัยที่ยอดเยี่ยมและความต้านทานต่อเทคนิคการวิเคราะห์การเข้ารหัสต่างๆ\n\n**การใช้งานทั่วไป:**\n- บล็อกเชน Ethereum (ใช้ Keccak-256 ต้นฉบับ)\n- การวิจัยทางวิชาการและโปรโตคอลการเข้ารหัส\n- แอปพลิเคชันที่ต้องการเอาต์พุตแฮชที่มีความยาวแปรผัน\n- ระบบที่ต้องการทางเลือกจากตระกูล SHA-2\n- การใช้งานบล็อกเชนและสกุลเงินดิจิทัล\n\n**ข้อดีเหนือแฮชแบบดั้งเดิม:**\n- การออกแบบที่แตกต่างโดยพื้นฐานลดความเสี่ยงของการโจมตีที่เกี่ยวข้อง\n- ความยาวเอาต์พุตที่ยืดหยุ่น (ไม่จำกัดเฉพาะขนาดคงที่)\n- พื้นฐานความปลอดภัยเชิงทฤษฎีที่แข็งแกร่ง\n- ความต้านทานต่อการโจมตีการขยายความยาว\n- ประสิทธิภาพที่ยอดเยี่ยมบนแพลตฟอร์มต่างๆ\n\n**หมายเหตุทางเทคนิค:**\n- **Keccak-256**: สร้างเอาต์พุต 256-บิต (ตัวแปรที่พบบ่อยที่สุด)\n- **สูตรความจุ**: c = 2d รับประกันระดับความปลอดภัยที่เหมาะสม\n- **การใช้งาน Ethereum**: Ethereum ใช้โดยเฉพาะ Keccak-256 ต้นฉบับ ไม่ใช่ SHA3-256"
  },
  "id": {
    "what-is-keccak": "Apa itu Keccak?",
    "what-is-keccak-description-markdown": "Keccak adalah keluarga fungsi hash kriptografi yang berfungsi sebagai dasar untuk standar SHA-3 (Secure Hash Algorithm 3). Dikembangkan oleh Guido Bertoni, Joan Daemen, Michaël Peeters, dan Gilles Van Assche, memenangkan kompetisi fungsi hash NIST pada 2012.\n\n**Karakteristik utama:**\n- **Konstruksi spons**: Menggunakan desain fungsi spons inovatif dengan fase penyerapan dan pemerasan\n- **Panjang output variabel**: Dapat menghasilkan output hash dengan panjang yang diinginkan\n- **Margin keamanan tinggi**: Dirancang dengan cadangan keamanan yang substansial\n- **Berbeda dari SHA-1/SHA-2**: Berdasarkan prinsip matematika yang sepenuhnya berbeda\n- **Varian Keccak[c=2d]**: Implementasi ini menggunakan spesifikasi Keccak asli dengan kapasitas c = 2d (di mana d adalah panjang output)\n\n**Perbedaan Keccak vs SHA-3 (FIPS 202):**\n🔍 **Perbedaan penting**: Keccak asli dan SHA-3 yang distandarisasi **tidak identik**:\n- **Keccak asli**: Menggunakan kapasitas c = 2d dan padding berbeda (padding Keccak: 0x01)\n- **FIPS 202 SHA-3**: Menggunakan kapasitas c = 2d tetapi padding berbeda (padding SHA-3: 0x06)\n- **Pemisahan domain**: Perbedaan padding memastikan Keccak dan SHA-3 menghasilkan output berbeda untuk input yang sama\n- **Tool ini mengimplementasikan**: **Spesifikasi Keccak asli** dengan parametrisasi Keccak[c=2d]\n\n**Status keamanan:**\n✅ **Keccak dianggap sangat aman** tanpa serangan praktis yang diketahui. Memberikan margin keamanan yang sangat baik dan ketahanan terhadap berbagai teknik kriptoanalisis.\n\n**Penggunaan umum:**\n- Blockchain Ethereum (menggunakan Keccak-256 asli)\n- Penelitian akademis dan protokol kriptografi\n- Aplikasi yang memerlukan output hash dengan panjang variabel\n- Sistem yang membutuhkan alternatif keluarga SHA-2\n- Implementasi blockchain dan cryptocurrency\n\n**Keunggulan dibanding hash tradisional:**\n- Desain yang fundamental berbeda mengurangi risiko serangan terkait\n- Panjang output fleksibel (tidak terbatas pada ukuran tetap)\n- Fondasi keamanan teoritis yang kuat\n- Ketahanan terhadap serangan perpanjangan panjang\n- Kinerja sangat baik di berbagai platform\n\n**Catatan teknis:**\n- **Keccak-256**: Menghasilkan output 256-bit (varian paling umum)\n- **Formula kapasitas**: c = 2d memastikan tingkat keamanan yang sesuai\n- **Penggunaan Ethereum**: Ethereum secara khusus menggunakan Keccak-256 asli, bukan SHA3-256"
  },
  "he": {
    "what-is-keccak": "מה זה Keccak?",
    "what-is-keccak-description-markdown": "Keccak הוא משפחה של פונקציות האש הקריפטוגרפיות המשמשת כבסיס לתקן SHA-3 (Secure Hash Algorithm 3). פותח על ידי Guido Bertoni, Joan Daemen, Michaël Peeters ו-Gilles Van Assche, וזכה בתחרות פונקציות האש של NIST ב-2012.\n\n**מאפיינים עיקריים:**\n- **מבנה ספוג**: משתמש בעיצוב פונקציית ספוג חדשני עם שלבי ספיגה וסחיטה\n- **אורך פלט משתנה**: יכול לייצר פלטי האש באורך כלשהו שרוצים\n- **מרווח אבטחה גבוה**: מעוצב עם עתודות אבטחה משמעותיות\n- **שונה מ-SHA-1/SHA-2**: מבוסס על עקרונות מתמטיים שונים לחלוטין\n- **וריאנט Keccak[c=2d]**: יישום זה משתמש במפרט Keccak המקורי עם קיבולת c = 2d (כאשר d הוא אורך הפלט)\n\n**הבדלים בין Keccak ל-SHA-3 (FIPS 202):**\n🔍 **הבחנה חשובה**: Keccak המקורי ו-SHA-3 המתוקנן **אינם זהים**:\n- **Keccak מקורי**: משתמש בקיבולת c = 2d ובריפוד שונה (ריפוד Keccak: 0x01)\n- **FIPS 202 SHA-3**: משתמש בקיבולת c = 2d אך בריפוד שונה (ריפוד SHA-3: 0x06)\n- **הפרדת תחומים**: הבדל הריפוד מבטיח שKeccak ו-SHA-3 מייצרים פלטים שונים לאותו קלט\n- **יישום כלי זה**: **מפרט Keccak המקורי** עם פרמטריזציה Keccak[c=2d]\n\n**מצב אבטחה:**\n✅ **Keccak נחשב בטוח ביותר** ללא התקפות מעשיות ידועות. הוא מספק מרווחי אבטחה מצוינים ועמידות נגד טכניקות ניתוח קריפטוגרפי שונות.\n\n**שימושים נפוצים:**\n- בלוקצ'יין Ethereum (משתמש ב-Keccak-256 המקורי)\n- מחקר אקדמי ופרוטוקולים קריפטוגרפיים\n- יישומים הדורשים פלטי האש באורכים משתנים\n- מערכות הדורשות חלופה למשפחת SHA-2\n- יישומי בלוקצ'יין ומטבעות קריפטוגרפיים\n\n**יתרונות על פני האש מסורתיים:**\n- עיצוב שונה בתכלית מפחית סיכון התקפות קשורות\n- אורך פלט גמיש (לא מוגבל לגדלים קבועים)\n- בסיס אבטחה תיאורטי חזק\n- עמידות נגד התקפות הארכת אורך\n- ביצועים מצוינים בפלטפורמות שונות\n\n**הערות טכניות:**\n- **Keccak-256**: מייצר פלט של 256-ביט (הוריאנט הנפוץ ביותר)\n- **נוסחת קיבולת**: c = 2d מבטיח רמת אבטחה מתאימה\n- **שימוש ב-Ethereum**: Ethereum משתמש ספציפית ב-Keccak-256 המקורי ולא ב-SHA3-256"
  },
  "ms": {
    "what-is-keccak": "Apakah Keccak?",
    "what-is-keccak-description-markdown": "Keccak adalah keluarga fungsi hash kriptografi yang berfungsi sebagai asas untuk standard SHA-3 (Secure Hash Algorithm 3). Dibangunkan oleh Guido Bertoni, Joan Daemen, Michaël Peeters dan Gilles Van Assche, ia memenangi pertandingan fungsi hash NIST pada 2012.\n\n**Ciri-ciri utama:**\n- **Pembinaan span**: Menggunakan reka bentuk fungsi span inovatif dengan fasa penyerapan dan pemerasan\n- **Panjang output berubah**: Dapat menghasilkan output hash dengan sebarang panjang yang dikehendaki\n- **Margin keselamatan tinggi**: Direka dengan rizab keselamatan yang besar\n- **Berbeza daripada SHA-1/SHA-2**: Berdasarkan prinsip matematik yang sama sekali berbeza\n- **Varian Keccak[c=2d]**: Pelaksanaan ini menggunakan spesifikasi Keccak asal dengan kapasiti c = 2d (di mana d ialah panjang output)\n\n**Perbezaan Keccak vs SHA-3 (FIPS 202):**\n🔍 **Perbezaan penting**: Keccak asal dan SHA-3 piawai **tidak sama**:\n- **Keccak asal**: Menggunakan kapasiti c = 2d dan padding berbeza (padding Keccak: 0x01)\n- **FIPS 202 SHA-3**: Menggunakan kapasiti c = 2d tetapi padding berbeza (padding SHA-3: 0x06)\n- **Pemisahan domain**: Perbezaan padding memastikan Keccak dan SHA-3 menghasilkan output berbeza untuk input yang sama\n- **Pelaksanaan alat ini**: **Spesifikasi Keccak asal** dengan parameterisasi Keccak[c=2d]\n\n**Status keselamatan:**\n✅ **Keccak dianggap sangat selamat** tanpa serangan praktikal yang diketahui. Ia menyediakan margin keselamatan yang cemerlang dan rintangan terhadap pelbagai teknik analisis kriptografi.\n\n**Kegunaan biasa:**\n- Blockchain Ethereum (menggunakan Keccak-256 asal)\n- Penyelidikan akademik dan protokol kriptografi\n- Aplikasi yang memerlukan output hash panjang berubah\n- Sistem yang memerlukan alternatif kepada keluarga SHA-2\n- Pelaksanaan blockchain dan mata wang kripto\n\n**Kelebihan berbanding hash tradisional:**\n- Reka bentuk yang berbeza secara asas mengurangkan risiko serangan berkaitan\n- Panjang output fleksibel (tidak terhad kepada saiz tetap)\n- Asas keselamatan teori yang kukuh\n- Rintangan terhadap serangan sambungan panjang\n- Prestasi cemerlang merentas pelbagai platform\n\n**Nota teknikal:**\n- **Keccak-256**: Menghasilkan output 256-bit (varian paling biasa)\n- **Formula kapasiti**: c = 2d memastikan tahap keselamatan yang sesuai\n- **Penggunaan Ethereum**: Ethereum secara khusus menggunakan Keccak-256 asal, bukan SHA3-256"
  },
  "no": {
    "what-is-keccak": "Hva er Keccak?",
    "what-is-keccak-description-markdown": "Keccak er en familie av kryptografiske hash-funksjoner som fungerer som grunnlag for SHA-3 (Secure Hash Algorithm 3) standarden. Utviklet av Guido Bertoni, Joan Daemen, Michaël Peeters og Gilles Van Assche, vant den NIST hash-funksjonskonkurransen i 2012.\n\n**Nøkkelegenskaper:**\n- **Svamp-konstruksjon**: Bruker et innovativt svamp-funksjonsdesign med absorpsjons- og utpressingsfaser\n- **Variabel utdatalengde**: Kan produsere hash-utdata av ønsket lengde\n- **Høy sikkerhetsmarginn**: Designet med betydelige sikkerhetsreserver\n- **Forskjellig fra SHA-1/SHA-2**: Basert på helt andre matematiske prinsipper\n- **Keccak[c=2d] variant**: Denne implementeringen bruker den opprinnelige Keccak-spesifikasjonen med kapasitet c = 2d (hvor d er utdatalengden)\n\n**Forskjeller mellom Keccak og SHA-3 (FIPS 202):**\n🔍 **Viktig skille**: Den opprinnelige Keccak og standardiserte SHA-3 er **ikke identiske**:\n- **Opprinnelig Keccak**: Bruker kapasitet c = 2d og annerledes padding (Keccak padding: 0x01)\n- **FIPS 202 SHA-3**: Bruker kapasitet c = 2d men annerledes padding (SHA-3 padding: 0x06)\n- **Domeneseparasjon**: Padding-forskjellen sikrer at Keccak og SHA-3 produserer forskjellige utdata for samme inndata\n- **Dette verktøyets implementering**: **Opprinnelig Keccak-spesifikasjon** med Keccak[c=2d] parametrisering\n\n**Sikkerhetsstatus:**\n✅ **Keccak anses som svært sikker** uten kjente praktiske angrep. Det gir utmerkede sikkerhetsmarginer og motstand mot forskjellige kryptanalytiske teknikker.\n\n**Vanlige bruksområder:**\n- Ethereum blockchain (bruker opprinnelig Keccak-256)\n- Akademisk forskning og kryptografiske protokoller\n- Applikasjoner som krever hash-utdata med variabel lengde\n- Systemer som trenger et alternativ til SHA-2-familien\n- Blockchain- og kryptovaluta-implementeringer\n\n**Fordeler over tradisjonelle hashes:**\n- Fundamentalt annerledes design reduserer risiko for relaterte angrep\n- Fleksibel utdatalengde (ikke begrenset til faste størrelser)\n- Sterkt teoretisk sikkerhetsfundament\n- Motstand mot lengdeutvidelsesangrep\n- Utmerket ytelse på tvers av forskjellige plattformer\n\n**Tekniske merknader:**\n- **Keccak-256**: Produserer 256-bits utdata (mest vanlige variant)\n- **Kapasitetsformel**: c = 2d sikrer passende sikkerhetsnivå\n- **Ethereum-bruk**: Ethereum bruker spesifikt opprinnelig Keccak-256, ikke SHA3-256"
  }
}
</i18n>
