packages:
  - packages/*
  - apps/*
  - tools/*
  - tools/**/*
  - shared/*
  - utils/*
  - registry/*

catalog:
  '@intlify/unplugin-vue-i18n': ^6.0.8
  '@jsquash/oxipng': ^2.3.0
  '@playwright/test': ^1.54.1
  '@prettier/plugin-oxc': 0.0.4
  '@tsconfig/node22': ^22.0.2
  '@types/jsdom': ^21.1.7
  '@types/node': ^22.16.5
  '@types/validator': ^13.15.2
  '@unhead/vue': 2.0.14
  '@vicons/antd': ^0.13.0
  '@vicons/carbon': ^0.13.0
  '@vicons/fa': ^0.13.0
  '@vicons/fluent': ^0.13.0
  '@vicons/ionicons4': ^0.13.0
  '@vicons/ionicons5': ^0.13.0
  '@vicons/material': ^0.13.0
  '@vicons/tabler': ^0.13.0
  '@vitejs/plugin-vue': ^6.0.1
  '@vitest/eslint-plugin': ^1.3.4
  '@vue/eslint-config-prettier': ^10.2.0
  '@vue/eslint-config-typescript': ^14.6.0
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.7.0
  '@vueuse/core': 13.6.0
  '@zip.js/zip.js': ^2.7.72
  eslint: ^9.32.0
  eslint-plugin-oxlint: ~1.12.0
  eslint-plugin-playwright: ^2.2.2
  eslint-plugin-vue: ~10.3.0
  highlight.js: 11.11.1
  jiti: ^2.4.2
  jsdom: ^26.1.0
  naive-ui: ^2.42.0
  npm-run-all2: ^8.0.4
  oxlint: ~1.8.0
  pinia: 3.0.3
  prettier: 3.6.2
  svgo: ^4.0.0
  typescript: ~5.8.0
  uuid: ^11.1.0
  validator: ^13.15.15
  vite: ^7
  vite-plugin-vue-devtools: ^8.0.0
  vitest: ^3.2.4
  vue: 3.5.18
  vue-i18n: ^11.1.11
  vue-router: ^4.5.1
  vue-tsc: ^3.0.4

onlyBuiltDependencies:
  - esbuild
