<template>
  <main>
    <BackButton />
    <n-h1 prefix="bar" align-text>Version 3 UUID</n-h1>
    <UUIDV3Generator :config="config" />
    <n-h2 prefix="bar" align-text>Config</n-h2>
    <UUIDV35Config v-model:config="config" />
    <n-h2 prefix="bar" align-text>What is a version 3 UUID?</n-h2>
    <n-p>
      Version-3 UUIDs are generated by hashing a namespace identifier and name. Version 3 uses MD5
      as the hashing algorithm.
    </n-p>
  </main>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { NH2, NH1, NP } from 'naive-ui'
import type { UUIDV35Config as UUIDV35ConfigType } from '../utils/uuid/config/UUIDV35Config'
import UUIDV3Generator from '../components/uuid/generator/UUIDV3Generator.vue'
import UUIDV35Config from '../components/uuid/config/UUIDV35Config.vue'
import { v4 as uuidv4 } from 'uuid'
import BackButton from '@/components/navigate/BackButton.vue'
import { useTitle, useDescription } from '@/composables/head'

useTitle('Version 3 UUID Generator')
useDescription('Generate version 3 UUID.')

const config = ref<UUIDV35ConfigType>({
  namespace: uuidv4(),
  name: 'example'
})
</script>
