<template>
  <ToolViewTemplate title="Version 5 UUID Generator">
    <UUIDV5Generator :config="config" />
    <n-h2 prefix="bar" align-text>Config</n-h2>
    <UUIDV35Config v-model:config="config" />
    <n-h2 prefix="bar" align-text>What is a version 5 UUID?</n-h2>
    <n-p>
      Version-5 UUIDs are generated by hashing a namespace identifier and name. Version 5 uses SHA-1
      as the hashing algorithm.
    </n-p>
  </ToolViewTemplate>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { NH2, NP } from 'naive-ui'
import type { UUIDV35Config as UUIDV35ConfigType } from '../utils/uuid/config/UUIDV35Config'
import UUIDV5Generator from '../components/uuid/generator/UUIDV5Generator.vue'
import UUIDV35Config from '../components/uuid/config/UUIDV35Config.vue'
import { v4 as uuidv4 } from 'uuid'
import { useTitle, useDescription } from '@/composables/head'
import ToolViewTemplate from '@/components/layouts/tool-view-template/ToolViewTemplate.vue'

useTitle('Version 5 UUID Generator')
useDescription('Generate version 5 UUID.')

const config = ref<UUIDV35ConfigType>({
  namespace: uuidv4(),
  name: 'example'
})
</script>
