<template>
  <DescriptionMarkdown
    :title="t('what-is-sri')"
    :description="t('what-is-sri-description-markdown')"
  />
</template>

<script setup lang="ts">
import { DescriptionMarkdown } from '@shared/ui/base'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()
</script>

<i18n lang="json">
{
  "en": {
    "what-is-sri": "What is Subresource Integrity (SRI)?",
    "what-is-sri-description-markdown": "Subresource Integrity (SRI) is a security feature that enables browsers to verify that files they fetch (e.g., from a CDN) haven\u2019t been unexpectedly modified. It works by comparing the cryptographic hash of a resource with a hash provided in the HTML.\n\n**How it works:**\n1. Generate a cryptographic hash of your resource file\n2. Include the hash in the integrity attribute of script or link tags\n3. Browser fetches the resource and calculates its hash\n4. Browser compares calculated hash with provided hash\n5. If hashes match, resource loads; if not, loading is blocked\n\n**Benefits:**\n- **Security**: Protects against malicious modifications of third-party resources\n- **CDN protection**: Ensures CDN-served files haven\u2019t been tampered with\n- **Supply chain security**: Validates integrity of external dependencies\n- **Browser support**: Widely supported across modern browsers\n\n**Supported algorithms:**\n- SHA-256 (recommended minimum)\n- SHA-384 (recommended)\n- SHA-512 (highest security)"
  },
  "zh": {
    "what-is-sri": "什么是子资源完整性（SRI）？",
    "what-is-sri-description-markdown": "子资源完整性（SRI）是一种安全功能，使浏览器能够验证它们获取的文件（例如来自 CDN）没有被意外修改。它通过将资源的加密哈希与 HTML 中提供的哈希进行比较来工作。\n\n**工作原理：**\n1. 生成资源文件的加密哈希\n2. 在 script 或 link 标签的 integrity 属性中包含哈希\n3. 浏览器获取资源并计算其哈希\n4. 浏览器将计算的哈希与提供的哈希进行比较\n5. 如果哈希匹配，资源加载；如果不匹配，加载被阻止\n\n**优势：**\n- **安全性**：防止第三方资源被恶意修改\n- **CDN 保护**：确保 CDN 提供的文件没有被篡改\n- **供应链安全**：验证外部依赖项的完整性\n- **浏览器支持**：在现代浏览器中广泛支持\n\n**支持的算法：**\n- SHA-256（推荐最低）\n- SHA-384（推荐）\n- SHA-512（最高安全性）"
  },
  "zh-CN": {
    "what-is-sri": "什么是子资源完整性（SRI）？",
    "what-is-sri-description-markdown": "子资源完整性（SRI）是一种安全功能，使浏览器能够验证它们获取的文件（例如来自 CDN）没有被意外修改。它通过将资源的加密哈希与 HTML 中提供的哈希进行比较来工作。\n\n**工作原理：**\n1. 生成资源文件的加密哈希\n2. 在 script 或 link 标签的 integrity 属性中包含哈希\n3. 浏览器获取资源并计算其哈希\n4. 浏览器将计算的哈希与提供的哈希进行比较\n5. 如果哈希匹配，资源加载；如果不匹配，加载被阻止\n\n**优势：**\n- **安全性**：防止第三方资源被恶意修改\n- **CDN 保护**：确保 CDN 提供的文件没有被篡改\n- **供应链安全**：验证外部依赖项的完整性\n- **浏览器支持**：在现代浏览器中广泛支持\n\n**支持的算法：**\n- SHA-256（推荐最低）\n- SHA-384（推荐）\n- SHA-512（最高安全性）"
  },
  "zh-TW": {
    "what-is-sri": "什麼是子資源完整性（SRI）？",
    "what-is-sri-description-markdown": "子資源完整性（SRI）是一種安全功能，使瀏覽器能夠驗證它們獲取的檔案（例如來自 CDN）沒有被意外修改。它通過將資源的加密雜湊與 HTML 中提供的雜湊進行比較來工作。\n\n**工作原理：**\n1. 生成資源檔案的加密雜湊\n2. 在 script 或 link 標籤的 integrity 屬性中包含雜湊\n3. 瀏覽器獲取資源並計算其雜湊\n4. 瀏覽器將計算的雜湊與提供的雜湊進行比較\n5. 如果雜湊匹配，資源載入；如果不匹配，載入被阻止\n\n**優勢：**\n- **安全性**：防止第三方資源被惡意修改\n- **CDN 保護**：確保 CDN 提供的檔案沒有被篡改\n- **供應鏈安全**：驗證外部依賴項的完整性\n- **瀏覽器支持**：在現代瀏覽器中廣泛支持\n\n**支持的演算法：**\n- SHA-256（推薦最低）\n- SHA-384（推薦）\n- SHA-512（最高安全性）"
  },
  "zh-HK": {
    "what-is-sri": "什麼是子資源完整性（SRI）？",
    "what-is-sri-description-markdown": "子資源完整性（SRI）是一種安全功能，使瀏覽器能夠驗證它們獲取的檔案（例如來自 CDN）沒有被意外修改。它通過將資源的加密雜湊與 HTML 中提供的雜湊進行比較來工作。\n\n**工作原理：**\n1. 生成資源檔案的加密雜湊\n2. 在 script 或 link 標籤的 integrity 屬性中包含雜湊\n3. 瀏覽器獲取資源並計算其雜湊\n4. 瀏覽器將計算的雜湊與提供的雜湊進行比較\n5. 如果雜湊匹配，資源載入；如果不匹配，載入被阻止\n\n**優勢：**\n- **安全性**：防止第三方資源被惡意修改\n- **CDN 保護**：確保 CDN 提供的檔案沒有被篡改\n- **供應鏈安全**：驗證外部依賴項的完整性\n- **瀏覽器支援**：在現代瀏覽器中廣泛支援\n\n**支援的演算法：**\n- SHA-256（推薦最低）\n- SHA-384（推薦）\n- SHA-512（最高安全性）"
  },
  "es": {
    "what-is-sri": "¿Qué es la Integridad de Subrecursos (SRI)?",
    "what-is-sri-description-markdown": "La Integridad de Subrecursos (SRI) es una característica de seguridad que permite a los navegadores verificar que los archivos que obtienen (por ejemplo, de un CDN) no han sido modificados inesperadamente. Funciona comparando el hash criptográfico de un recurso con un hash proporcionado en el HTML.\n\n**Cómo funciona:**\n1. Generar un hash criptográfico de tu archivo de recurso\n2. Incluir el hash en el atributo integrity de las etiquetas script o link\n3. El navegador obtiene el recurso y calcula su hash\n4. El navegador compara el hash calculado con el hash proporcionado\n5. Si los hashes coinciden, el recurso se carga; si no, la carga se bloquea\n\n**Beneficios:**\n- **Seguridad**: Protege contra modificaciones maliciosas de recursos de terceros\n- **Protección CDN**: Asegura que los archivos servidos por CDN no han sido alterados\n- **Seguridad de la cadena de suministro**: Valida la integridad de dependencias externas\n- **Soporte del navegador**: Ampliamente soportado en navegadores modernos\n\n**Algoritmos soportados:**\n- SHA-256 (mínimo recomendado)\n- SHA-384 (recomendado)\n- SHA-512 (máxima seguridad)"
  },
  "fr": {
    "what-is-sri": "Qu\u2019est-ce que l\u2019Intégrité des Sous-ressources (SRI) ?",
    "what-is-sri-description-markdown": "L\u2019Intégrité des Sous-ressources (SRI) est une fonctionnalité de sécurité qui permet aux navigateurs de vérifier que les fichiers qu\u2019ils récupèrent (par exemple, depuis un CDN) n\u2019ont pas été modifiés de manière inattendue. Elle fonctionne en comparant le hachage cryptographique d\u2019une ressource avec un hachage fourni dans le HTML.\n\n**Comment ça fonctionne :**\n1. Générer un hachage cryptographique de votre fichier de ressource\n2. Inclure le hachage dans l\u2019attribut integrity des balises script ou link\n3. Le navigateur récupère la ressource et calcule son hachage\n4. Le navigateur compare le hachage calculé avec le hachage fourni\n5. Si les hachages correspondent, la ressource se charge ; sinon, le chargement est bloqué\n\n**Avantages :**\n- **Sécurité** : Protège contre les modifications malveillantes des ressources tierces\n- **Protection CDN** : Assure que les fichiers servis par CDN n\u2019ont pas été altérés\n- **Sécurité de la chaîne d\u2019approvisionnement** : Valide l\u2019intégrité des dépendances externes\n- **Support navigateur** : Largement supporté par les navigateurs modernes\n\n**Algorithmes supportés :**\n- SHA-256 (minimum recommandé)\n- SHA-384 (recommandé)\n- SHA-512 (sécurité maximale)"
  },
  "de": {
    "what-is-sri": "Was ist Subresource Integrity (SRI)?",
    "what-is-sri-description-markdown": "Subresource Integrity (SRI) ist eine Sicherheitsfunktion, die es Browsern ermöglicht zu überprüfen, dass Dateien, die sie abrufen (z.B. von einem CDN), nicht unerwartet verändert wurden. Es funktioniert durch Vergleich des kryptographischen Hashes einer Ressource mit einem im HTML bereitgestellten Hash.\n\n**Wie es funktioniert:**\n1. Erstellen Sie einen kryptographischen Hash Ihrer Ressourcendatei\n2. Fügen Sie den Hash in das integrity-Attribut von script- oder link-Tags ein\n3. Browser ruft die Ressource ab und berechnet ihren Hash\n4. Browser vergleicht berechneten Hash mit bereitgestelltem Hash\n5. Wenn Hashes übereinstimmen, wird Ressource geladen; sonst wird Laden blockiert\n\n**Vorteile:**\n- **Sicherheit**: Schützt vor bösartigen Änderungen an Drittanbieter-Ressourcen\n- **CDN-Schutz**: Stellt sicher, dass CDN-bereitgestellte Dateien nicht manipuliert wurden\n- **Supply-Chain-Sicherheit**: Validiert Integrität externer Abhängigkeiten\n- **Browser-Unterstützung**: Weitgehend unterstützt in modernen Browsern\n\n**Unterstützte Algorithmen:**\n- SHA-256 (empfohlenes Minimum)\n- SHA-384 (empfohlen)\n- SHA-512 (höchste Sicherheit)"
  },
  "it": {
    "what-is-sri": "Cos\u2019è l\u2019Integrità delle Sottoriscorse (SRI)?",
    "what-is-sri-description-markdown": "L\u2019Integrità delle Sottoriscorse (SRI) è una funzionalità di sicurezza che consente ai browser di verificare che i file che recuperano (ad esempio, da un CDN) non siano stati modificati inaspettatamente. Funziona confrontando l\u2019hash crittografico di una risorsa con un hash fornito nell\u2019HTML.\n\n**Come funziona:**\n1. Generare un hash crittografico del file risorsa\n2. Includere l\u2019hash nell\u2019attributo integrity dei tag script o link\n3. Il browser recupera la risorsa e calcola il suo hash\n4. Il browser confronta l\u2019hash calcolato con l\u2019hash fornito\n5. Se gli hash corrispondono, la risorsa viene caricata; altrimenti, il caricamento viene bloccato\n\n**Vantaggi:**\n- **Sicurezza**: Protegge contro modifiche dannose delle risorse di terze parti\n- **Protezione CDN**: Assicura che i file serviti da CDN non siano stati alterati\n- **Sicurezza della catena di fornitura**: Valida l\u2019integrità delle dipendenze esterne\n- **Supporto browser**: Ampiamente supportato nei browser moderni\n\n**Algoritmi supportati:**\n- SHA-256 (minimo raccomandato)\n- SHA-384 (raccomandato)\n- SHA-512 (massima sicurezza)"
  },
  "ja": {
    "what-is-sri": "サブリソース完全性（SRI）とは？",
    "what-is-sri-description-markdown": "サブリソース完全性（SRI）は、ブラウザが取得するファイル（例：CDNから）が予期せず変更されていないことを検証できるセキュリティ機能です。リソースの暗号学的ハッシュをHTMLで提供されるハッシュと比較することで動作します。\n\n**動作原理：**\n1. リソースファイルの暗号学的ハッシュを生成\n2. scriptまたはlinkタグのintegrity属性にハッシュを含める\n3. ブラウザがリソースを取得してハッシュを計算\n4. ブラウザが計算されたハッシュと提供されたハッシュを比較\n5. ハッシュが一致すればリソースが読み込まれ、一致しなければ読み込みがブロック\n\n**利点：**\n- **セキュリティ**：サードパーティリソースの悪意ある変更から保護\n- **CDN保護**：CDNで提供されるファイルが改ざんされていないことを保証\n- **サプライチェーンセキュリティ**：外部依存関係の完全性を検証\n- **ブラウザサポート**：モダンブラウザで広くサポート\n\n**サポートされるアルゴリズム：**\n- SHA-256（推奨最低）\n- SHA-384（推奨）\n- SHA-512（最高セキュリティ）"
  },
  "ko": {
    "what-is-sri": "서브리소스 무결성(SRI)이란?",
    "what-is-sri-description-markdown": "서브리소스 무결성(SRI)은 브라우저가 가져오는 파일(예: CDN에서)이 예기치 않게 수정되지 않았는지 확인할 수 있는 보안 기능입니다. 리소스의 암호화 해시를 HTML에서 제공하는 해시와 비교하여 작동합니다.\n\n**작동 방식:**\n1. 리소스 파일의 암호화 해시 생성\n2. script 또는 link 태그의 integrity 속성에 해시 포함\n3. 브라우저가 리소스를 가져와서 해시 계산\n4. 브라우저가 계산된 해시와 제공된 해시 비교\n5. 해시가 일치하면 리소스 로드, 일치하지 않으면 로딩 차단\n\n**이점:**\n- **보안**: 서드파티 리소스의 악의적인 수정으로부터 보호\n- **CDN 보호**: CDN에서 제공하는 파일이 변조되지 않았음을 보장\n- **공급망 보안**: 외부 종속성의 무결성 검증\n- **브라우저 지원**: 모던 브라우저에서 광범위하게 지원\n\n**지원되는 알고리즘:**\n- SHA-256 (권장 최소)\n- SHA-384 (권장)\n- SHA-512 (최고 보안)"
  },
  "ru": {
    "what-is-sri": "Что такое Целостность Подресурсов (SRI)?",
    "what-is-sri-description-markdown": "Целостность Подресурсов (SRI) — это функция безопасности, которая позволяет браузерам проверять, что файлы, которые они загружают (например, с CDN), не были неожиданно изменены. Она работает путем сравнения криптографического хеша ресурса с хешем, предоставленным в HTML.\n\n**Как это работает:**\n1. Создайте криптографический хеш вашего файла ресурса\n2. Включите хеш в атрибут integrity тегов script или link\n3. Браузер загружает ресурс и вычисляет его хеш\n4. Браузер сравнивает вычисленный хеш с предоставленным хешем\n5. Если хеши совпадают, ресурс загружается; если нет, загрузка блокируется\n\n**Преимущества:**\n- **Безопасность**: Защищает от злонамеренных изменений сторонних ресурсов\n- **Защита CDN**: Обеспечивает, что файлы, предоставляемые CDN, не были изменены\n- **Безопасность цепочки поставок**: Проверяет целостность внешних зависимостей\n- **Поддержка браузеров**: Широко поддерживается современными браузерами\n\n**Поддерживаемые алгоритмы:**\n- SHA-256 (рекомендуемый минимум)\n- SHA-384 (рекомендуется)\n- SHA-512 (максимальная безопасность)"
  },
  "pt": {
    "what-is-sri": "O que é Integridade de Sub-recursos (SRI)?",
    "what-is-sri-description-markdown": "Integridade de Sub-recursos (SRI) é um recurso de segurança que permite aos navegadores verificar se os arquivos que eles buscam (por exemplo, de um CDN) não foram modificados inesperadamente. Funciona comparando o hash criptográfico de um recurso com um hash fornecido no HTML.\n\n**Como funciona:**\n1. Gerar um hash criptográfico do seu arquivo de recurso\n2. Incluir o hash no atributo integrity das tags script ou link\n3. Navegador busca o recurso e calcula seu hash\n4. Navegador compara o hash calculado com o hash fornecido\n5. Se os hashes coincidirem, o recurso carrega; se não, o carregamento é bloqueado\n\n**Benefícios:**\n- **Segurança**: Protege contra modificações maliciosas de recursos de terceiros\n- **Proteção CDN**: Garante que arquivos servidos por CDN não foram alterados\n- **Segurança da cadeia de fornecimento**: Valida a integridade de dependências externas\n- **Suporte do navegador**: Amplamente suportado em navegadores modernos\n\n**Algoritmos suportados:**\n- SHA-256 (mínimo recomendado)\n- SHA-384 (recomendado)\n- SHA-512 (máxima segurança)"
  },
  "ar": {
    "what-is-sri": "ما هي سلامة الموارد الفرعية (SRI)؟",
    "what-is-sri-description-markdown": "سلامة الموارد الفرعية (SRI) هي ميزة أمان تمكن المتصفحات من التحقق من أن الملفات التي تحصل عليها (مثل من CDN) لم يتم تعديلها بشكل غير متوقع. تعمل من خلال مقارنة التشفير المشفر للمورد مع التشفير المقدم في HTML.\n\n**كيف تعمل:**\n1. إنشاء تشفير مشفر لملف المورد الخاص بك\n2. تضمين التشفير في خاصية integrity للعلامات script أو link\n3. المتصفح يحصل على المورد ويحسب تشفيره\n4. المتصفح يقارن التشفير المحسوب مع التشفير المقدم\n5. إذا تطابقت التشفيرات، يتم تحميل المورد؛ وإلا، يتم حظر التحميل\n\n**الفوائد:**\n- **الأمان**: يحمي من التعديلات الخبيثة للموارد من طرف ثالث\n- **حماية CDN**: يضمن أن الملفات المقدمة من CDN لم يتم العبث بها\n- **أمان سلسلة التوريد**: يتحقق من سلامة التبعيات الخارجية\n- **دعم المتصفح**: مدعوم على نطاق واسع في المتصفحات الحديثة\n\n**الخوارزميات المدعومة:**\n- SHA-256 (الحد الأدنى الموصى به)\n- SHA-384 (موصى به)\n- SHA-512 (أعلى أمان)"
  },
  "hi": {
    "what-is-sri": "सबरिसोर्स इंटेग्रिटी (SRI) क्या है?",
    "what-is-sri-description-markdown": "सबरिसोर्स इंटेग्रिटी (SRI) एक सुरक्षा सुविधा है जो ब्राउज़र को यह सत्यापित करने में सक्षम बनाती है कि वे जो फ़ाइलें प्राप्त करते हैं (जैसे, CDN से) अनपेक्षित रूप से संशोधित नहीं की गई हैं। यह किसी संसाधन के क्रिप्टोग्राफिक हैश की HTML में प्रदान किए गए हैश के साथ तुलना करके काम करता है।\n\n**यह कैसे काम करता है:**\n1. अपनी संसाधन फ़ाइल का क्रिप्टोग्राफिक हैश बनाएं\n2. script या link टैग की integrity विशेषता में हैश शामिल करें\n3. ब्राउज़र संसाधन प्राप्त करता है और इसका हैश गणना करता है\n4. ब्राउज़र गणना किए गए हैश की प्रदान किए गए हैश के साथ तुलना करता है\n5. यदि हैश मेल खाते हैं, संसाधन लोड होता है; यदि नहीं, लोडिंग अवरुद्ध हो जाती है\n\n**लाभ:**\n- **सुरक्षा**: तृतीय-पक्ष संसाधनों के दुर्भावनापूर्ण संशोधनों से सुरक्षा\n- **CDN सुरक्षा**: सुनिश्चित करता है कि CDN-सेवित फ़ाइलों के साथ छेड़छाड़ नहीं हुई है\n- **आपूर्ति श्रृंखला सुरक्षा**: बाहरी निर्भरताओं की अखंडता को मान्य करता है\n- **ब्राउज़र समर्थन**: आधुनिक ब्राउज़रों में व्यापक रूप से समर्थित\n\n**समर्थित एल्गोरिदम:**\n- SHA-256 (अनुशंसित न्यूनतम)\n- SHA-384 (अनुशंसित)\n- SHA-512 (उच्चतम सुरक्षा)"
  },
  "tr": {
    "what-is-sri": "Alt Kaynak Bütünlüğü (SRI) nedir?",
    "what-is-sri-description-markdown": "Alt Kaynak Bütünlüğü (SRI), tarayıcıların aldıkları dosyaların (örneğin, bir CDN\u2019den) beklenmedik şekilde değiştirilmediğini doğrulamasını sağlayan bir güvenlik özelliğidir. Bir kaynağın kriptografik hash\u2019ini HTML\u2019de sağlanan hash ile karşılaştırarak çalışır.\n\n**Nasıl çalışır:**\n1. Kaynak dosyanızın kriptografik hash\u2019ini oluşturun\n2. Hash\u2019i script veya link etiketlerinin integrity özniteliğine ekleyin\n3. Tarayıcı kaynağı alır ve hash\u2019ini hesaplar\n4. Tarayıcı hesaplanan hash\u2019i sağlanan hash ile karşılaştırır\n5. Hash\u2019ler eşleşirse kaynak yüklenir; eşleşmezse yükleme engellenir\n\n**Faydalar:**\n- **Güvenlik**: Üçüncü taraf kaynakların kötü niyetli değişikliklerine karşı koruma\n- **CDN koruması**: CDN tarafından sunulan dosyaların kurcalanmadığını garanti eder\n- **Tedarik zinciri güvenliği**: Harici bağımlılıkların bütünlüğünü doğrular\n- **Tarayıcı desteği**: Modern tarayıcılarda yaygın olarak desteklenir\n\n**Desteklenen algoritmalar:**\n- SHA-256 (önerilen minimum)\n- SHA-384 (önerilen)\n- SHA-512 (en yüksek güvenlik)"
  },
  "nl": {
    "what-is-sri": "Wat is Subresource Integrity (SRI)?",
    "what-is-sri-description-markdown": "Subresource Integrity (SRI) is een beveiligingsfunctie die browsers in staat stelt te verifiëren dat bestanden die ze ophalen (bijv. van een CDN) niet onverwacht zijn gewijzigd. Het werkt door de cryptografische hash van een bron te vergelijken met een hash die in de HTML wordt verstrekt.\n\n**Hoe het werkt:**\n1. Genereer een cryptografische hash van uw bronbestand\n2. Voeg de hash toe aan het integrity-attribuut van script- of link-tags\n3. Browser haalt de bron op en berekent de hash\n4. Browser vergelijkt berekende hash met verstrekte hash\n5. Als hashes overeenkomen, wordt bron geladen; zo niet, wordt laden geblokkeerd\n\n**Voordelen:**\n- **Beveiliging**: Beschermt tegen kwaadwillende wijzigingen van externe bronnen\n- **CDN-bescherming**: Zorgt ervoor dat CDN-geserveerde bestanden niet zijn geknoeid\n- **Supply chain beveiliging**: Valideert integriteit van externe afhankelijkheden\n- **Browserondersteuning**: Breed ondersteund in moderne browsers\n\n**Ondersteunde algoritmen:**\n- SHA-256 (aanbevolen minimum)\n- SHA-384 (aanbevolen)\n- SHA-512 (hoogste beveiliging)"
  },
  "sv": {
    "what-is-sri": "Vad är Subresource Integrity (SRI)?",
    "what-is-sri-description-markdown": "Subresource Integrity (SRI) är en säkerhetsfunktion som gör det möjligt för webbläsare att verifiera att filer de hämtar (t.ex. från en CDN) inte har ändrats oväntat. Det fungerar genom att jämföra den kryptografiska hashen av en resurs med en hash som tillhandahålls i HTML:en.\n\n**Hur det fungerar:**\n1. Generera en kryptografisk hash av din resursfil\n2. Inkludera hashen i integrity-attributet för script- eller link-taggar\n3. Webbläsaren hämtar resursen och beräknar dess hash\n4. Webbläsaren jämför den beräknade hashen med den tillhandahållna hashen\n5. Om hasharna matchar laddas resursen; annars blockeras laddningen\n\n**Fördelar:**\n- **Säkerhet**: Skyddar mot illvilliga ändringar av tredjepartsresurser\n- **CDN-skydd**: Säkerställer att CDN-serverade filer inte har manipulerats\n- **Leveranskedjesäkerhet**: Validerar integriteten hos externa beroenden\n- **Webbläsarstöd**: Brett stöd i moderna webbläsare\n\n**Stödda algoritmer:**\n- SHA-256 (rekommenderat minimum)\n- SHA-384 (rekommenderat)\n- SHA-512 (högsta säkerhet)"
  },
  "pl": {
    "what-is-sri": "Czym jest Integralność Podzasobów (SRI)?",
    "what-is-sri-description-markdown": "Integralność Podzasobów (SRI) to funkcja bezpieczeństwa, która umożliwia przeglądarkom weryfikację, że pliki, które pobierają (np. z CDN), nie zostały nieoczekiwanie zmodyfikowane. Działa poprzez porównanie kryptograficznego skrótu zasobu ze skrótem podanym w HTML.\n\n**Jak to działa:**\n1. Wygeneruj kryptograficzny skrót pliku zasobu\n2. Dołącz skrót do atrybutu integrity tagów script lub link\n3. Przeglądarka pobiera zasób i oblicza jego skrót\n4. Przeglądarka porównuje obliczony skrót z podanym skrótem\n5. Jeśli skróty się zgadzają, zasób się ładuje; jeśli nie, ładowanie jest blokowane\n\n**Korzyści:**\n- **Bezpieczeństwo**: Chroni przed złośliwymi modyfikacjami zasobów stron trzecich\n- **Ochrona CDN**: Zapewnia, że pliki serwowane przez CDN nie zostały naruszone\n- **Bezpieczeństwo łańcucha dostaw**: Weryfikuje integralność zewnętrznych zależności\n- **Wsparcie przeglądarek**: Szeroko wspierane w nowoczesnych przeglądarkach\n\n**Obsługiwane algorytmy:**\n- SHA-256 (zalecane minimum)\n- SHA-384 (zalecane)\n- SHA-512 (najwyższe bezpieczeństwo)"
  },
  "vi": {
    "what-is-sri": "Tính Toàn Vẹn Tài Nguyên Phụ (SRI) là gì?",
    "what-is-sri-description-markdown": "Tính Toàn Vẹn Tài Nguyên Phụ (SRI) là một tính năng bảo mật cho phép trình duyệt xác minh rằng các tệp họ tải về (ví dụ: từ CDN) không bị thay đổi ngoài ý muốn. Nó hoạt động bằng cách so sánh hash mật mã của tài nguyên với hash được cung cấp trong HTML.\n\n**Cách hoạt động:**\n1. Tạo hash mật mã của tệp tài nguyên của bạn\n2. Bao gồm hash trong thuộc tính integrity của thẻ script hoặc link\n3. Trình duyệt tải tài nguyên và tính toán hash của nó\n4. Trình duyệt so sánh hash được tính toán với hash được cung cấp\n5. Nếu hash khớp, tài nguyên được tải; nếu không, việc tải bị chặn\n\n**Lợi ích:**\n- **Bảo mật**: Bảo vệ chống lại các thay đổi độc hại của tài nguyên bên thứ ba\n- **Bảo vệ CDN**: Đảm bảo các tệp được phục vụ bởi CDN không bị giả mạo\n- **Bảo mật chuỗi cung ứng**: Xác thực tính toàn vẹn của các phụ thuộc bên ngoài\n- **Hỗ trợ trình duyệt**: Được hỗ trợ rộng rãi trên các trình duyệt hiện đại\n\n**Thuật toán được hỗ trợ:**\n- SHA-256 (tối thiểu được khuyến nghị)\n- SHA-384 (được khuyến nghị)\n- SHA-512 (bảo mật cao nhất)"
  },
  "th": {
    "what-is-sri": "Subresource Integrity (SRI) คืออะไร?",
    "what-is-sri-description-markdown": "Subresource Integrity (SRI) เป็นฟีเจอร์ความปลอดภัยที่ช่วยให้เบราว์เซอร์สามารถตรวจสอบได้ว่าไฟล์ที่พวกเขาดาวน์โหลด (เช่น จาก CDN) ไม่ได้ถูกแก้ไขโดยไม่คาดคิด มันทำงานโดยการเปรียบเทียบแฮชเข้ารหัสของทรัพยากรกับแฮชที่ให้ไว้ใน HTML\n\n**วิธีการทำงาน:**\n1. สร้างแฮชเข้ารหัสของไฟล์ทรัพยากรของคุณ\n2. รวมแฮชไว้ในแอตทริบิวต์ integrity ของแท็ก script หรือ link\n3. เบราว์เซอร์ดึงทรัพยากรและคำนวณแฮชของมัน\n4. เบราว์เซอร์เปรียบเทียบแฮชที่คำนวณได้กับแฮชที่ให้ไว้\n5. หากแฮชตรงกัน ทรัพยากรจะโหลด หากไม่ การโหลดจะถูกบล็อก\n\n**ประโยชน์:**\n- **ความปลอดภัย**: ป้องกันการแก้ไขที่เป็นอันตรายของทรัพยากรบุคคลที่สาม\n- **การป้องกัน CDN**: รับประกันว่าไฟล์ที่เสิร์ฟโดย CDN ไม่ได้ถูกจัดการ\n- **ความปลอดภัยของห่วงโซ่อุปทาน**: ตรวจสอบความสมบูรณ์ของการพึ่งพาภายนอก\n- **การสนับสนุนเบราว์เซอร์**: ได้รับการสนับสนุนอย่างกว้างขวางในเบราว์เซอร์สมัยใหม่\n\n**อัลกอริทึมที่รองรับ:**\n- SHA-256 (ขั้นต่ำที่แนะนำ)\n- SHA-384 (แนะนำ)\n- SHA-512 (ความปลอดภัยสูงสุด)"
  },
  "id": {
    "what-is-sri": "Apa itu Subresource Integrity (SRI)?",
    "what-is-sri-description-markdown": "Subresource Integrity (SRI) adalah fitur keamanan yang memungkinkan browser untuk memverifikasi bahwa file yang mereka ambil (misalnya, dari CDN) tidak dimodifikasi secara tidak terduga. Ini bekerja dengan membandingkan hash kriptografi dari sumber daya dengan hash yang disediakan dalam HTML.\n\n**Cara kerjanya:**\n1. Buat hash kriptografi dari file sumber daya Anda\n2. Sertakan hash dalam atribut integrity dari tag script atau link\n3. Browser mengambil sumber daya dan menghitung hashnya\n4. Browser membandingkan hash yang dihitung dengan hash yang disediakan\n5. Jika hash cocok, sumber daya dimuat; jika tidak, pemuatan diblokir\n\n**Manfaat:**\n- **Keamanan**: Melindungi terhadap modifikasi berbahaya dari sumber daya pihak ketiga\n- **Perlindungan CDN**: Memastikan file yang disajikan CDN tidak diutak-atik\n- **Keamanan rantai pasokan**: Memvalidasi integritas dependensi eksternal\n- **Dukungan browser**: Didukung secara luas di browser modern\n\n**Algoritma yang didukung:**\n- SHA-256 (minimum yang direkomendasikan)\n- SHA-384 (direkomendasikan)\n- SHA-512 (keamanan tertinggi)"
  },
  "he": {
    "what-is-sri": "מה זה שלמות משאבי משנה (SRI)?",
    "what-is-sri-description-markdown": "שלמות משאבי משנה (SRI) הוא תכונת אבטחה המאפשרת לדפדפנים לאמת שקבצים שהם מביאים (למשל, מ-CDN) לא שונו באופן בלתי צפוי. זה עובד על ידי השוואת ההאש הקריפטוגרפי של משאב עם האש שסופק ב-HTML.\n\n**איך זה עובד:**\n1. יצירת האש קריפטוגרפי של קובץ המשאב שלך\n2. כללת ההאש בתכונת integrity של תגי script או link\n3. הדפדפן מביא את המשאב ומחשב את ההאש שלו\n4. הדפדפן משווה את ההאש המחושב עם ההאש שסופק\n5. אם ההאשים תואמים, המשאב נטען; אם לא, הטעינה חסומה\n\n**יתרונות:**\n- **אבטחה**: מגן מפני שינויים זדוניים של משאבי צד שלישי\n- **הגנת CDN**: מבטיח שקבצים המוגשים על ידי CDN לא נפגעו\n- **אבטחת שרשרת אספקה**: מאמת שלמות של תלויות חיצוניות\n- **תמיכת דפדפן**: נתמך באופן נרחב בדפדפנים מודרניים\n\n**אלגוריתמים נתמכים:**\n- SHA-256 (מינימום מומלץ)\n- SHA-384 (מומלץ)\n- SHA-512 (אבטחה גבוהה ביותר)"
  },
  "ms": {
    "what-is-sri": "Apakah Subresource Integrity (SRI)?",
    "what-is-sri-description-markdown": "Subresource Integrity (SRI) adalah ciri keselamatan yang membolehkan pelayar untuk mengesahkan bahawa fail yang mereka ambil (contohnya, dari CDN) tidak diubah suai secara tidak dijangka. Ia berfungsi dengan membandingkan hash kriptografi sumber dengan hash yang disediakan dalam HTML.\n\n**Bagaimana ia berfungsi:**\n1. Jana hash kriptografi fail sumber anda\n2. Sertakan hash dalam atribut integrity tag script atau link\n3. Pelayar mengambil sumber dan mengira hashnya\n4. Pelayar membandingkan hash yang dikira dengan hash yang disediakan\n5. Jika hash sepadan, sumber dimuatkan; jika tidak, pemuatan disekat\n\n**Faedah:**\n- **Keselamatan**: Melindungi daripada pengubahsuaian berniat jahat sumber pihak ketiga\n- **Perlindungan CDN**: Memastikan fail yang dihidang CDN tidak diganggu\n- **Keselamatan rantaian bekalan**: Mengesahkan integriti kebergantungan luaran\n- **Sokongan pelayar**: Disokong secara meluas dalam pelayar moden\n\n**Algoritma yang disokong:**\n- SHA-256 (minimum yang disyorkan)\n- SHA-384 (disyorkan)\n- SHA-512 (keselamatan tertinggi)"
  },
  "no": {
    "what-is-sri": "Hva er Subresource Integrity (SRI)?",
    "what-is-sri-description-markdown": "Subresource Integrity (SRI) er en sikkerhetsfunksjon som gjør det mulig for nettlesere å verifisere at filer de henter (f.eks. fra en CDN) ikke har blitt uventet endret. Det fungerer ved å sammenligne den kryptografiske hashen til en ressurs med en hash som er oppgitt i HTML-en.\n\n**Hvordan det fungerer:**\n1. Generer en kryptografisk hash av ressursfilen din\n2. Inkluder hashen i integrity-attributtet til script- eller link-tagger\n3. Nettleseren henter ressursen og beregner dens hash\n4. Nettleseren sammenligner den beregnede hashen med den oppgitte hashen\n5. Hvis hashene stemmer overens, lastes ressursen; hvis ikke, blokkeres lastingen\n\n**Fordeler:**\n- **Sikkerhet**: Beskytter mot ondsinnet endring av tredjepartsressurser\n- **CDN-beskyttelse**: Sikrer at CDN-serverte filer ikke har blitt manipulert\n- **Leverandørkjedesikkerhet**: Validerer integriteten til eksterne avhengigheter\n- **Nettleserstøtte**: Bredt støttet i moderne nettlesere\n\n**Støttede algoritmer:**\n- SHA-256 (anbefalt minimum)\n- SHA-384 (anbefalt)\n- SHA-512 (høyeste sikkerhet)"
  }
}
</i18n>
