<template>
  <DescriptionMarkdown
    :title="t('what-is-sha1')"
    :description="t('what-is-sha1-description-markdown')"
  />
</template>

<script setup lang="ts">
import { DescriptionMarkdown } from '@shared/ui/base'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()
</script>

<i18n lang="json">
{
  "en": {
    "what-is-sha1": "What is SHA-1?",
    "what-is-sha1-description-markdown": "SHA-1 (Secure Hash Algorithm 1) is a cryptographic hash function that produces a 160-bit (20-byte) hash value, typically rendered as a 40-character hexadecimal number. It was designed by the NSA and published by NIST in 1995 as part of the Digital Signature Standard.\n\n**Key characteristics:**\n- **Deterministic**: The same input always produces the same hash\n- **Fast computation**: Quick to compute for any given input\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Irreversible**: Computationally infeasible to reverse the hash to find the original input\n- **Collision vulnerable**: Known vulnerabilities make it possible to find collisions\n\n**Security status:**\n⚠️ **SHA-1 is cryptographically broken and should not be used for security-critical applications**. Theoretical attacks were demonstrated in 2005, and practical collision attacks were achieved in 2017.\n\n**Common uses (historical):**\n- Digital signatures and certificates (deprecated)\n- Git version control system (for compatibility)\n- Legacy systems requiring SHA-1\n- File integrity verification (non-security critical)\n- Proof of work algorithms (some older cryptocurrencies)\n\n**Recommended alternatives:**\n- SHA-256 or SHA-3 for new applications\n- SHA-512 for high-security requirements"
  },
  "zh": {
    "what-is-sha1": "什么是 SHA-1？",
    "what-is-sha1-description-markdown": "SHA-1（安全散列算法 1）是一种加密散列函数，产生 160 位（20 字节）的散列值，通常呈现为 40 个字符的十六进制数。它由 NSA 设计并于 1995 年由 NIST 作为数字签名标准的一部分发布。\n\n**主要特征：**\n- **确定性**：相同的输入总是产生相同的散列\n- **快速计算**：对于任何给定输入都能快速计算\n- **雪崩效应**：输入的微小变化会产生截然不同的输出\n- **不可逆**：从散列反推原始输入在计算上是不可行的\n- **碰撞脆弱性**：已知漏洞使得找到碰撞成为可能\n\n**安全状态：**\n⚠️ **SHA-1 在密码学上已被破解，不应用于安全关键应用**。理论攻击在 2005 年得到证明，实际碰撞攻击在 2017 年实现。\n\n**常见用途（历史）：**\n- 数字签名和证书（已弃用）\n- Git 版本控制系统（为了兼容性）\n- 需要 SHA-1 的遗留系统\n- 文件完整性验证（非安全关键）\n- 工作量证明算法（一些较老的加密货币）\n\n**推荐替代方案：**\n- 新应用使用 SHA-256 或 SHA-3\n- 高安全要求使用 SHA-512"
  },
  "zh-CN": {
    "what-is-sha1": "什么是 SHA-1？",
    "what-is-sha1-description-markdown": "SHA-1（安全散列算法 1）是一种加密散列函数，产生 160 位（20 字节）的散列值，通常呈现为 40 个字符的十六进制数。它由 NSA 设计并于 1995 年由 NIST 作为数字签名标准的一部分发布。\n\n**主要特征：**\n- **确定性**：相同的输入总是产生相同的散列\n- **快速计算**：对于任何给定输入都能快速计算\n- **雪崩效应**：输入的微小变化会产生截然不同的输出\n- **不可逆**：从散列反推原始输入在计算上是不可行的\n- **碰撞脆弱性**：已知漏洞使得找到碰撞成为可能\n\n**安全状态：**\n⚠️ **SHA-1 在密码学上已被破解，不应用于安全关键应用**。理论攻击在 2005 年得到证明，实际碰撞攻击在 2017 年实现。\n\n**常见用途（历史）：**\n- 数字签名和证书（已弃用）\n- Git 版本控制系统（为了兼容性）\n- 需要 SHA-1 的遗留系统\n- 文件完整性验证（非安全关键）\n- 工作量证明算法（一些较老的加密货币）\n\n**推荐替代方案：**\n- 新应用使用 SHA-256 或 SHA-3\n- 高安全要求使用 SHA-512"
  },
  "zh-TW": {
    "what-is-sha1": "什麼是 SHA-1？",
    "what-is-sha1-description-markdown": "SHA-1（安全雜湊演算法 1）是一種加密雜湊函數，產生 160 位元（20 位元組）的雜湊值，通常呈現為 40 個字元的十六進位數。它由 NSA 設計並於 1995 年由 NIST 作為數位簽章標準的一部分發布。\n\n**主要特徵：**\n- **確定性**：相同的輸入總是產生相同的雜湊\n- **快速計算**：對於任何給定輸入都能快速計算\n- **雪崩效應**：輸入的微小變化會產生截然不同的輸出\n- **不可逆**：從雜湊反推原始輸入在計算上是不可行的\n- **碰撞脆弱性**：已知漏洞使得找到碰撞成為可能\n\n**安全狀態：**\n⚠️ **SHA-1 在密碼學上已被破解，不應用於安全關鍵應用**。理論攻擊在 2005 年得到證明，實際碰撞攻擊在 2017 年實現。\n\n**常見用途（歷史）：**\n- 數位簽章和憑證（已棄用）\n- Git 版本控制系統（為了相容性）\n- 需要 SHA-1 的遺留系統\n- 檔案完整性驗證（非安全關鍵）\n- 工作量證明演算法（一些較老的加密貨幣）\n\n**推薦替代方案：**\n- 新應用使用 SHA-256 或 SHA-3\n- 高安全要求使用 SHA-512"
  },
  "zh-HK": {
    "what-is-sha1": "什麼是 SHA-1？",
    "what-is-sha1-description-markdown": "SHA-1（安全雜湊演算法 1）是一種加密雜湊函數，產生 160 位元（20 位元組）的雜湊值，通常呈現為 40 個字元的十六進位數。它由 NSA 設計並於 1995 年由 NIST 作為數碼簽署標準的一部分發布。\n\n**主要特徵：**\n- **確定性**：相同的輸入總是產生相同的雜湊\n- **快速計算**：對於任何給定輸入都能快速計算\n- **雪崩效應**：輸入的微小變化會產生截然不同的輸出\n- **不可逆**：從雜湊反推原始輸入在計算上是不可行的\n- **碰撞脆弱性**：已知漏洞使得找到碰撞成為可能\n\n**安全狀態：**\n⚠️ **SHA-1 在密碼學上已被破解，不應用於安全關鍵應用**。理論攻擊在 2005 年得到證明，實際碰撞攻擊在 2017 年實現。\n\n**常見用途（歷史）：**\n- 數碼簽署和證書（已棄用）\n- Git 版本控制系統（為了相容性）\n- 需要 SHA-1 的遺留系統\n- 檔案完整性驗證（非安全關鍵）\n- 工作量證明演算法（一些較老的加密貨幣）\n\n**推薦替代方案：**\n- 新應用使用 SHA-256 或 SHA-3\n- 高安全要求使用 SHA-512"
  },
  "es": {
    "what-is-sha1": "¿Qué es SHA-1?",
    "what-is-sha1-description-markdown": "SHA-1 (Algoritmo de Hash Seguro 1) es una función hash criptográfica que produce un valor hash de 160 bits (20 bytes), típicamente representado como un número hexadecimal de 40 caracteres. Fue diseñado por la NSA y publicado por NIST en 1995 como parte del Estándar de Firma Digital.\n\n**Características clave:**\n- **Determinístico**: La misma entrada siempre produce el mismo hash\n- **Computación rápida**: Rápido de calcular para cualquier entrada dada\n- **Efecto avalancha**: Pequeños cambios en la entrada producen salidas drásticamente diferentes\n- **Irreversible**: Es computacionalmente inviable revertir el hash para encontrar la entrada original\n- **Vulnerable a colisiones**: Las vulnerabilidades conocidas hacen posible encontrar colisiones\n\n**Estado de seguridad:**\n⚠️ **SHA-1 está criptográficamente roto y no debe usarse para aplicaciones críticas de seguridad**. Los ataques teóricos se demostraron en 2005, y los ataques prácticos de colisión se lograron en 2017.\n\n**Usos comunes (históricos):**\n- Firmas digitales y certificados (obsoleto)\n- Sistema de control de versiones Git (por compatibilidad)\n- Sistemas heredados que requieren SHA-1\n- Verificación de integridad de archivos (no crítico para seguridad)\n- Algoritmos de prueba de trabajo (algunas criptomonedas más antiguas)\n\n**Alternativas recomendadas:**\n- SHA-256 o SHA-3 para nuevas aplicaciones\n- SHA-512 para requisitos de alta seguridad"
  },
  "fr": {
    "what-is-sha1": "Qu'est-ce que SHA-1 ?",
    "what-is-sha1-description-markdown": "SHA-1 (Algorithme de Hachage Sécurisé 1) est une fonction de hachage cryptographique qui produit une valeur de hachage de 160 bits (20 octets), généralement rendue sous forme d'un nombre hexadécimal de 40 caractères. Il a été conçu par la NSA et publié par le NIST en 1995 dans le cadre du Standard de Signature Numérique.\n\n**Caractéristiques clés :**\n- **Déterministe** : La même entrée produit toujours le même hachage\n- **Calcul rapide** : Rapide à calculer pour toute entrée donnée\n- **Effet d'avalanche** : De petits changements dans l'entrée produisent des sorties drastiquement différentes\n- **Irréversible** : Il est informatiquement impossible d'inverser le hachage pour trouver l'entrée originale\n- **Vulnérable aux collisions** : Les vulnérabilités connues rendent possible la recherche de collisions\n\n**État de sécurité :**\n⚠️ **SHA-1 est cryptographiquement cassé et ne devrait pas être utilisé pour des applications critiques de sécurité**. Les attaques théoriques ont été démontrées en 2005, et les attaques pratiques de collision ont été réalisées en 2017.\n\n**Utilisations courantes (historiques) :**\n- Signatures numériques et certificats (obsolète)\n- Système de contrôle de version Git (pour compatibilité)\n- Systèmes hérités nécessitant SHA-1\n- Vérification d'intégrité de fichiers (non critique pour la sécurité)\n- Algorithmes de preuve de travail (certaines cryptomonnaies plus anciennes)\n\n**Alternatives recommandées :**\n- SHA-256 ou SHA-3 pour les nouvelles applications\n- SHA-512 pour les exigences de haute sécurité"
  },
  "de": {
    "what-is-sha1": "Was ist SHA-1?",
    "what-is-sha1-description-markdown": "SHA-1 (Secure Hash Algorithm 1) ist eine kryptographische Hash-Funktion, die einen 160-Bit (20-Byte) Hash-Wert erzeugt, der typischerweise als 40-stellige Hexadezimalzahl dargestellt wird. Es wurde von der NSA entworfen und 1995 vom NIST als Teil des Digital Signature Standards veröffentlicht.\n\n**Hauptmerkmale:**\n- **Deterministisch**: Dieselbe Eingabe erzeugt immer denselben Hash\n- **Schnelle Berechnung**: Schnell zu berechnen für jede gegebene Eingabe\n- **Lawineneffekt**: Kleine Änderungen in der Eingabe erzeugen drastisch unterschiedliche Ausgaben\n- **Irreversibel**: Rechnerisch nicht machbar, den Hash umzukehren, um die ursprüngliche Eingabe zu finden\n- **Kollisionsvulnerabel**: Bekannte Schwachstellen machen es möglich, Kollisionen zu finden\n\n**Sicherheitsstatus:**\n⚠️ **SHA-1 ist kryptographisch gebrochen und sollte nicht für sicherheitskritische Anwendungen verwendet werden**. Theoretische Angriffe wurden 2005 demonstriert, und praktische Kollisionsangriffe wurden 2017 erreicht.\n\n**Häufige Verwendungen (historisch):**\n- Digitale Signaturen und Zertifikate (veraltet)\n- Git-Versionskontrollsystem (aus Kompatibilitätsgründen)\n- Legacy-Systeme, die SHA-1 erfordern\n- Datei-Integritätsprüfung (nicht sicherheitskritisch)\n- Proof-of-Work-Algorithmen (einige ältere Kryptowährungen)\n\n**Empfohlene Alternativen:**\n- SHA-256 oder SHA-3 für neue Anwendungen\n- SHA-512 für hohe Sicherheitsanforderungen"
  },
  "it": {
    "what-is-sha1": "Cos'è SHA-1?",
    "what-is-sha1-description-markdown": "SHA-1 (Secure Hash Algorithm 1) è una funzione hash crittografica che produce un valore hash di 160 bit (20 byte), tipicamente rappresentato come un numero esadecimale di 40 caratteri. È stato progettato dalla NSA e pubblicato dal NIST nel 1995 come parte del Digital Signature Standard.\n\n**Caratteristiche chiave:**\n- **Deterministico**: Lo stesso input produce sempre lo stesso hash\n- **Calcolo veloce**: Veloce da calcolare per qualsiasi input dato\n- **Effetto valanga**: Piccoli cambiamenti nell'input producono output drasticamente diversi\n- **Irreversibile**: Computazionalmente impossibile invertire l'hash per trovare l'input originale\n- **Vulnerabile alle collisioni**: Le vulnerabilità note rendono possibile trovare collisioni\n\n**Stato di sicurezza:**\n⚠️ **SHA-1 è crittograficamente compromesso e non dovrebbe essere usato per applicazioni critiche per la sicurezza**. Gli attacchi teorici sono stati dimostrati nel 2005, e gli attacchi pratici di collisione sono stati raggiunti nel 2017.\n\n**Usi comuni (storici):**\n- Firme digitali e certificati (deprecato)\n- Sistema di controllo versione Git (per compatibilità)\n- Sistemi legacy che richiedono SHA-1\n- Verifica dell'integrità dei file (non critica per la sicurezza)\n- Algoritmi proof-of-work (alcune criptovalute più vecchie)\n\n**Alternative raccomandate:**\n- SHA-256 o SHA-3 per nuove applicazioni\n- SHA-512 per requisiti di alta sicurezza"
  },
  "ja": {
    "what-is-sha1": "SHA-1とは？",
    "what-is-sha1-description-markdown": "SHA-1（Secure Hash Algorithm 1）は、160ビット（20バイト）のハッシュ値を生成する暗号学的ハッシュ関数で、通常40文字の16進数として表示されます。NSAによって設計され、1995年にデジタル署名標準の一部としてNISTによって公開されました。\n\n**主な特徴：**\n- **決定論的**：同じ入力は常に同じハッシュを生成\n- **高速計算**：任意の入力に対して高速に計算\n- **雪崩効果**：入力の小さな変化が劇的に異なる出力を生成\n- **不可逆**：ハッシュを逆算して元の入力を見つけることは計算上不可能\n- **衝突脆弱性**：既知の脆弱性により衝突を見つけることが可能\n\n**セキュリティ状況：**\n⚠️ **SHA-1は暗号学的に破られており、セキュリティが重要なアプリケーションでは使用すべきではありません**。理論的攻撃は2005年に実証され、実用的な衝突攻撃は2017年に達成されました。\n\n**一般的な用途（歴史的）：**\n- デジタル署名と証明書（非推奨）\n- Gitバージョン管理システム（互換性のため）\n- SHA-1を必要とするレガシーシステム\n- ファイル整合性検証（セキュリティ非重要）\n- プルーフオブワークアルゴリズム（一部の古い暗号通貨）\n\n**推奨される代替案：**\n- 新しいアプリケーションにはSHA-256またはSHA-3\n- 高セキュリティ要件にはSHA-512"
  },
  "ko": {
    "what-is-sha1": "SHA-1이란?",
    "what-is-sha1-description-markdown": "SHA-1(Secure Hash Algorithm 1)은 160비트(20바이트) 해시 값을 생성하는 암호화 해시 함수로, 일반적으로 40자리 16진수로 표현됩니다. NSA에서 설계하고 1995년 디지털 서명 표준의 일부로 NIST에서 발표했습니다.\n\n**주요 특징:**\n- **결정론적**: 동일한 입력은 항상 동일한 해시를 생성\n- **빠른 계산**: 주어진 입력에 대해 빠르게 계산\n- **눈사태 효과**: 입력의 작은 변화가 완전히 다른 출력을 생성\n- **비가역적**: 해시를 역산하여 원본 입력을 찾는 것은 계산적으로 불가능\n- **충돌 취약성**: 알려진 취약점으로 인해 충돌을 찾는 것이 가능\n\n**보안 상태:**\n⚠️ **SHA-1은 암호학적으로 깨졌으며 보안이 중요한 애플리케이션에서는 사용해서는 안 됩니다**. 이론적 공격은 2005년에 증명되었고, 실용적인 충돌 공격은 2017년에 달성되었습니다.\n\n**일반적인 용도(역사적):**\n- 디지털 서명 및 인증서(더 이상 사용되지 않음)\n- Git 버전 제어 시스템(호환성을 위해)\n- SHA-1이 필요한 레거시 시스템\n- 파일 무결성 검증(보안 비중요)\n- 작업 증명 알고리즘(일부 오래된 암호화폐)\n\n**권장 대안:**\n- 새로운 애플리케이션에는 SHA-256 또는 SHA-3\n- 높은 보안 요구사항에는 SHA-512"
  },
  "ru": {
    "what-is-sha1": "Что такое SHA-1?",
    "what-is-sha1-description-markdown": "SHA-1 (Secure Hash Algorithm 1) — это криптографическая хеш-функция, которая производит 160-битное (20-байтовое) хеш-значение, обычно представляемое как 40-символьное шестнадцатеричное число. Он был разработан АНБ и опубликован NIST в 1995 году как часть стандарта цифровой подписи.\n\n**Ключевые характеристики:**\n- **Детерминированность**: Одинаковый ввод всегда производит одинаковый хеш\n- **Быстрое вычисление**: Быстро вычисляется для любого заданного ввода\n- **Эффект лавины**: Небольшие изменения во вводе производят кардинально разные выводы\n- **Необратимость**: Вычислительно невозможно обратить хеш для поиска исходного ввода\n- **Уязвимость к коллизиям**: Известные уязвимости делают возможным поиск коллизий\n\n**Статус безопасности:**\n⚠️ **SHA-1 криптографически сломан и не должен использоваться для критически важных для безопасности приложений**. Теоретические атаки были продемонстрированы в 2005 году, а практические атаки коллизий были достигнуты в 2017 году.\n\n**Обычные применения (исторические):**\n- Цифровые подписи и сертификаты (устаревшие)\n- Система контроля версий Git (для совместимости)\n- Устаревшие системы, требующие SHA-1\n- Проверка целостности файлов (не критично для безопасности)\n- Алгоритмы доказательства работы (некоторые старые криптовалюты)\n\n**Рекомендуемые альтернативы:**\n- SHA-256 или SHA-3 для новых приложений\n- SHA-512 для высоких требований безопасности"
  },
  "pt": {
    "what-is-sha1": "O que é SHA-1?",
    "what-is-sha1-description-markdown": "SHA-1 (Secure Hash Algorithm 1) é uma função hash criptográfica que produz um valor hash de 160 bits (20 bytes), tipicamente renderizado como um número hexadecimal de 40 caracteres. Foi projetado pela NSA e publicado pelo NIST em 1995 como parte do Padrão de Assinatura Digital.\n\n**Características principais:**\n- **Determinístico**: A mesma entrada sempre produz o mesmo hash\n- **Computação rápida**: Rápido de calcular para qualquer entrada dada\n- **Efeito avalanche**: Pequenas mudanças na entrada produzem saídas drasticamente diferentes\n- **Irreversível**: Computacionalmente inviável reverter o hash para encontrar a entrada original\n- **Vulnerável a colisões**: Vulnerabilidades conhecidas tornam possível encontrar colisões\n\n**Status de segurança:**\n⚠️ **SHA-1 está criptograficamente quebrado e não deve ser usado para aplicações críticas de segurança**. Ataques teóricos foram demonstrados em 2005, e ataques práticos de colisão foram alcançados em 2017.\n\n**Usos comuns (históricos):**\n- Assinaturas digitais e certificados (obsoleto)\n- Sistema de controle de versão Git (para compatibilidade)\n- Sistemas legados que requerem SHA-1\n- Verificação de integridade de arquivos (não crítico para segurança)\n- Algoritmos de prova de trabalho (algumas criptomoedas mais antigas)\n\n**Alternativas recomendadas:**\n- SHA-256 ou SHA-3 para novas aplicações\n- SHA-512 para requisitos de alta segurança"
  },
  "ar": {
    "what-is-sha1": "ما هو SHA-1؟",
    "what-is-sha1-description-markdown": "SHA-1 (خوارزمية التشفير الآمنة 1) هي دالة تشفير تنتج قيمة تشفير بحجم 160 بت (20 بايت)، وتُعرض عادة كرقم سادس عشر مكون من 40 حرفاً. صممتها وكالة الأمن القومي ونشرها المعهد الوطني للمعايير والتكنولوجيا في 1995 كجزء من معيار التوقيع الرقمي.\n\n**الخصائص الرئيسية:**\n- **حتمية**: نفس المدخل ينتج دائماً نفس التشفير\n- **حوسبة سريعة**: سريعة الحساب لأي مدخل معطى\n- **تأثير الانهيار الجليدي**: تغييرات صغيرة في المدخل تنتج مخرجات مختلفة تماماً\n- **غير قابلة للعكس**: من المستحيل حاسوبياً عكس التشفير لإيجاد المدخل الأصلي\n- **عرضة للتصادمات**: نقاط الضعف المعروفة تجعل إيجاد التصادمات ممكناً\n\n**حالة الأمان:**\n⚠️ **SHA-1 مكسور تشفيرياً ولا يجب استخدامه للتطبيقات الحرجة أمنياً**. الهجمات النظرية تم إثباتها في 2005، والهجمات العملية للتصادمات تم تحقيقها في 2017.\n\n**الاستخدامات الشائعة (تاريخية):**\n- التوقيعات الرقمية والشهادات (مهجور)\n- نظام التحكم في الإصدارات Git (للتوافق)\n- الأنظمة القديمة التي تتطلب SHA-1\n- التحقق من سلامة الملفات (غير حرج أمنياً)\n- خوارزميات إثبات العمل (بعض العملات المشفرة الأقدم)\n\n**البدائل الموصى بها:**\n- SHA-256 أو SHA-3 للتطبيقات الجديدة\n- SHA-512 لمتطلبات الأمان العالية"
  },
  "hi": {
    "what-is-sha1": "SHA-1 क्या है?",
    "what-is-sha1-description-markdown": "SHA-1 (Secure Hash Algorithm 1) एक क्रिप्टोग्राफिक हैश फ़ंक्शन है जो 160-बिट (20-बाइट) हैश वैल्यू उत्पन्न करता है, जो आमतौर पर 40-वर्ण हेक्साडेसिमल संख्या के रूप में प्रस्तुत होता है। इसे NSA द्वारा डिज़ाइन किया गया था और 1995 में डिजिटल सिग्नेचर स्टैंडर्ड के भाग के रूप में NIST द्वारा प्रकाशित किया गया था।\n\n**मुख्य विशेषताएं:**\n- **निर्धारक**: समान इनपुट हमेशा समान हैश उत्पन्न करता है\n- **तेज़ गणना**: किसी भी दिए गए इनपुट के लिए तेज़ी से गणना\n- **हिमस्खलन प्रभाव**: इनपुट में छोटे बदलाव बेहद अलग आउटपुट उत्पन्न करते हैं\n- **अपरिवर्तनीय**: मूल इनपुट खोजने के लिए हैश को उलटना कम्प्यूटेशनल रूप से असंभव\n- **टक्कर संवेदनशील**: ज्ञात कमजोरियां टकराव खोजना संभव बनाती हैं\n\n**सुरक्षा स्थिति:**\n⚠️ **SHA-1 क्रिप्टोग्राफिक रूप से टूटा हुआ है और सुरक्षा-महत्वपूर्ण अनुप्रयोगों के लिए उपयोग नहीं किया जाना चाहिए**। सैद्धांतिक हमले 2005 में प्रदर्शित किए गए थे, और व्यावहारिक टकराव हमले 2017 में हासिल किए गए थे।\n\n**सामान्य उपयोग (ऐतिहासिक):**\n- डिजिटल हस्ताक्षर और प्रमाणपत्र (बहिष्कृत)\n- Git वर्जन कंट्रोल सिस्टम (संगतता के लिए)\n- लीगेसी सिस्टम जिन्हें SHA-1 की आवश्यकता है\n- फ़ाइल अखंडता सत्यापन (सुरक्षा गैर-महत्वपूर्ण)\n- कार्य प्रमाण एल्गोरिदम (कुछ पुराने क्रिप्टोकरेंसी)\n\n**अनुशंसित विकल्प:**\n- नए अनुप्रयोगों के लिए SHA-256 या SHA-3\n- उच्च सुरक्षा आवश्यकताओं के लिए SHA-512"
  },
  "tr": {
    "what-is-sha1": "SHA-1 nedir?",
    "what-is-sha1-description-markdown": "SHA-1 (Güvenli Hash Algoritması 1), tipik olarak 40 karakterlik onaltılık sayı olarak gösterilen 160-bit (20-bayt) hash değeri üreten kriptografik bir hash fonksiyonudur. NSA tarafından tasarlanmış ve 1995 yılında Dijital İmza Standardının bir parçası olarak NIST tarafından yayınlanmıştır.\n\n**Temel özellikler:**\n- **Deterministik**: Aynı girdi her zaman aynı hash'i üretir\n- **Hızlı hesaplama**: Herhangi bir verilen girdi için hızla hesaplanır\n- **Çığ etkisi**: Girdideki küçük değişiklikler büyük ölçüde farklı çıktılar üretir\n- **Geri döndürülemez**: Hash'i tersine çevirerek orijinal girdiyi bulmak hesaplamalı olarak mümkün değildir\n- **Çarpışma açığı**: Bilinen güvenlik açıkları çarpışma bulmayı mümkün kılar\n\n**Güvenlik durumu:**\n⚠️ **SHA-1 kriptografik olarak kırılmıştır ve güvenlik açısından kritik uygulamalar için kullanılmamalıdır**. Teorik saldırılar 2005 yılında gösterilmiş, pratik çarpışma saldırıları 2017 yılında başarılmıştır.\n\n**Yaygın kullanımlar (tarihsel):**\n- Dijital imzalar ve sertifikalar (kullanımdan kaldırıldı)\n- Git versiyon kontrol sistemi (uyumluluk için)\n- SHA-1 gerektiren eski sistemler\n- Dosya bütünlüğü doğrulama (güvenlik açısından kritik değil)\n- İş kanıtı algoritmaları (bazı eski kripto para birimleri)\n\n**Önerilen alternatifler:**\n- Yeni uygulamalar için SHA-256 veya SHA-3\n- Yüksek güvenlik gereksinimleri için SHA-512"
  },
  "nl": {
    "what-is-sha1": "Wat is SHA-1?",
    "what-is-sha1-description-markdown": "SHA-1 (Secure Hash Algorithm 1) is een cryptografische hashfunctie die een 160-bit (20-byte) hashwaarde produceert, doorgaans weergegeven als een 40-karakter hexadecimaal getal. Het is ontworpen door de NSA en gepubliceerd door NIST in 1995 als onderdeel van de Digital Signature Standard.\n\n**Belangrijkste kenmerken:**\n- **Deterministisch**: Dezelfde invoer produceert altijd dezelfde hash\n- **Snelle berekening**: Snel te berekenen voor elke gegeven invoer\n- **Lawine-effect**: Kleine veranderingen in invoer produceren drastisch verschillende uitvoer\n- **Onomkeerbaar**: Computationeel onhaalbaar om de hash om te keren om de oorspronkelijke invoer te vinden\n- **Botsingsgevoelig**: Bekende kwetsbaarheden maken het mogelijk om botsingen te vinden\n\n**Beveiligingsstatus:**\n⚠️ **SHA-1 is cryptografisch gebroken en mag niet worden gebruikt voor beveiligingskritische toepassingen**. Theoretische aanvallen werden gedemonstreerd in 2005, en praktische botsingsaanvallen werden bereikt in 2017.\n\n**Veelvoorkomende toepassingen (historisch):**\n- Digitale handtekeningen en certificaten (verouderd)\n- Git versiebeheersysteem (voor compatibiliteit)\n- Legacy systemen die SHA-1 vereisen\n- Bestandsintegriteitsverificatie (niet beveiligingskritisch)\n- Proof-of-work algoritmes (sommige oudere cryptocurrencies)\n\n**Aanbevolen alternatieven:**\n- SHA-256 of SHA-3 voor nieuwe toepassingen\n- SHA-512 voor hoge beveiligingseisen"
  },
  "sv": {
    "what-is-sha1": "Vad är SHA-1?",
    "what-is-sha1-description-markdown": "SHA-1 (Secure Hash Algorithm 1) är en kryptografisk hash-funktion som producerar ett 160-bitars (20-byte) hash-värde, vanligtvis återgivet som ett 40-tecken heksadecimalt tal. Det designades av NSA och publicerades av NIST 1995 som en del av Digital Signature Standard.\n\n**Nyckelegenskaper:**\n- **Deterministisk**: Samma inmatning producerar alltid samma hash\n- **Snabb beräkning**: Snabb att beräkna för vilken given inmatning som helst\n- **Lavineffekt**: Små förändringar i inmatningen producerar drastiskt olika utmatningar\n- **Irreversibel**: Beräkningsmässigt omöjligt att vända hashen för att hitta den ursprungliga inmatningen\n- **Kollisionssårbar**: Kända sårbarheter gör det möjligt att hitta kollisioner\n\n**Säkerhetsstatus:**\n⚠️ **SHA-1 är kryptografiskt brutet och bör inte användas för säkerhetskritiska applikationer**. Teoretiska attacker demonstrerades 2005, och praktiska kollisionsattacker uppnåddes 2017.\n\n**Vanliga användningar (historiska):**\n- Digitala signaturer och certifikat (föråldrat)\n- Git versionskontrollsystem (för kompatibilitet)\n- Äldre system som kräver SHA-1\n- Filintegritetsverifiering (inte säkerhetskritiskt)\n- Proof-of-work algoritmer (vissa äldre kryptovalutor)\n\n**Rekommenderade alternativ:**\n- SHA-256 eller SHA-3 för nya applikationer\n- SHA-512 för höga säkerhetskrav"
  },
  "pl": {
    "what-is-sha1": "Czym jest SHA-1?",
    "what-is-sha1-description-markdown": "SHA-1 (Secure Hash Algorithm 1) to kryptograficzna funkcja skrótu, która produkuje 160-bitową (20-bajtową) wartość skrótu, zazwyczaj przedstawianą jako 40-znakową liczbę szesnastkową. Została zaprojektowana przez NSA i opublikowana przez NIST w 1995 roku jako część Digital Signature Standard.\n\n**Kluczowe cechy:**\n- **Deterministyczna**: To samo wejście zawsze produkuje ten sam skrót\n- **Szybkie obliczenia**: Szybkie do obliczenia dla dowolnego danego wejścia\n- **Efekt lawiny**: Małe zmiany w wejściu powodują drastycznie różne wyjścia\n- **Nieodwracalna**: Obliczeniowo niemożliwe do odwrócenia skrótu w celu znalezienia oryginalnego wejścia\n- **Podatna na kolizje**: Znane podatności umożliwiają znalezienie kolizji\n\n**Status bezpieczeństwa:**\n⚠️ **SHA-1 jest kryptograficznie złamane i nie powinno być używane do aplikacji krytycznych dla bezpieczeństwa**. Ataki teoretyczne zostały zademonstrowane w 2005 roku, a praktyczne ataki kolizyjne zostały osiągnięte w 2017 roku.\n\n**Powszechne zastosowania (historyczne):**\n- Podpisy cyfrowe i certyfikaty (przestarzałe)\n- System kontroli wersji Git (dla kompatybilności)\n- Starsze systemy wymagające SHA-1\n- Weryfikacja integralności plików (niekrytyczna dla bezpieczeństwa)\n- Algorytmy proof-of-work (niektóre starsze kryptowaluty)\n\n**Zalecane alternatywy:**\n- SHA-256 lub SHA-3 dla nowych aplikacji\n- SHA-512 dla wysokich wymagań bezpieczeństwa"
  },
  "vi": {
    "what-is-sha1": "SHA-1 là gì?",
    "what-is-sha1-description-markdown": "SHA-1 (Secure Hash Algorithm 1) là một hàm băm mật mã tạo ra giá trị băm 160-bit (20-byte), thường được hiển thị dưới dạng số thập lục phân 40 ký tự. Nó được thiết kế bởi NSA và xuất bản bởi NIST năm 1995 như một phần của Tiêu chuẩn Chữ ký Số.\n\n**Đặc điểm chính:**\n- **Xác định**: Cùng một đầu vào luôn tạo ra cùng một băm\n- **Tính toán nhanh**: Nhanh chóng tính toán cho bất kỳ đầu vào nào\n- **Hiệu ứng tuyết lở**: Những thay đổi nhỏ trong đầu vào tạo ra đầu ra hoàn toàn khác biệt\n- **Không thể đảo ngược**: Không thể tính toán để đảo ngược băm để tìm đầu vào gốc\n- **Dễ bị va chạm**: Các lỗ hổng đã biết làm cho việc tìm ra va chạm trở nên khả thi\n\n**Tình trạng bảo mật:**\n⚠️ **SHA-1 đã bị phá vỡ về mặt mật mã và không nên được sử dụng cho các ứng dụng quan trọng về bảo mật**. Các cuộc tấn công lý thuyết được chứng minh vào năm 2005, và các cuộc tấn công va chạm thực tế được thực hiện vào năm 2017.\n\n**Sử dụng phổ biến (lịch sử):**\n- Chữ ký số và chứng chỉ (đã lỗi thời)\n- Hệ thống kiểm soát phiên bản Git (để tương thích)\n- Hệ thống cũ yêu cầu SHA-1\n- Xác minh tính toàn vẹn tệp (không quan trọng về bảo mật)\n- Thuật toán proof-of-work (một số tiền điện tử cũ hơn)\n\n**Các lựa chọn thay thế được đề xuất:**\n- SHA-256 hoặc SHA-3 cho các ứng dụng mới\n- SHA-512 cho yêu cầu bảo mật cao"
  },
  "th": {
    "what-is-sha1": "SHA-1 คืออะไร?",
    "what-is-sha1-description-markdown": "SHA-1 (Secure Hash Algorithm 1) เป็นฟังก์ชันแฮชเข้ารหัสที่สร้างค่าแฮช 160-บิต (20-ไบต์) ซึ่งมักแสดงเป็นตัวเลขฐานสิบหก 40 ตัวอักษร ออกแบบโดย NSA และเผยแพร่โดย NIST ในปี 1995 เป็นส่วนหนึ่งของมาตรฐานลายเซ็นดิจิทัล\n\n**คุณลักษณะสำคัญ:**\n- **กำหนดได้**: อินพุตเดียวกันจะสร้างแฮชเดียวกันเสมอ\n- **การคำนวณที่รวดเร็ว**: คำนวณได้อย่างรวดเร็วสำหรับอินพุตใดก็ตาม\n- **เอฟเฟกต์หิมะถล่ม**: การเปลี่ยนแปลงเล็กน้อยในอินพุตจะสร้างเอาต์พุตที่แตกต่างอย่างมาก\n- **ไม่สามารถย้อนกลับได้**: ไม่สามารถคำนวณเพื่อย้อนกลับแฮชเพื่อหาอินพุตต้นฉบับได้\n- **เสี่ยงต่อการชน**: ช่องโหว่ที่ทราบแล้วทำให้สามารถหาการชนได้\n\n**สถานะความปลอดภัย:**\n⚠️ **SHA-1 ถูกทำลายทางการเข้ารหัสแล้วและไม่ควรใช้สำหรับแอปพลิเคชันที่สำคัญด้านความปลอดภัย** การโจมตีเชิงทฤษฎีได้รับการพิสูจน์ในปี 2005 และการโจมตีการชนในทางปฏิบัติสำเร็จในปี 2017\n\n**การใช้งานทั่วไป (ประวัติศาสตร์):**\n- ลายเซ็นดิจิทัลและใบรับรอง (ล้าสมัย)\n- ระบบควบคุมเวอร์ชัน Git (เพื่อความเข้ากันได้)\n- ระบบเก่าที่ต้องการ SHA-1\n- การตรวจสอบความสมบูรณ์ของไฟล์ (ไม่สำคัญด้านความปลอดภัย)\n- อัลกอริทึม proof-of-work (สกุลเงินดิจิทัลเก่าบางตัว)\n\n**ทางเลือกที่แนะนำ:**\n- SHA-256 หรือ SHA-3 สำหรับแอปพลิเคชันใหม่\n- SHA-512 สำหรับความต้องการความปลอดภัยสูง"
  },
  "id": {
    "what-is-sha1": "Apa itu SHA-1?",
    "what-is-sha1-description-markdown": "SHA-1 (Secure Hash Algorithm 1) adalah fungsi hash kriptografi yang menghasilkan nilai hash 160-bit (20-byte), biasanya ditampilkan sebagai angka heksadesimal 40 karakter. Dirancang oleh NSA dan diterbitkan oleh NIST pada tahun 1995 sebagai bagian dari Digital Signature Standard.\n\n**Karakteristik utama:**\n- **Deterministik**: Input yang sama selalu menghasilkan hash yang sama\n- **Komputasi cepat**: Cepat dihitung untuk input apa pun\n- **Efek longsor**: Perubahan kecil pada input menghasilkan output yang sangat berbeda\n- **Tidak dapat dibalik**: Secara komputasi tidak mungkin membalik hash untuk menemukan input asli\n- **Rentan collision**: Kerentanan yang diketahui memungkinkan untuk menemukan collision\n\n**Status keamanan:**\n⚠️ **SHA-1 telah rusak secara kriptografi dan tidak boleh digunakan untuk aplikasi yang kritis keamanan**. Serangan teoretis didemonstrasikan pada tahun 2005, dan serangan collision praktis dicapai pada tahun 2017.\n\n**Penggunaan umum (historis):**\n- Tanda tangan digital dan sertifikat (deprecated)\n- Sistem kontrol versi Git (untuk kompatibilitas)\n- Sistem lama yang memerlukan SHA-1\n- Verifikasi integritas file (tidak kritis keamanan)\n- Algoritma proof-of-work (beberapa cryptocurrency lama)\n\n**Alternatif yang direkomendasikan:**\n- SHA-256 atau SHA-3 untuk aplikasi baru\n- SHA-512 untuk persyaratan keamanan tinggi"
  },
  "he": {
    "what-is-sha1": "מה זה SHA-1?",
    "what-is-sha1-description-markdown": "SHA-1 (Secure Hash Algorithm 1) הוא פונקציית האש קריפטוגרפית המייצרת ערך האש של 160-ביט (20-בייט), המוצג בדרך כלל כמספר הקסדצימלי של 40 תווים. הוא עוצב על ידי ה-NSA ופורסם על ידי NIST ב-1995 כחלק מתקן החתימה הדיגיטלית.\n\n**מאפיינים עיקריים:**\n- **דטרמיניסטי**: אותו קלט תמיד מייצר אותו האש\n- **חישוב מהיר**: מהיר לחישוב עבור כל קלט נתון\n- **אפקט מפולת**: שינויים קטנים בקלט מייצרים פלטים שונים בתכלית\n- **בלתי הפיך**: בלתי אפשרי חישובית להפוך את ההאש כדי למצוא את הקלט המקורי\n- **פגיע להתנגשויות**: פגיעויות ידועות מאפשרות למצוא התנגשויות\n\n**מצב אבטחה:**\n⚠️ **SHA-1 שבור קריפטוגרפית ולא צריך להיות בשימוש עבור יישומים קריטיים לאבטחה**. התקפות תיאורטיות הודגמו ב-2005, והתקפות התנגשות פרקטיות הושגו ב-2017.\n\n**שימושים נפוצים (היסטוריים):**\n- חתימות דיגיטליות ותעודות (מיושן)\n- מערכת בקרת גרסאות Git (לתאימות)\n- מערכות ישנות הדורשות SHA-1\n- אימות תקינות קבצים (לא קריטי לאבטחה)\n- אלגוריתמי הוכחת עבודה (כמה מטבעות קריפטו ישנים יותר)\n\n**חלופות מומלצות:**\n- SHA-256 או SHA-3 ליישומים חדשים\n- SHA-512 לדרישות אבטחה גבוהות"
  },
  "ms": {
    "what-is-sha1": "Apakah SHA-1?",
    "what-is-sha1-description-markdown": "SHA-1 (Secure Hash Algorithm 1) adalah fungsi hash kriptografi yang menghasilkan nilai hash 160-bit (20-byte), biasanya dipaparkan sebagai nombor heksadesimal 40 aksara. Ia direka oleh NSA dan diterbitkan oleh NIST pada tahun 1995 sebagai sebahagian daripada Piawaian Tandatangan Digital.\n\n**Ciri-ciri utama:**\n- **Deterministik**: Input yang sama sentiasa menghasilkan hash yang sama\n- **Pengiraan pantas**: Pantas dikira untuk sebarang input yang diberikan\n- **Kesan runtuhan salji**: Perubahan kecil dalam input menghasilkan output yang sangat berbeza\n- **Tidak boleh dibalik**: Mustahil secara pengiraan untuk membalikkan hash untuk mencari input asal\n- **Terdedah kepada perlanggaran**: Kelemahan yang diketahui membolehkan pencarian perlanggaran\n\n**Status keselamatan:**\n⚠️ **SHA-1 telah rosak secara kriptografi dan tidak sepatutnya digunakan untuk aplikasi kritikal keselamatan**. Serangan teori telah ditunjukkan pada tahun 2005, dan serangan perlanggaran praktikal dicapai pada tahun 2017.\n\n**Kegunaan biasa (sejarah):**\n- Tandatangan digital dan sijil (terkini)\n- Sistem kawalan versi Git (untuk keserasian)\n- Sistem lama yang memerlukan SHA-1\n- Pengesahan integriti fail (tidak kritikal keselamatan)\n- Algoritma bukti kerja (beberapa mata wang kripto lama)\n\n**Alternatif yang disyorkan:**\n- SHA-256 atau SHA-3 untuk aplikasi baharu\n- SHA-512 untuk keperluan keselamatan tinggi"
  },
  "no": {
    "what-is-sha1": "Hva er SHA-1?",
    "what-is-sha1-description-markdown": "SHA-1 (Secure Hash Algorithm 1) er en kryptografisk hash-funksjon som produserer en 160-bits (20-byte) hash-verdi, vanligvis gjengitt som et 40-tegn heksadesimalt tall. Den ble designet av NSA og publisert av NIST i 1995 som en del av Digital Signature Standard.\n\n**Nøkkelegenskaper:**\n- **Deterministisk**: Samme inndata produserer alltid samme hash\n- **Rask beregning**: Rask å beregne for enhver gitt inndata\n- **Snøskredeffekt**: Små endringer i inndata produserer drastisk forskjellige utdata\n- **Irreversibel**: Beregningsmessig umulig å reversere hashen for å finne opprinnelig inndata\n- **Sårbar for kollisjoner**: Kjente sårbarheter gjør det mulig å finne kollisjoner\n\n**Sikkerhetsstatus:**\n⚠️ **SHA-1 er kryptografisk ødelagt og bør ikke brukes for sikkerhetskritiske applikasjoner**. Teoretiske angrep ble demonstrert i 2005, og praktiske kollisjonsangrep ble oppnådd i 2017.\n\n**Vanlige bruksområder (historiske):**\n- Digitale signaturer og sertifikater (utdatert)\n- Git versjonskontrollsystem (for kompatibilitet)\n- Eldre systemer som krever SHA-1\n- Filintegritetsverifisering (ikke sikkerhetskritisk)\n- Proof-of-work algoritmer (noen eldre kryptovalutaer)\n\n**Anbefalte alternativer:**\n- SHA-256 eller SHA-3 for nye applikasjoner\n- SHA-512 for høye sikkerhetskrav"
  }
}
</i18n>
