<template>
  <DescriptionMarkdown
    :title="t('what-is-blake2b')"
    :description="t('what-is-blake2b-description-markdown')"
  />
</template>

<script setup lang="ts">
import { DescriptionMarkdown } from '@shared/ui/base'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()
</script>

<i18n lang="json">
{
  "en": {
    "what-is-blake2b": "What is BLAKE2b?",
    "what-is-blake2b-description-markdown": "BLAKE2b is a cryptographic hash function that is faster than MD5, SHA-1, SHA-2, and SHA-3, yet is at least as secure as the latest standard SHA-3. It produces variable-length hash outputs from 8 to 512 bits (1 to 64 bytes). BLAKE2b is optimized for 64-bit platforms and is part of the BLAKE2 family developed by Jean-Philippe Aumasson, Samuel Neves, Zooko Wilcox-O'Hearn, and Christian Winnerlein.\n\n**Key characteristics:**\n- **Variable output length**: Can produce hashes from 8 to 512 bits\n- **High performance**: Faster than SHA-2 and SHA-3 while maintaining security\n- **Deterministic**: The same input always produces the same hash\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Irreversible**: Computationally infeasible to reverse the hash to find the original input\n- **Collision resistant**: Very difficult to find two different inputs that produce the same hash\n- **Keyed hashing**: Supports optional key input for MAC functionality\n\n**Common uses:**\n- File integrity verification\n- Digital signatures and certificates\n- Password storage and authentication\n- Blockchain and cryptocurrency applications\n- High-performance applications requiring fast hashing\n- Cryptographic protocols and systems"
  },
  "zh": {
    "what-is-blake2b": "什么是 BLAKE2b？",
    "what-is-blake2b-description-markdown": "BLAKE2b 是一种加密散列函数，比 MD5、SHA-1、SHA-2 和 SHA-3 更快，但至少与最新标准 SHA-3 一样安全。它可以产生从 8 到 512 位（1 到 64 字节）的可变长度散列输出。BLAKE2b 针对 64 位平台进行了优化，是由 Jean-Philippe Aumasson、Samuel Neves、Zooko Wilcox-O'Hearn 和 Christian Winnerlein 开发的 BLAKE2 系列的一部分。\n\n**主要特征：**\n- **可变输出长度**：可以产生从 8 到 512 位的散列\n- **高性能**：比 SHA-2 和 SHA-3 更快，同时保持安全性\n- **确定性**：相同的输入总是产生相同的散列\n- **雪崩效应**：输入的微小变化会产生截然不同的输出\n- **不可逆**：从散列反推原始输入在计算上是不可行的\n- **抗碰撞**：很难找到产生相同散列的两个不同输入\n- **密钥散列**：支持可选的密钥输入以实现 MAC 功能\n\n**常见用途：**\n- 文件完整性验证\n- 数字签名和证书\n- 密码存储和身份验证\n- 区块链和加密货币应用\n- 需要快速散列的高性能应用\n- 加密协议和系统"
  },
  "zh-CN": {
    "what-is-blake2b": "什么是 BLAKE2b？",
    "what-is-blake2b-description-markdown": "BLAKE2b 是一种加密散列函数，比 MD5、SHA-1、SHA-2 和 SHA-3 更快，但至少与最新标准 SHA-3 一样安全。它可以产生从 8 到 512 位（1 到 64 字节）的可变长度散列输出。BLAKE2b 针对 64 位平台进行了优化，是由 Jean-Philippe Aumasson、Samuel Neves、Zooko Wilcox-O'Hearn 和 Christian Winnerlein 开发的 BLAKE2 系列的一部分。\n\n**主要特征：**\n- **可变输出长度**：可以产生从 8 到 512 位的散列\n- **高性能**：比 SHA-2 和 SHA-3 更快，同时保持安全性\n- **确定性**：相同的输入总是产生相同的散列\n- **雪崩效应**：输入的微小变化会产生截然不同的输出\n- **不可逆**：从散列反推原始输入在计算上是不可行的\n- **抗碰撞**：很难找到产生相同散列的两个不同输入\n- **密钥散列**：支持可选的密钥输入以实现 MAC 功能\n\n**常见用途：**\n- 文件完整性验证\n- 数字签名和证书\n- 密码存储和身份验证\n- 区块链和加密货币应用\n- 需要快速散列的高性能应用\n- 加密协议和系统"
  },
  "zh-TW": {
    "what-is-blake2b": "什麼是 BLAKE2b？",
    "what-is-blake2b-description-markdown": "BLAKE2b 是一種加密雜湊函數，比 MD5、SHA-1、SHA-2 和 SHA-3 更快，但至少與最新標準 SHA-3 一樣安全。它可以產生從 8 到 512 位元（1 到 64 位元組）的可變長度雜湊輸出。BLAKE2b 針對 64 位元平台進行了最佳化，是由 Jean-Philippe Aumasson、Samuel Neves、Zooko Wilcox-O'Hearn 和 Christian Winnerlein 開發的 BLAKE2 系列的一部分。\n\n**主要特徵：**\n- **可變輸出長度**：可以產生從 8 到 512 位元的雜湊\n- **高效能**：比 SHA-2 和 SHA-3 更快，同時保持安全性\n- **確定性**：相同的輸入總是產生相同的雜湊\n- **雪崩效應**：輸入的微小變化會產生截然不同的輸出\n- **不可逆**：從雜湊反推原始輸入在計算上是不可行的\n- **抗碰撞**：很難找到產生相同雜湊的兩個不同輸入\n- **金鑰雜湊**：支援可選的金鑰輸入以實現 MAC 功能\n\n**常見用途：**\n- 檔案完整性驗證\n- 數位簽章和憑證\n- 密碼儲存和身份驗證\n- 區塊鏈和加密貨幣應用\n- 需要快速雜湊的高效能應用\n- 加密協定和系統"
  },
  "zh-HK": {
    "what-is-blake2b": "什麼是 BLAKE2b？",
    "what-is-blake2b-description-markdown": "BLAKE2b 是一種加密雜湊函數，比 MD5、SHA-1、SHA-2 和 SHA-3 更快，但至少與最新標準 SHA-3 一樣安全。它可以產生從 8 到 512 位元（1 到 64 位元組）的可變長度雜湊輸出。BLAKE2b 針對 64 位元平台進行了最佳化，是由 Jean-Philippe Aumasson、Samuel Neves、Zooko Wilcox-O'Hearn 和 Christian Winnerlein 開發的 BLAKE2 系列的一部分。\n\n**主要特徵：**\n- **可變輸出長度**：可以產生從 8 到 512 位元的雜湊\n- **高效能**：比 SHA-2 和 SHA-3 更快，同時保持安全性\n- **確定性**：相同的輸入總是產生相同的雜湊\n- **雪崩效應**：輸入的微小變化會產生截然不同的輸出\n- **不可逆**：從雜湊反推原始輸入在計算上是不可行的\n- **抗碰撞**：很難找到產生相同雜湊的兩個不同輸入\n- **金鑰雜湊**：支援可選的金鑰輸入以實現 MAC 功能\n\n**常見用途：**\n- 檔案完整性驗證\n- 數碼簽署和證書\n- 密碼儲存和身份驗證\n- 區塊鏈和加密貨幣應用\n- 需要快速雜湊的高效能應用\n- 加密協定和系統"
  },
  "es": {
    "what-is-blake2b": "¿Qué es BLAKE2b?",
    "what-is-blake2b-description-markdown": "BLAKE2b es una función hash criptográfica que es más rápida que MD5, SHA-1, SHA-2 y SHA-3, pero al menos tan segura como el último estándar SHA-3. Produce salidas hash de longitud variable de 8 a 512 bits (1 a 64 bytes). BLAKE2b está optimizado para plataformas de 64 bits y es parte de la familia BLAKE2 desarrollada por Jean-Philippe Aumasson, Samuel Neves, Zooko Wilcox-O'Hearn y Christian Winnerlein.\n\n**Características clave:**\n- **Longitud de salida variable**: Puede producir hashes de 8 a 512 bits\n- **Alto rendimiento**: Más rápido que SHA-2 y SHA-3 manteniendo la seguridad\n- **Determinístico**: La misma entrada siempre produce el mismo hash\n- **Efecto avalancha**: Pequeños cambios en la entrada producen salidas drásticamente diferentes\n- **Irreversible**: Es computacionalmente inviable revertir el hash para encontrar la entrada original\n- **Resistente a colisiones**: Muy difícil encontrar dos entradas diferentes que produzcan el mismo hash\n- **Hash con clave**: Admite entrada de clave opcional para funcionalidad MAC\n\n**Usos comunes:**\n- Verificación de integridad de archivos\n- Firmas digitales y certificados\n- Almacenamiento y autenticación de contraseñas\n- Aplicaciones de blockchain y criptomonedas\n- Aplicaciones de alto rendimiento que requieren hash rápido\n- Protocolos y sistemas criptográficos"
  },
  "fr": {
    "what-is-blake2b": "Qu'est-ce que BLAKE2b ?",
    "what-is-blake2b-description-markdown": "BLAKE2b est une fonction de hachage cryptographique qui est plus rapide que MD5, SHA-1, SHA-2 et SHA-3, tout en étant au moins aussi sécurisée que le dernier standard SHA-3. Elle produit des sorties de hachage de longueur variable de 8 à 512 bits (1 à 64 octets). BLAKE2b est optimisé pour les plateformes 64 bits et fait partie de la famille BLAKE2 développée par Jean-Philippe Aumasson, Samuel Neves, Zooko Wilcox-O'Hearn et Christian Winnerlein.\n\n**Caractéristiques clés :**\n- **Longueur de sortie variable** : Peut produire des hachages de 8 à 512 bits\n- **Haute performance** : Plus rapide que SHA-2 et SHA-3 tout en maintenant la sécurité\n- **Déterministe** : La même entrée produit toujours le même hachage\n- **Effet d'avalanche** : De petits changements dans l'entrée produisent des sorties drastiquement différentes\n- **Irréversible** : Il est informatiquement impossible d'inverser le hachage pour trouver l'entrée originale\n- **Résistant aux collisions** : Très difficile de trouver deux entrées différentes qui produisent le même hachage\n- **Hachage avec clé** : Prend en charge l'entrée de clé optionnelle pour la fonctionnalité MAC\n\n**Utilisations courantes :**\n- Vérification d'intégrité de fichiers\n- Signatures numériques et certificats\n- Stockage et authentification de mots de passe\n- Applications blockchain et cryptomonnaies\n- Applications haute performance nécessitant un hachage rapide\n- Protocoles et systèmes cryptographiques"
  },
  "de": {
    "what-is-blake2b": "Was ist BLAKE2b?",
    "what-is-blake2b-description-markdown": "BLAKE2b ist eine kryptographische Hash-Funktion, die schneller ist als MD5, SHA-1, SHA-2 und SHA-3, aber mindestens so sicher wie der neueste Standard SHA-3. Sie erzeugt Hash-Ausgaben variabler Länge von 8 bis 512 Bits (1 bis 64 Bytes). BLAKE2b ist für 64-Bit-Plattformen optimiert und ist Teil der BLAKE2-Familie, die von Jean-Philippe Aumasson, Samuel Neves, Zooko Wilcox-O'Hearn und Christian Winnerlein entwickelt wurde.\n\n**Hauptmerkmale:**\n- **Variable Ausgabelänge**: Kann Hashes von 8 bis 512 Bits erzeugen\n- **Hohe Leistung**: Schneller als SHA-2 und SHA-3 bei Beibehaltung der Sicherheit\n- **Deterministisch**: Dieselbe Eingabe erzeugt immer denselben Hash\n- **Lawineneffekt**: Kleine Änderungen in der Eingabe erzeugen drastisch unterschiedliche Ausgaben\n- **Irreversibel**: Rechnerisch nicht machbar, den Hash umzukehren, um die ursprüngliche Eingabe zu finden\n- **Kollisionsresistent**: Sehr schwierig, zwei verschiedene Eingaben zu finden, die denselben Hash erzeugen\n- **Schlüssel-Hash**: Unterstützt optionale Schlüsseleingabe für MAC-Funktionalität\n\n**Häufige Verwendungen:**\n- Datei-Integritätsprüfung\n- Digitale Signaturen und Zertifikate\n- Passwort-Speicherung und Authentifizierung\n- Blockchain- und Kryptowährungsanwendungen\n- Hochleistungsanwendungen, die schnelles Hashing erfordern\n- Kryptographische Protokolle und Systeme"
  },
  "it": {
    "what-is-blake2b": "Cos'è BLAKE2b?",
    "what-is-blake2b-description-markdown": "BLAKE2b è una funzione hash crittografica che è più veloce di MD5, SHA-1, SHA-2 e SHA-3, eppure è almeno sicura quanto l'ultimo standard SHA-3. Produce output hash di lunghezza variabile da 8 a 512 bit (da 1 a 64 byte). BLAKE2b è ottimizzato per piattaforme a 64 bit ed è parte della famiglia BLAKE2 sviluppata da Jean-Philippe Aumasson, Samuel Neves, Zooko Wilcox-O'Hearn e Christian Winnerlein.\n\n**Caratteristiche chiave:**\n- **Lunghezza di output variabile**: Può produrre hash da 8 a 512 bit\n- **Alte prestazioni**: Più veloce di SHA-2 e SHA-3 mantenendo la sicurezza\n- **Deterministico**: Lo stesso input produce sempre lo stesso hash\n- **Effetto valanga**: Piccoli cambiamenti nell'input producono output drasticamente diversi\n- **Irreversibile**: Computazionalmente impossibile invertire l'hash per trovare l'input originale\n- **Resistente alle collisioni**: Molto difficile trovare due input diversi che producano lo stesso hash\n- **Hash con chiave**: Supporta input di chiave opzionale per funzionalità MAC\n\n**Usi comuni:**\n- Verifica dell'integrità dei file\n- Firme digitali e certificati\n- Archiviazione e autenticazione password\n- Applicazioni blockchain e criptovalute\n- Applicazioni ad alte prestazioni che richiedono hashing veloce\n- Protocolli e sistemi crittografici"
  },
  "ja": {
    "what-is-blake2b": "BLAKE2bとは？",
    "what-is-blake2b-description-markdown": "BLAKE2bは、MD5、SHA-1、SHA-2、SHA-3よりも高速でありながら、最新標準のSHA-3と少なくとも同等の安全性を持つ暗号学的ハッシュ関数です。8から512ビット（1から64バイト）の可変長ハッシュ出力を生成します。BLAKE2bは64ビットプラットフォーム用に最適化されており、Jean-Philippe Aumasson、Samuel Neves、Zooko Wilcox-O'Hearn、Christian Winnerleinによって開発されたBLAKE2ファミリーの一部です。\n\n**主な特徴：**\n- **可変出力長**：8から512ビットのハッシュを生成可能\n- **高性能**：安全性を維持しながらSHA-2やSHA-3より高速\n- **決定論的**：同じ入力は常に同じハッシュを生成\n- **雪崩効果**：入力の小さな変化が劇的に異なる出力を生成\n- **不可逆**：ハッシュを逆算して元の入力を見つけることは計算上不可能\n- **衝突耐性**：同じハッシュを生成する2つの異なる入力を見つけることは非常に困難\n- **キー付きハッシュ**：MAC機能のためのオプションキー入力をサポート\n\n**一般的な用途：**\n- ファイル整合性検証\n- デジタル署名と証明書\n- パスワード保存と認証\n- ブロックチェーンと暗号通貨アプリケーション\n- 高速ハッシュが必要な高性能アプリケーション\n- 暗号プロトコルとシステム"
  },
  "ko": {
    "what-is-blake2b": "BLAKE2b란?",
    "what-is-blake2b-description-markdown": "BLAKE2b는 MD5, SHA-1, SHA-2, SHA-3보다 빠르면서도 최신 표준인 SHA-3만큼 안전한 암호화 해시 함수입니다. 8비트에서 512비트(1바이트에서 64바이트)까지의 가변 길이 해시 출력을 생성합니다. BLAKE2b는 64비트 플랫폼에 최적화되어 있으며, Jean-Philippe Aumasson, Samuel Neves, Zooko Wilcox-O'Hearn, Christian Winnerlein이 개발한 BLAKE2 패밀리의 일부입니다.\n\n**주요 특징:**\n- **가변 출력 길이**: 8비트에서 512비트까지의 해시 생성 가능\n- **고성능**: 보안성을 유지하면서 SHA-2, SHA-3보다 빠름\n- **결정론적**: 동일한 입력은 항상 동일한 해시를 생성\n- **눈사태 효과**: 입력의 작은 변화가 완전히 다른 출력을 생성\n- **비가역적**: 해시를 역산하여 원본 입력을 찾는 것은 계산적으로 불가능\n- **충돌 저항성**: 동일한 해시를 생성하는 두 개의 다른 입력을 찾기 매우 어려움\n- **키 해싱**: MAC 기능을 위한 선택적 키 입력 지원\n\n**일반적인 용도:**\n- 파일 무결성 검증\n- 디지털 서명 및 인증서\n- 비밀번호 저장 및 인증\n- 블록체인 및 암호화폐 애플리케이션\n- 빠른 해싱이 필요한 고성능 애플리케이션\n- 암호화 프로토콜 및 시스템"
  },
  "ru": {
    "what-is-blake2b": "Что такое BLAKE2b?",
    "what-is-blake2b-description-markdown": "BLAKE2b — это криптографическая хеш-функция, которая быстрее MD5, SHA-1, SHA-2 и SHA-3, но при этом как минимум так же безопасна, как последний стандарт SHA-3. Она производит хеш-выводы переменной длины от 8 до 512 бит (от 1 до 64 байт). BLAKE2b оптимизирован для 64-битных платформ и является частью семейства BLAKE2, разработанного Jean-Philippe Aumasson, Samuel Neves, Zooko Wilcox-O'Hearn и Christian Winnerlein.\n\n**Ключевые характеристики:**\n- **Переменная длина вывода**: Может производить хеши от 8 до 512 бит\n- **Высокая производительность**: Быстрее SHA-2 и SHA-3 при сохранении безопасности\n- **Детерминированность**: Одинаковый ввод всегда производит одинаковый хеш\n- **Эффект лавины**: Небольшие изменения во вводе производят кардинально разные выводы\n- **Необратимость**: Вычислительно невозможно обратить хеш для поиска исходного ввода\n- **Устойчивость к коллизиям**: Очень сложно найти два разных ввода, которые производят одинаковый хеш\n- **Хеширование с ключом**: Поддерживает опциональный ввод ключа для функциональности MAC\n\n**Обычные применения:**\n- Проверка целостности файлов\n- Цифровые подписи и сертификаты\n- Хранение и аутентификация паролей\n- Приложения блокчейн и криптовалют\n- Высокопроизводительные приложения, требующие быстрого хеширования\n- Криптографические протоколы и системы"
  },
  "pt": {
    "what-is-blake2b": "O que é BLAKE2b?",
    "what-is-blake2b-description-markdown": "BLAKE2b é uma função hash criptográfica que é mais rápida que MD5, SHA-1, SHA-2 e SHA-3, mas pelo menos tão segura quanto o último padrão SHA-3. Produz saídas hash de comprimento variável de 8 a 512 bits (1 a 64 bytes). BLAKE2b é otimizado para plataformas de 64 bits e faz parte da família BLAKE2 desenvolvida por Jean-Philippe Aumasson, Samuel Neves, Zooko Wilcox-O'Hearn e Christian Winnerlein.\n\n**Características principais:**\n- **Comprimento de saída variável**: Pode produzir hashes de 8 a 512 bits\n- **Alto desempenho**: Mais rápido que SHA-2 e SHA-3 mantendo a segurança\n- **Determinístico**: A mesma entrada sempre produz o mesmo hash\n- **Efeito avalanche**: Pequenas mudanças na entrada produzem saídas drasticamente diferentes\n- **Irreversível**: Computacionalmente inviável reverter o hash para encontrar a entrada original\n- **Resistente a colisões**: Muito difícil encontrar duas entradas diferentes que produzam o mesmo hash\n- **Hash com chave**: Suporta entrada de chave opcional para funcionalidade MAC\n\n**Usos comuns:**\n- Verificação de integridade de arquivos\n- Assinaturas digitais e certificados\n- Armazenamento e autenticação de senhas\n- Aplicações de blockchain e criptomoedas\n- Aplicações de alto desempenho que requerem hash rápido\n- Protocolos e sistemas criptográficos"
  },
  "ar": {
    "what-is-blake2b": "ما هو BLAKE2b؟",
    "what-is-blake2b-description-markdown": "BLAKE2b هي دالة تشفير أسرع من MD5 و SHA-1 و SHA-2 و SHA-3، ولكنها آمنة على الأقل مثل أحدث معيار SHA-3. تنتج مخرجات تشفير متغيرة الطول من 8 إلى 512 بت (1 إلى 64 بايت). BLAKE2b محسّنة لمنصات 64 بت وهي جزء من عائلة BLAKE2 التي طورها Jean-Philippe Aumasson و Samuel Neves و Zooko Wilcox-O'Hearn و Christian Winnerlein.\n\n**الخصائص الرئيسية:**\n- **طول المخرج المتغير**: يمكن أن تنتج تشفيرات من 8 إلى 512 بت\n- **أداء عالي**: أسرع من SHA-2 و SHA-3 مع الحفاظ على الأمان\n- **حتمية**: نفس المدخل ينتج دائماً نفس التشفير\n- **تأثير الانهيار الجليدي**: تغييرات صغيرة في المدخل تنتج مخرجات مختلفة تماماً\n- **غير قابلة للعكس**: من المستحيل حاسوبياً عكس التشفير لإيجاد المدخل الأصلي\n- **مقاومة للتصادمات**: صعب جداً إيجاد مدخلين مختلفين ينتجان نفس التشفير\n- **تشفير بمفتاح**: يدعم إدخال مفتاح اختياري لوظيفة MAC\n\n**الاستخدامات الشائعة:**\n- التحقق من سلامة الملفات\n- التوقيعات الرقمية والشهادات\n- تخزين ومصادقة كلمات المرور\n- تطبيقات البلوك تشين والعملات المشفرة\n- تطبيقات الأداء العالي التي تتطلب تشفيراً سريعاً\n- البروتوكولات والأنظمة المشفرة"
  },
  "hi": {
    "what-is-blake2b": "BLAKE2b क्या है?",
    "what-is-blake2b-description-markdown": "BLAKE2b एक क्रिप्टोग्राफिक हैश फ़ंक्शन है जो MD5, SHA-1, SHA-2, और SHA-3 से तेज़ है, फिर भी कम से कम नवीनतम मानक SHA-3 जितना सुरक्षित है। यह 8 से 512 बिट्स (1 से 64 बाइट्स) तक के चर-लंबाई हैश आउटपुट उत्पन्न करता है। BLAKE2b 64-बिट प्लेटफॉर्म के लिए अनुकूलित है और Jean-Philippe Aumasson, Samuel Neves, Zooko Wilcox-O'Hearn, और Christian Winnerlein द्वारा विकसित BLAKE2 परिवार का हिस्सा है।\n\n**मुख्य विशेषताएं:**\n- **चर आउटपुट लंबाई**: 8 से 512 बिट्स तक हैश उत्पन्न कर सकता है\n- **उच्च प्रदर्शन**: सुरक्षा बनाए रखते हुए SHA-2 और SHA-3 से तेज़\n- **निर्धारक**: समान इनपुट हमेशा समान हैश उत्पन्न करता है\n- **हिमस्खलन प्रभाव**: इनपुट में छोटे बदलाव बेहद अलग आउटपुट उत्पन्न करते हैं\n- **अपरिवर्तनीय**: मूल इनपुट खोजने के लिए हैश को उलटना कम्प्यूटेशनल रूप से असंभव\n- **टक्कर प्रतिरोधी**: समान हैश उत्पन्न करने वाले दो अलग इनपुट खोजना बहुत कठिन\n- **कुंजी हैशिंग**: MAC कार्यक्षमता के लिए वैकल्पिक कुंजी इनपुट का समर्थन करता है\n\n**सामान्य उपयोग:**\n- फ़ाइल अखंडता सत्यापन\n- डिजिटल हस्ताक्षर और प्रमाणपत्र\n- पासवर्ड भंडारण और प्रमाणीकरण\n- ब्लॉकचेन और क्रिप्टोकरेंसी एप्लिकेशन\n- तेज़ हैशिंग की आवश्यकता वाले उच्च-प्रदर्शन एप्लिकेशन\n- क्रिप्टोग्राफिक प्रोटोकॉल और सिस्टम"
  },
  "tr": {
    "what-is-blake2b": "BLAKE2b nedir?",
    "what-is-blake2b-description-markdown": "BLAKE2b, MD5, SHA-1, SHA-2 ve SHA-3'ten daha hızlı olan, ancak en azından en son standart SHA-3 kadar güvenli olan bir kriptografik hash fonksiyonudur. 8 ila 512 bit (1 ila 64 bayt) arası değişken uzunlukta hash çıktıları üretir. BLAKE2b, 64-bit platformlar için optimize edilmiştir ve Jean-Philippe Aumasson, Samuel Neves, Zooko Wilcox-O'Hearn ve Christian Winnerlein tarafından geliştirilen BLAKE2 ailesinin bir parçasıdır.\n\n**Temel özellikler:**\n- **Değişken çıktı uzunluğu**: 8 ila 512 bit arası hash üretebilir\n- **Yüksek performans**: Güvenliği korurken SHA-2 ve SHA-3'ten daha hızlı\n- **Deterministik**: Aynı girdi her zaman aynı hash'i üretir\n- **Çığ etkisi**: Girdideki küçük değişiklikler büyük ölçüde farklı çıktılar üretir\n- **Geri döndürülemez**: Hash'i tersine çevirerek orijinal girdiyi bulmak hesaplamalı olarak mümkün değildir\n- **Çarpışma dirençli**: Aynı hash'i üreten iki farklı girdi bulmak çok zordur\n- **Anahtarlı hash**: MAC işlevselliği için isteğe bağlı anahtar girdisini destekler\n\n**Yaygın kullanımlar:**\n- Dosya bütünlüğü doğrulama\n- Dijital imzalar ve sertifikalar\n- Şifre depolama ve kimlik doğrulama\n- Blok zinciri ve kripto para uygulamaları\n- Hızlı hash gerektiren yüksek performanslı uygulamalar\n- Kriptografik protokoller ve sistemler"
  },
  "nl": {
    "what-is-blake2b": "Wat is BLAKE2b?",
    "what-is-blake2b-description-markdown": "BLAKE2b is een cryptografische hashfunctie die sneller is dan MD5, SHA-1, SHA-2 en SHA-3, maar minstens zo veilig als de nieuwste standaard SHA-3. Het produceert hash-uitvoer van variabele lengte van 8 tot 512 bits (1 tot 64 bytes). BLAKE2b is geoptimaliseerd voor 64-bits platforms en is onderdeel van de BLAKE2-familie ontwikkeld door Jean-Philippe Aumasson, Samuel Neves, Zooko Wilcox-O'Hearn en Christian Winnerlein.\n\n**Belangrijkste kenmerken:**\n- **Variabele uitvoerlengte**: Kan hashes van 8 tot 512 bits produceren\n- **Hoge prestaties**: Sneller dan SHA-2 en SHA-3 terwijl veiligheid behouden blijft\n- **Deterministisch**: Dezelfde invoer produceert altijd dezelfde hash\n- **Lawine-effect**: Kleine veranderingen in invoer produceren drastisch verschillende uitvoer\n- **Onomkeerbaar**: Computationeel onhaalbaar om de hash om te keren om de oorspronkelijke invoer te vinden\n- **Botsingsbestendig**: Zeer moeilijk om twee verschillende invoeren te vinden die dezelfde hash produceren\n- **Sleutel-hashing**: Ondersteunt optionele sleutelinvoer voor MAC-functionaliteit\n\n**Veelvoorkomende toepassingen:**\n- Bestandsintegriteitsverificatie\n- Digitale handtekeningen en certificaten\n- Wachtwoordopslag en authenticatie\n- Blockchain en cryptocurrency-toepassingen\n- Hoge prestatie-toepassingen die snelle hashing vereisen\n- Cryptografische protocollen en systemen"
  },
  "sv": {
    "what-is-blake2b": "Vad är BLAKE2b?",
    "what-is-blake2b-description-markdown": "BLAKE2b är en kryptografisk hashfunktion som är snabbare än MD5, SHA-1, SHA-2 och SHA-3, men ändå minst lika säker som den senaste standarden SHA-3. Den producerar hash-utmatningar av variabel längd från 8 till 512 bitar (1 till 64 bytes). BLAKE2b är optimerad för 64-bitars plattformar och är en del av BLAKE2-familjen utvecklad av Jean-Philippe Aumasson, Samuel Neves, Zooko Wilcox-O'Hearn och Christian Winnerlein.\n\n**Nyckelegenskaper:**\n- **Variabel utmatningslängd**: Kan producera hasher från 8 till 512 bitar\n- **Hög prestanda**: Snabbare än SHA-2 och SHA-3 samtidigt som säkerheten bibehålls\n- **Deterministisk**: Samma inmatning producerar alltid samma hash\n- **Lavineffekt**: Små förändringar i inmatningen producerar drastiskt olika utmatningar\n- **Irreversibel**: Beräkningsmässigt omöjligt att vända hashen för att hitta den ursprungliga inmatningen\n- **Kollisionsresistent**: Mycket svårt att hitta två olika inmatningar som producerar samma hash\n- **Nyckel-hashing**: Stöder valfri nyckelinmatning för MAC-funktionalitet\n\n**Vanliga användningar:**\n- Filintegritetsverifiering\n- Digitala signaturer och certifikat\n- Lösenordslagring och autentisering\n- Blockchain och kryptovaluta-applikationer\n- Höga prestanda-applikationer som kräver snabb hashing\n- Kryptografiska protokoll och system"
  },
  "pl": {
    "what-is-blake2b": "Czym jest BLAKE2b?",
    "what-is-blake2b-description-markdown": "BLAKE2b to kryptograficzna funkcja skrótu, która jest szybsza niż MD5, SHA-1, SHA-2 i SHA-3, a jednocześnie co najmniej tak bezpieczna jak najnowszy standard SHA-3. Produkuje wyjścia skrótu o zmiennej długości od 8 do 512 bitów (od 1 do 64 bajtów). BLAKE2b jest zoptymalizowany dla platform 64-bitowych i jest częścią rodziny BLAKE2 opracowanej przez Jean-Philippe Aumasson, Samuel Neves, Zooko Wilcox-O'Hearn i Christian Winnerlein.\n\n**Kluczowe cechy:**\n- **Zmienna długość wyjścia**: Może produkować skróty od 8 do 512 bitów\n- **Wysoka wydajność**: Szybszy niż SHA-2 i SHA-3 przy zachowaniu bezpieczeństwa\n- **Deterministyczna**: To samo wejście zawsze produkuje ten sam skrót\n- **Efekt lawiny**: Małe zmiany w wejściu powodują drastycznie różne wyjścia\n- **Nieodwracalna**: Obliczeniowo niemożliwe do odwrócenia skrótu w celu znalezienia oryginalnego wejścia\n- **Odporna na kolizje**: Bardzo trudno znaleźć dwa różne wejścia, które produkują ten sam skrót\n- **Hashing z kluczem**: Obsługuje opcjonalne wejście klucza dla funkcjonalności MAC\n\n**Powszechne zastosowania:**\n- Weryfikacja integralności plików\n- Podpisy cyfrowe i certyfikaty\n- Przechowywanie i uwierzytelnianie haseł\n- Aplikacje blockchain i kryptowalut\n- Aplikacje wysokiej wydajności wymagające szybkiego hashingu\n- Protokoły i systemy kryptograficzne"
  },
  "vi": {
    "what-is-blake2b": "BLAKE2b là gì?",
    "what-is-blake2b-description-markdown": "BLAKE2b là một hàm băm mật mã nhanh hơn MD5, SHA-1, SHA-2 và SHA-3, nhưng ít nhất cũng an toàn như tiêu chuẩn mới nhất SHA-3. Nó tạo ra đầu ra băm có độ dài thay đổi từ 8 đến 512 bit (1 đến 64 byte). BLAKE2b được tối ưu hóa cho các nền tảng 64-bit và là một phần của họ BLAKE2 được phát triển bởi Jean-Philippe Aumasson, Samuel Neves, Zooko Wilcox-O'Hearn và Christian Winnerlein.\n\n**Đặc điểm chính:**\n- **Độ dài đầu ra thay đổi**: Có thể tạo ra băm từ 8 đến 512 bit\n- **Hiệu suất cao**: Nhanh hơn SHA-2 và SHA-3 trong khi duy trì bảo mật\n- **Xác định**: Cùng một đầu vào luôn tạo ra cùng một băm\n- **Hiệu ứng tuyết lở**: Những thay đổi nhỏ trong đầu vào tạo ra đầu ra hoàn toàn khác biệt\n- **Không thể đảo ngược**: Không thể tính toán để đảo ngược băm để tìm đầu vào gốc\n- **Chống va chạm**: Rất khó tìm hai đầu vào khác nhau tạo ra cùng một băm\n- **Băm có khóa**: Hỗ trợ đầu vào khóa tùy chọn cho chức năng MAC\n\n**Sử dụng phổ biến:**\n- Xác minh tính toàn vẹn tệp\n- Chữ ký số và chứng chỉ\n- Lưu trữ và xác thực mật khẩu\n- Ứng dụng blockchain và tiền điện tử\n- Ứng dụng hiệu suất cao yêu cầu băm nhanh\n- Giao thức và hệ thống mật mã"
  },
  "th": {
    "what-is-blake2b": "BLAKE2b คืออะไร?",
    "what-is-blake2b-description-markdown": "BLAKE2b เป็นฟังก์ชันแฮชเข้ารหัสที่เร็วกว่า MD5, SHA-1, SHA-2 และ SHA-3 แต่ปลอดภัยอย่างน้อยเท่ากับมาตรฐานล่าสุด SHA-3 มันสร้างเอาต์พุตแฮชความยาวแปรผันตั้งแต่ 8 ถึง 512 บิต (1 ถึง 64 ไบต์) BLAKE2b ได้รับการปรับให้เหมาะสมสำหรับแพลตฟอร์ม 64 บิต และเป็นส่วนหนึ่งของตระกูล BLAKE2 ที่พัฒนาโดย Jean-Philippe Aumasson, Samuel Neves, Zooko Wilcox-O'Hearn และ Christian Winnerlein\n\n**คุณลักษณะสำคัญ:**\n- **ความยาวเอาต์พุตแปรผัน**: สามารถสร้างแฮชตั้งแต่ 8 ถึง 512 บิต\n- **ประสิทธิภาพสูง**: เร็วกว่า SHA-2 และ SHA-3 ในขณะที่รักษาความปลอดภัย\n- **กำหนดได้**: อินพุตเดียวกันจะสร้างแฮชเดียวกันเสมอ\n- **เอฟเฟกต์หิมะถล่ม**: การเปลี่ยนแปลงเล็กน้อยในอินพุตจะสร้างเอาต์พุตที่แตกต่างอย่างมาก\n- **ไม่สามารถย้อนกลับได้**: ไม่สามารถคำนวณเพื่อย้อนกลับแฮชเพื่อหาอินพุตต้นฉบับได้\n- **ต้านทานการชน**: หาอินพุตสองตัวที่แตกต่างกันแต่สร้างแฮชเดียวกันได้ยากมาก\n- **แฮชแบบมีคีย์**: รองรับการป้อนคีย์เสริมสำหรับฟังก์ชัน MAC\n\n**การใช้งานทั่วไป:**\n- การตรวจสอบความสมบูรณ์ของไฟล์\n- ลายเซ็นดิจิทัลและใบรับรอง\n- การจัดเก็บและการรับรองรหัสผ่าน\n- แอปพลิเคชันบล็อกเชนและสกุลเงินดิจิทัล\n- แอปพลิเคชันประสิทธิภาพสูงที่ต้องการแฮชที่เร็ว\n- โปรโตคอลและระบบเข้ารหัส"
  },
  "id": {
    "what-is-blake2b": "Apa itu BLAKE2b?",
    "what-is-blake2b-description-markdown": "BLAKE2b adalah fungsi hash kriptografi yang lebih cepat dari MD5, SHA-1, SHA-2, dan SHA-3, namun setidaknya sama amannya dengan standar terbaru SHA-3. Ini menghasilkan output hash dengan panjang variabel dari 8 hingga 512 bit (1 hingga 64 byte). BLAKE2b dioptimalkan untuk platform 64-bit dan merupakan bagian dari keluarga BLAKE2 yang dikembangkan oleh Jean-Philippe Aumasson, Samuel Neves, Zooko Wilcox-O'Hearn, dan Christian Winnerlein.\n\n**Karakteristik utama:**\n- **Panjang output variabel**: Dapat menghasilkan hash dari 8 hingga 512 bit\n- **Performa tinggi**: Lebih cepat dari SHA-2 dan SHA-3 sambil mempertahankan keamanan\n- **Deterministik**: Input yang sama selalu menghasilkan hash yang sama\n- **Efek longsor**: Perubahan kecil pada input menghasilkan output yang sangat berbeda\n- **Tidak dapat dibalik**: Secara komputasi tidak mungkin membalik hash untuk menemukan input asli\n- **Tahan collision**: Sangat sulit menemukan dua input berbeda yang menghasilkan hash yang sama\n- **Hash berkunci**: Mendukung input kunci opsional untuk fungsionalitas MAC\n\n**Penggunaan umum:**\n- Verifikasi integritas file\n- Tanda tangan digital dan sertifikat\n- Penyimpanan dan otentikasi kata sandi\n- Aplikasi blockchain dan cryptocurrency\n- Aplikasi performa tinggi yang membutuhkan hashing cepat\n- Protokol dan sistem kriptografi"
  },
  "he": {
    "what-is-blake2b": "מה זה BLAKE2b?",
    "what-is-blake2b-description-markdown": "BLAKE2b הוא פונקציית האש קריפטוגרפית שמהירה יותר מ-MD5, SHA-1, SHA-2 ו-SHA-3, אך בטוחה לפחות כמו התקן החדש ביותר SHA-3. הוא מייצר פלטי האש באורך משתנה מ-8 עד 512 ביט (1 עד 64 בייט). BLAKE2b מיועד לפלטפורמות 64-ביט והוא חלק ממשפחת BLAKE2 שפותחה על ידי Jean-Philippe Aumasson, Samuel Neves, Zooko Wilcox-O'Hearn ו-Christian Winnerlein.\n\n**מאפיינים עיקריים:**\n- **אורך פלט משתנה**: יכול לייצר האשים מ-8 עד 512 ביט\n- **ביצועים גבוהים**: מהיר יותר מ-SHA-2 ו-SHA-3 תוך שמירה על הבטחון\n- **דטרמיניסטי**: אותו קלט תמיד מייצר אותו האש\n- **אפקט מפולת**: שינויים קטנים בקלט מייצרים פלטים שונים בתכלית\n- **בלתי הפיך**: בלתי אפשרי חישובית להפוך את ההאש כדי למצוא את הקלט המקורי\n- **עמיד להתנגשויות**: קשה מאוד למצוא שני קלטים שונים המייצרים אותו האש\n- **האש עם מפתח**: תומך בקלט מפתח אופציונלי לפונקציונליות MAC\n\n**שימושים נפוצים:**\n- אימות תקינות קבצים\n- חתימות דיגיטליות ותעודות\n- אחסון ואימות סיסמאות\n- יישומי בלוקצ'יין ומטבעות קריפטו\n- יישומי ביצועים גבוהים הדורשים האש מהיר\n- פרוטוקולים ומערכות קריפטוגרפיות"
  },
  "ms": {
    "what-is-blake2b": "Apakah BLAKE2b?",
    "what-is-blake2b-description-markdown": "BLAKE2b adalah fungsi hash kriptografi yang lebih pantas daripada MD5, SHA-1, SHA-2, dan SHA-3, namun sekurang-kurangnya sama selamat dengan standard terkini SHA-3. Ia menghasilkan output hash dengan panjang berubah-ubah dari 8 hingga 512 bit (1 hingga 64 bait). BLAKE2b dioptimumkan untuk platform 64-bit dan merupakan sebahagian daripada keluarga BLAKE2 yang dibangunkan oleh Jean-Philippe Aumasson, Samuel Neves, Zooko Wilcox-O'Hearn, dan Christian Winnerlein.\n\n**Ciri-ciri utama:**\n- **Panjang output berubah-ubah**: Boleh menghasilkan hash dari 8 hingga 512 bit\n- **Prestasi tinggi**: Lebih pantas daripada SHA-2 dan SHA-3 sambil mengekalkan keselamatan\n- **Deterministik**: Input yang sama sentiasa menghasilkan hash yang sama\n- **Kesan runtuhan salji**: Perubahan kecil dalam input menghasilkan output yang sangat berbeza\n- **Tidak boleh dibalik**: Mustahil secara pengiraan untuk membalikkan hash untuk mencari input asal\n- **Tahan perlanggaran**: Sangat sukar untuk mencari dua input berbeza yang menghasilkan hash yang sama\n- **Hash berkunci**: Menyokong input kunci pilihan untuk fungsi MAC\n\n**Kegunaan biasa:**\n- Pengesahan integriti fail\n- Tandatangan digital dan sijil\n- Penyimpanan dan pengesahan kata laluan\n- Aplikasi blockchain dan mata wang kripto\n- Aplikasi prestasi tinggi yang memerlukan hash pantas\n- Protokol dan sistem kriptografi"
  },
  "no": {
    "what-is-blake2b": "Hva er BLAKE2b?",
    "what-is-blake2b-description-markdown": "BLAKE2b er en kryptografisk hash-funksjon som er raskere enn MD5, SHA-1, SHA-2 og SHA-3, men likevel minst like sikker som den nyeste standarden SHA-3. Den produserer hash-utdata med variabel lengde fra 8 til 512 bits (1 til 64 bytes). BLAKE2b er optimalisert for 64-bits plattformer og er en del av BLAKE2-familien utviklet av Jean-Philippe Aumasson, Samuel Neves, Zooko Wilcox-O'Hearn og Christian Winnerlein.\n\n**Nøkkelegenskaper:**\n- **Variabel utdatalengde**: Kan produsere hashes fra 8 til 512 bits\n- **Høy ytelse**: Raskere enn SHA-2 og SHA-3 mens sikkerhet opprettholdes\n- **Deterministisk**: Samme inndata produserer alltid samme hash\n- **Snøskredeffekt**: Små endringer i inndata produserer drastisk forskjellige utdata\n- **Irreversibel**: Beregningsmessig umulig å reversere hashen for å finne opprinnelig inndata\n- **Kollisjonsresistent**: Svært vanskelig å finne to forskjellige inndata som produserer samme hash\n- **Nøklet hashing**: Støtter valgfri nøkkelinndata for MAC-funksjonalitet\n\n**Vanlige bruksområder:**\n- Filintegritetsverifisering\n- Digitale signaturer og sertifikater\n- Passordlagring og autentisering\n- Blokkjede og kryptovaluta-applikasjoner\n- Høyytelses-applikasjoner som krever rask hashing\n- Kryptografiske protokoller og systemer"
  }
}
</i18n>
