<template>
  <ToolSectionHeader>
    {{ t('title') }}
  </ToolSectionHeader>
  <ToolSection>
    <i18n-t keypath="description">
      <template #uuid>
        <n-text code>9073926b-929f-31c2-abc9-fad77ae3e8eb</n-text>
      </template>
      <template #dnsuuid>
        <n-text code>6ba7b810-9dad-11d1-80b4-00c04fd430c8</n-text>
      </template>
      <template #name>
        <n-text code>example.com</n-text>
      </template>
    </i18n-t>
  </ToolSection>
</template>

<script setup lang="ts">
import { NText } from 'naive-ui'
import { useI18n } from 'vue-i18n'
import { ToolSectionHeader, ToolSection } from '@shared/ui/tool'

const { t } = useI18n()
</script>

<i18n lang="json">
{
  "en": {
    "title": "What is UUID v3?",
    "description": "UUID v3 is a 128-bit universally unique identifier generated by hashing a namespace UUID and a name using the MD5 algorithm. It is deterministic, meaning the same namespace and name will always produce the same UUID, making it useful for creating consistent identifiers for things like URLs, file paths, or usernames. The UUID is formatted as a 36-character string, with the 13th character always being \"3\" to indicate version 3 and the 17th character representing the variant. For example, using the DNS namespace UUID {dnsuuid} and the name {name}, the generated UUID v3 is {uuid}."
  },
  "zh": {
    "title": "什么是 UUID v3？",
    "description": "UUID v3 是一个通过使用 MD5 算法对命名空间 UUID 和名称进行哈希处理而生成的 128 位通用唯一标识符。它是确定性的，意味着相同的命名空间和名称将始终产生相同的 UUID，这使得它对于创建 URL、文件路径或用户名等的一致标识符非常有用。UUID 格式为 36 个字符的字符串，第 13 个字符始终为 \"3\" 表示版本 3，第 17 个字符表示变体。例如，使用 DNS 命名空间 UUID {dnsuuid} 和名称 {name}，生成的 UUID v3 是 {uuid}。"
  },
  "zh-CN": {
    "title": "什么是 UUID v3？",
    "description": "UUID v3 是一个通过使用 MD5 算法对命名空间 UUID 和名称进行哈希处理而生成的 128 位通用唯一标识符。它是确定性的，意味着相同的命名空间和名称将始终产生相同的 UUID，这使得它对于创建 URL、文件路径或用户名等的一致标识符非常有用。UUID 格式为 36 个字符的字符串，第 13 个字符始终为 \"3\" 表示版本 3，第 17 个字符表示变体。例如，使用 DNS 命名空间 UUID {dnsuuid} 和名称 {name}，生成的 UUID v3 是 {uuid}。"
  },
  "zh-TW": {
    "title": "什麼是 UUID v3？",
    "description": "UUID v3 是一個通過使用 MD5 演算法對命名空間 UUID 和名稱進行雜湊處理而生成的 128 位通用唯一識別碼。它是確定性的，意味著相同的命名空間和名稱將始終產生相同的 UUID，這使得它對於創建 URL、檔案路徑或用戶名等的一致識別碼非常有用。UUID 格式為 36 個字元的字串，第 13 個字元始終為 \"3\" 表示版本 3，第 17 個字元表示變體。例如，使用 DNS 命名空間 UUID {dnsuuid} 和名稱 {name}，生成的 UUID v3 是 {uuid}。"
  },
  "zh-HK": {
    "title": "什麼是 UUID v3？",
    "description": "UUID v3 是一個通過使用 MD5 演算法對命名空間 UUID 和名稱進行雜湊處理而生成的 128 位通用唯一識別碼。它是確定性的，意味著相同的命名空間和名稱將始終產生相同的 UUID，這使得它對於創建 URL、檔案路徑或用戶名等的一致識別碼非常有用。UUID 格式為 36 個字元的字串，第 13 個字元始終為 \"3\" 表示版本 3，第 17 個字元表示變體。例如，使用 DNS 命名空間 UUID {dnsuuid} 和名稱 {name}，生成的 UUID v3 是 {uuid}。"
  },
  "es": {
    "title": "¿Qué es UUID v3?",
    "description": "UUID v3 es un identificador único universal de 128 bits generado mediante el hash de un UUID de espacio de nombres y un nombre utilizando el algoritmo MD5. Es determinista, lo que significa que el mismo espacio de nombres y nombre siempre producirá el mismo UUID, lo que lo hace útil para crear identificadores consistentes para cosas como URLs, rutas de archivos o nombres de usuario. El UUID se formatea como una cadena de 36 caracteres, con el carácter 13 siempre siendo \"3\" para indicar la versión 3 y el carácter 17 representando la variante. Por ejemplo, usando el UUID de espacio de nombres DNS {dnsuuid} y el nombre {name}, el UUID v3 generado es {uuid}."
  },
  "fr": {
    "title": "Qu'est-ce que l'UUID v3 ?",
    "description": "L'UUID v3 est un identifiant unique universel de 128 bits généré en hachant un UUID d'espace de noms et un nom à l'aide de l'algorithme MD5. Il est déterministe, ce qui signifie que le même espace de noms et le même nom produiront toujours le même UUID, ce qui le rend utile pour créer des identifiants cohérents pour des éléments tels que les URL, les chemins de fichiers ou les noms d'utilisateur. L'UUID est formaté comme une chaîne de 36 caractères, le 13e caractère étant toujours \"3\" pour indiquer la version 3 et le 17e caractère représentant la variante. Par exemple, en utilisant l'UUID d'espace de noms DNS {dnsuuid} et le nom {name}, l'UUID v3 généré est {uuid}."
  },
  "de": {
    "title": "Was ist UUID v3?",
    "description": "UUID v3 ist ein 128-Bit universell eindeutiger Bezeichner, der durch Hashing einer Namensraum-UUID und eines Namens mit dem MD5-Algorithmus generiert wird. Er ist deterministisch, was bedeutet, dass derselbe Namensraum und Name immer dieselbe UUID erzeugen, was ihn nützlich für die Erstellung konsistenter Bezeichner für Dinge wie URLs, Dateipfade oder Benutzernamen macht. Die UUID wird als 36-Zeichen-String formatiert, wobei das 13. Zeichen immer \"3\" ist, um Version 3 anzuzeigen, und das 17. Zeichen die Variante darstellt. Zum Beispiel ergibt sich mit der DNS-Namensraum-UUID {dnsuuid} und dem Namen {name} die generierte UUID v3 {uuid}."
  },
  "it": {
    "title": "Cos'è UUID v3?",
    "description": "UUID v3 è un identificatore univoco universale a 128 bit generato mediante l'hashing di un UUID dello spazio dei nomi e di un nome utilizzando l'algoritmo MD5. È deterministico, il che significa che lo stesso spazio dei nomi e lo stesso nome produrranno sempre lo stesso UUID, rendendolo utile per creare identificatori coerenti per elementi come URL, percorsi di file o nomi utente. L'UUID è formattato come una stringa di 36 caratteri, con il 13° carattere sempre \"3\" per indicare la versione 3 e il 17° carattere che rappresenta la variante. Ad esempio, utilizzando l'UUID dello spazio dei nomi DNS {dnsuuid} e il nome {name}, l'UUID v3 generato è {uuid}."
  },
  "ja": {
    "title": "UUID v3とは？",
    "description": "UUID v3は、MD5アルゴリズムを使用して名前空間UUIDと名前をハッシュ化することによって生成される128ビットの汎用一意識別子です。これは決定論的であり、同じ名前空間と名前は常に同じUUIDを生成するため、URL、ファイルパス、ユーザー名などの一貫した識別子を作成するのに役立ちます。UUIDは36文字の文字列としてフォーマットされ、13番目の文字は常に\"3\"でバージョン3を示し、17番目の文字はバリアントを表します。例えば、DNS名前空間UUID {dnsuuid}と名前 {name}を使用すると、生成されるUUID v3は {uuid}です。"
  },
  "ko": {
    "title": "UUID v3란?",
    "description": "UUID v3는 MD5 알고리즘을 사용하여 네임스페이스 UUID와 이름을 해시하여 생성되는 128비트 범용 고유 식별자입니다. 이는 결정적이므로 동일한 네임스페이스와 이름은 항상 동일한 UUID를 생성하며, URL, 파일 경로 또는 사용자 이름과 같은 일관된 식별자를 만드는 데 유용합니다. UUID는 36자 문자열로 형식화되며, 13번째 문자는 항상 \"3\"으로 버전 3을 나타내고 17번째 문자는 변형을 나타냅니다. 예를 들어, DNS 네임스페이스 UUID {dnsuuid}와 이름 {name}을 사용하면 생성된 UUID v3는 {uuid}입니다."
  },
  "ru": {
    "title": "Что такое UUID v3?",
    "description": "UUID v3 - это 128-битный универсальный уникальный идентификатор, генерируемый с использованием комбинации текущей временной метки, последовательности часов и MAC-адреса устройства. Он обычно представляется в виде 36-символьной строки в формате {uuid}, где \"1\" указывает на версию 1. Компонент временной метки обеспечивает временную упорядоченность UUID, в то время как MAC-адрес и последовательность часов помогают предотвращать коллизии даже между разными машинами. Поскольку UUID v1 кодирует как временную, так и аппаратную информацию, он обеспечивает сильные гарантии уникальности, но также вызывает проблемы с конфиденциальностью, так как может потенциально раскрыть точное время и происхождение генерации. Он обычно используется в устаревших системах или приложениях, требующих сортировки по времени, хотя UUID v4 обычно предпочтительнее в современном программном обеспечении из-за его простоты и лучшей конфиденциальности."
  },
  "pt": {
    "title": "O que é UUID v3?",
    "description": "UUID v3 é um identificador único universal de 128 bits gerado usando uma combinação do timestamp atual, uma sequência de relógio e o endereço MAC do dispositivo. É tipicamente representado como uma string de 36 caracteres no formato {uuid}, onde o \"1\" indica a versão 1. O componente timestamp garante que os UUIDs sejam ordenados temporalmente, enquanto o endereço MAC e a sequência de relógio ajudam a prevenir colisões mesmo entre diferentes máquinas. Como o UUID v1 codifica tanto informações temporais quanto de hardware, ele fornece fortes garantias de unicidade, mas também levanta preocupações de privacidade, pois pode potencialmente expor o tempo exato e a origem da geração. É comumente usado em sistemas legados ou aplicações que requerem ordenação baseada em tempo, embora o UUID v4 seja geralmente preferido em software moderno por sua simplicidade e melhor privacidade."
  },
  "ar": {
    "title": "ما هو UUID v3؟",
    "description": "UUID v3 هو معرف فريد عالمي 128 بت يتم إنشاؤه عن طريق تجزئة UUID مساحة الاسم واسم باستخدام خوارزمية MD5. إنه حتمي، مما يعني أن نفس مساحة الاسم والاسم سيؤديان دائمًا إلى نفس UUID، مما يجعله مفيدًا لإنشاء معرفات متسقة لأشياء مثل عناوين URL أو مسارات الملفات أو أسماء المستخدمين. يتم تنسيق UUID كسلسلة من 36 حرفًا، حيث يكون الحرف الثالث عشر دائمًا \"3\" للإشارة إلى الإصدار 3 والحرف السابع عشر يمثل المتغير. على سبيل المثال، باستخدام UUID مساحة اسم DNS {dnsuuid} والاسم {name}، فإن UUID v3 المُنشأ هو {uuid}."
  },
  "hi": {
    "title": "UUID v3 क्या है?",
    "description": "UUID v3 एक 128-बिट सार्वभौमिक विशिष्ट पहचानकर्ता है जो MD5 एल्गोरिथम का उपयोग करके नेमस्पेस UUID और नाम को हैश करके उत्पन्न किया जाता है। यह निर्धारक है, जिसका अर्थ है कि एक ही नेमस्पेस और नाम हमेशा एक ही UUID उत्पन्न करेगा, जो इसे URL, फ़ाइल पथ या उपयोगकर्ता नाम जैसी चीज़ों के लिए सुसंगत पहचानकर्ता बनाने के लिए उपयोगी बनाता है। UUID को 36-वर्ण स्ट्रिंग के रूप में स्वरूपित किया जाता है, जिसमें 13वां वर्ण हमेशा \"3\" होता है जो संस्करण 3 को इंगित करता है और 17वां वर्ण वेरिएंट का प्रतिनिधित्व करता है। उदाहरण के लिए, DNS नेमस्पेस UUID {dnsuuid} और नाम {name} का उपयोग करके, उत्पन्न UUID v3 {uuid} है।"
  },
  "tr": {
    "title": "UUID v3 nedir?",
    "description": "UUID v3, MD5 algoritması kullanılarak bir ad alanı UUID'si ve bir adın hash'lenmesiyle oluşturulan 128-bit evrensel benzersiz tanımlayıcıdır. Belirleyicidir, yani aynı ad alanı ve ad her zaman aynı UUID'yi üretecektir, bu da onu URL'ler, dosya yolları veya kullanıcı adları gibi şeyler için tutarlı tanımlayıcılar oluşturmada kullanışlı kılar. UUID, 36 karakterlik bir dize olarak biçimlendirilir, 13. karakter her zaman \"3\" olarak sürüm 3'ü belirtir ve 17. karakter varyantı temsil eder. Örneğin, DNS ad alanı UUID'si {dnsuuid} ve ad {name} kullanılarak, oluşturulan UUID v3 {uuid}'dir."
  },
  "nl": {
    "title": "Wat is UUID v3?",
    "description": "UUID v3 is een 128-bits universeel unieke identifier die wordt gegenereerd door een naamruimte-UUID en een naam te hashen met het MD5-algoritme. Het is deterministisch, wat betekent dat dezelfde naamruimte en naam altijd dezelfde UUID zullen produceren, wat het nuttig maakt voor het creëren van consistente identifiers voor zaken als URL's, bestandspaden of gebruikersnamen. De UUID wordt geformatteerd als een 36-tekens string, waarbij het 13e teken altijd \"3\" is om versie 3 aan te duiden en het 17e teken de variant vertegenwoordigt. Bijvoorbeeld, met de DNS-naamruimte UUID {dnsuuid} en de naam {name}, is de gegenereerde UUID v3 {uuid}."
  },
  "sv": {
    "title": "Vad är UUID v3?",
    "description": "UUID v3 är en 128-bitars universellt unik identifierare som genereras genom att hasha en namnrymds-UUID och ett namn med MD5-algoritmen. Den är deterministisk, vilket betyder att samma namnrymd och namn alltid kommer att producera samma UUID, vilket gör den användbar för att skapa konsekventa identifierare för saker som URL:er, filsökvägar eller användarnamn. UUID:n formateras som en 36-tecken sträng, där det 13:e tecknet alltid är \"3\" för att indikera version 3 och det 17:e tecknet representerar varianten. Till exempel, med DNS-namnrymds-UUID {dnsuuid} och namnet {name}, är den genererade UUID v3 {uuid}."
  },
  "pl": {
    "title": "Co to jest UUID v3?",
    "description": "UUID v3 to 128-bitowy uniwersalny unikalny identyfikator generowany przez haszowanie UUID przestrzeni nazw i nazwy przy użyciu algorytmu MD5. Jest deterministyczny, co oznacza, że ta sama przestrzeń nazw i nazwa zawsze wyprodukują ten sam UUID, co czyni go przydatnym do tworzenia spójnych identyfikatorów dla rzeczy takich jak URL-e, ścieżki plików lub nazwy użytkowników. UUID jest formatowany jako 36-znakowy ciąg, gdzie 13. znak to zawsze \"3\" oznaczający wersję 3, a 17. znak reprezentuje wariant. Na przykład, używając UUID przestrzeni nazw DNS {dnsuuid} i nazwy {name}, wygenerowany UUID v3 to {uuid}."
  },
  "vi": {
    "title": "UUID v3 là gì?",
    "description": "UUID v3 là một định danh duy nhất phổ quát 128-bit được tạo bằng cách băm UUID không gian tên và tên bằng thuật toán MD5. Nó là xác định, có nghĩa là cùng một không gian tên và tên sẽ luôn tạo ra cùng một UUID, làm cho nó hữu ích để tạo các định danh nhất quán cho những thứ như URL, đường dẫn tệp hoặc tên người dùng. UUID được định dạng dưới dạng chuỗi 36 ký tự, với ký tự thứ 13 luôn là \"3\" để chỉ phiên bản 3 và ký tự thứ 17 đại diện cho biến thể. Ví dụ, sử dụng UUID không gian tên DNS {dnsuuid} và tên {name}, UUID v3 được tạo là {uuid}."
  },
  "th": {
    "title": "UUID v3 คืออะไร?",
    "description": "UUID v3 เป็นตัวระบุเฉพาะสากล 128 บิตที่สร้างขึ้นโดยการแฮช UUID namespace และชื่อโดยใช้อัลกอริทึม MD5 มันเป็นแบบกำหนดได้ หมายความว่า namespace และชื่อเดียวกันจะสร้าง UUID เดียวกันเสมอ ทำให้มีประโยชน์สำหรับการสร้างตัวระบุที่สอดคล้องกันสำหรับสิ่งต่างๆ เช่น URL เส้นทางไฟล์ หรือชื่อผู้ใช้ UUID มีรูปแบบเป็นสตริง 36 ตัวอักษร โดยตัวอักษรที่ 13 จะเป็น \"3\" เสมอเพื่อระบุเวอร์ชัน 3 และตัวอักษรที่ 17 แทนตัวแปร ตัวอย่างเช่น การใช้ UUID namespace ของ DNS {dnsuuid} และชื่อ {name} UUID v3 ที่สร้างขึ้นคือ {uuid}"
  },
  "id": {
    "title": "Apa itu UUID v3?",
    "description": "UUID v3 adalah pengidentifikasi unik universal 128-bit yang dihasilkan dengan menghash UUID namespace dan nama menggunakan algoritma MD5. Ini bersifat deterministik, artinya namespace dan nama yang sama akan selalu menghasilkan UUID yang sama, membuatnya berguna untuk membuat pengidentifikasi yang konsisten untuk hal-hal seperti URL, jalur file, atau nama pengguna. UUID diformat sebagai string 36 karakter, dengan karakter ke-13 selalu \"3\" untuk menunjukkan versi 3 dan karakter ke-17 mewakili varian. Misalnya, menggunakan UUID namespace DNS {dnsuuid} dan nama {name}, UUID v3 yang dihasilkan adalah {uuid}."
  },
  "he": {
    "title": "?UUID v3 מהו",
    "description": "UUID v3 הוא מזהה ייחודי אוניברסלי 128-ביט שנוצר על ידי גיבוב UUID מרחב שמות ושם באמצעות אלגוריתם MD5. הוא דטרמיניסטי, כלומר אותו מרחב שמות ושם תמיד יפיקו את אותו UUID, מה שהופך אותו לשימושי ליצירת מזהים עקביים עבור דברים כמו כתובות URL, נתיבי קבצים או שמות משתמש. ה-UUID מעוצב כמחרוזת של 36 תווים, כאשר התו ה-13 הוא תמיד \"3\" לציון גרסה 3 והתו ה-17 מייצג את הווריאנט. למשל, באמצעות UUID מרחב השמות של DNS {dnsuuid} והשם {name}, ה-UUID v3 שנוצר הוא {uuid}."
  },
  "ms": {
    "title": "Apakah UUID v3?",
    "description": "UUID v3 ialah pengenalan unik sejagat 128-bit yang dijana dengan menghash UUID ruang nama dan nama menggunakan algoritma MD5. Ia adalah deterministik, bermakna ruang nama dan nama yang sama akan sentiasa menghasilkan UUID yang sama, menjadikannya berguna untuk mencipta pengenalan yang konsisten untuk perkara seperti URL, laluan fail atau nama pengguna. UUID diformat sebagai rentetan 36 aksara, dengan aksara ke-13 sentiasa \"3\" untuk menunjukkan versi 3 dan aksara ke-17 mewakili varian. Sebagai contoh, menggunakan UUID ruang nama DNS {dnsuuid} dan nama {name}, UUID v3 yang dijana ialah {uuid}."
  },
  "no": {
    "title": "Hva er UUID v3?",
    "description": "UUID v3 er en 128-bit universelt unik identifikator som genereres ved å hashe en navnerom-UUID og et navn ved hjelp av MD5-algoritmen. Den er deterministisk, noe som betyr at samme navnerom og navn alltid vil produsere samme UUID, noe som gjør den nyttig for å lage konsistente identifikatorer for ting som URL-er, filstier eller brukernavn. UUID-en er formatert som en 36-tegns streng, der det 13. tegnet alltid er \"3\" for å indikere versjon 3 og det 17. tegnet representerer varianten. For eksempel, med DNS-navnerom UUID {dnsuuid} og navnet {name}, er den genererte UUID v3 {uuid}."
  }
}
</i18n>
