<template>
  <DescriptionMarkdown
    :title="t('what-is-ripemd160')"
    :description="t('what-is-ripemd160-description-markdown')"
  />
</template>

<script setup lang="ts">
import { DescriptionMarkdown } from '@shared/ui/base'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()
</script>

<i18n lang="json">
{
  "en": {
    "what-is-ripemd160": "What is RIPEMD-160?",
    "what-is-ripemd160-description-markdown": "RIPEMD-160 (RACE Integrity Primitives Evaluation Message Digest) is a cryptographic hash function that produces a 160-bit (20-byte) hash value, typically rendered as a 40-character hexadecimal number. It was developed in 1996 by Hans Dobbertin, Antoon Bosselaers, and Bart Preneel as part of the European RACE project.\n\n**Key characteristics:**\n- **Deterministic**: The same input always produces the same hash\n- **Fast computation**: Reasonably fast to compute for any given input\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Fixed output size**: Always produces a 160-bit hash regardless of input size\n- **Two-line parallel structure**: Uses two parallel computation lines for enhanced security\n\n**Security status:**\n✅ **RIPEMD-160 is considered cryptographically secure** with no known practical attacks. It provides a good security margin and is still recommended for cryptographic applications where a 160-bit hash is sufficient.\n\n**Common uses:**\n- Bitcoin address generation (Base58Check encoding)\n- Digital signatures and certificates\n- Data integrity verification\n- Cryptographic protocols requiring 160-bit hashes\n- Alternative to SHA-1 where needed\n\n**Comparison with other algorithms:**\n- More secure than MD5 and SHA-1\n- Smaller output than SHA-256 (160-bit vs 256-bit)\n- Good performance characteristics\n- Well-studied and trusted in cryptographic community\n\n**Recommended for:**\n- Applications requiring 160-bit hash security\n- Bitcoin-related cryptographic operations\n- Legacy system compatibility where RIPEMD-160 is specified"
  },
  "zh": {
    "what-is-ripemd160": "什么是 RIPEMD-160？",
    "what-is-ripemd160-description-markdown": "RIPEMD-160（RACE 完整性原语评估消息摘要）是一种加密散列函数，产生 160 位（20 字节）的散列值，通常呈现为 40 个字符的十六进制数。它由 Hans Dobbertin、Antoon Bosselaers 和 Bart Preneel 于 1996 年开发，作为欧洲 RACE 项目的一部分。\n\n**主要特征：**\n- **确定性**：相同的输入总是产生相同的散列\n- **快速计算**：对于任何给定输入都能合理快速地计算\n- **雪崩效应**：输入的微小变化会产生截然不同的输出\n- **固定输出大小**：无论输入大小如何，始终产生 160 位散列\n- **双线并行结构**：使用两条并行计算线以增强安全性\n\n**安全状态：**\n✅ **RIPEMD-160 被认为是加密安全的**，没有已知的实际攻击。它提供了良好的安全边际，对于 160 位散列足够的加密应用仍被推荐。\n\n**常见用途：**\n- 比特币地址生成（Base58Check 编码）\n- 数字签名和证书\n- 数据完整性验证\n- 需要 160 位散列的加密协议\n- 需要时作为 SHA-1 的替代品\n\n**与其他算法的比较：**\n- 比 MD5 和 SHA-1 更安全\n- 输出比 SHA-256 小（160 位 vs 256 位）\n- 良好的性能特征\n- 在加密社区中经过充分研究和信任\n\n**推荐用于：**\n- 需要 160 位散列安全性的应用\n- 比特币相关的加密操作\n- 指定 RIPEMD-160 的遗留系统兼容性"
  },
  "zh-CN": {
    "what-is-ripemd160": "什么是 RIPEMD-160？",
    "what-is-ripemd160-description-markdown": "RIPEMD-160（RACE 完整性原语评估消息摘要）是一种加密散列函数，产生 160 位（20 字节）的散列值，通常呈现为 40 个字符的十六进制数。它由 Hans Dobbertin、Antoon Bosselaers 和 Bart Preneel 于 1996 年开发，作为欧洲 RACE 项目的一部分。\n\n**主要特征：**\n- **确定性**：相同的输入总是产生相同的散列\n- **快速计算**：对于任何给定输入都能合理快速地计算\n- **雪崩效应**：输入的微小变化会产生截然不同的输出\n- **固定输出大小**：无论输入大小如何，始终产生 160 位散列\n- **双线并行结构**：使用两条并行计算线以增强安全性\n\n**安全状态：**\n✅ **RIPEMD-160 被认为是加密安全的**，没有已知的实际攻击。它提供了良好的安全边际，对于 160 位散列足够的加密应用仍被推荐。\n\n**常见用途：**\n- 比特币地址生成（Base58Check 编码）\n- 数字签名和证书\n- 数据完整性验证\n- 需要 160 位散列的加密协议\n- 需要时作为 SHA-1 的替代品\n\n**与其他算法的比较：**\n- 比 MD5 和 SHA-1 更安全\n- 输出比 SHA-256 小（160 位 vs 256 位）\n- 良好的性能特征\n- 在加密社区中经过充分研究和信任\n\n**推荐用于：**\n- 需要 160 位散列安全性的应用\n- 比特币相关的加密操作\n- 指定 RIPEMD-160 的遗留系统兼容性"
  },
  "zh-TW": {
    "what-is-ripemd160": "什麼是 RIPEMD-160？",
    "what-is-ripemd160-description-markdown": "RIPEMD-160（RACE 完整性原語評估訊息摘要）是一種加密雜湊函數，產生 160 位元（20 位元組）的雜湊值，通常呈現為 40 個字元的十六進位數。它由 Hans Dobbertin、Antoon Bosselaers 和 Bart Preneel 於 1996 年開發，作為歐洲 RACE 專案的一部分。\n\n**主要特徵：**\n- **確定性**：相同的輸入總是產生相同的雜湊\n- **快速計算**：對於任何給定輸入都能合理快速地計算\n- **雪崩效應**：輸入的微小變化會產生截然不同的輸出\n- **固定輸出大小**：無論輸入大小如何，始終產生 160 位元雜湊\n- **雙線並行結構**：使用兩條並行計算線以增強安全性\n\n**安全狀態：**\n✅ **RIPEMD-160 被認為是加密安全的**，沒有已知的實際攻擊。它提供了良好的安全邊際，對於 160 位元雜湊足夠的加密應用仍被推薦。\n\n**常見用途：**\n- 比特幣地址生成（Base58Check 編碼）\n- 數位簽章和憑證\n- 資料完整性驗證\n- 需要 160 位元雜湊的加密協定\n- 需要時作為 SHA-1 的替代品\n\n**與其他演算法的比較：**\n- 比 MD5 和 SHA-1 更安全\n- 輸出比 SHA-256 小（160 位元 vs 256 位元）\n- 良好的效能特徵\n- 在加密社群中經過充分研究和信任\n\n**推薦用於：**\n- 需要 160 位元雜湊安全性的應用\n- 比特幣相關的加密操作\n- 指定 RIPEMD-160 的遺留系統相容性"
  },
  "zh-HK": {
    "what-is-ripemd160": "什麼是 RIPEMD-160？",
    "what-is-ripemd160-description-markdown": "RIPEMD-160（RACE 完整性原語評估訊息摘要）是一種加密雜湊函數，產生 160 位元（20 位元組）的雜湊值，通常呈現為 40 個字元的十六進位數。它由 Hans Dobbertin、Antoon Bosselaers 和 Bart Preneel 於 1996 年開發，作為歐洲 RACE 專案的一部分。\n\n**主要特徵：**\n- **確定性**：相同的輸入總是產生相同的雜湊\n- **快速計算**：對於任何給定輸入都能合理快速地計算\n- **雪崩效應**：輸入的微小變化會產生截然不同的輸出\n- **固定輸出大小**：無論輸入大小如何，始終產生 160 位元雜湊\n- **雙線並行結構**：使用兩條並行計算線以增強安全性\n\n**安全狀態：**\n✅ **RIPEMD-160 被認為是加密安全的**，沒有已知的實際攻擊。它提供了良好的安全邊際，對於 160 位元雜湊足夠的加密應用仍被推薦。\n\n**常見用途：**\n- 比特幣地址生成（Base58Check 編碼）\n- 數位簽章和憑證\n- 資料完整性驗證\n- 需要 160 位元雜湊的加密協定\n- 需要時作為 SHA-1 的替代品\n\n**與其他演算法的比較：**\n- 比 MD5 和 SHA-1 更安全\n- 輸出比 SHA-256 小（160 位元 vs 256 位元）\n- 良好的效能特徵\n- 在加密社群中經過充分研究和信任\n\n**推薦用於：**\n- 需要 160 位元雜湊安全性的應用\n- 比特幣相關的加密操作\n- 指定 RIPEMD-160 的遺留系統相容性"
  },
  "es": {
    "what-is-ripemd160": "¿Qué es RIPEMD-160?",
    "what-is-ripemd160-description-markdown": "RIPEMD-160 (RACE Integrity Primitives Evaluation Message Digest) es una función hash criptográfica que produce un valor hash de 160 bits (20 bytes), típicamente representado como un número hexadecimal de 40 caracteres. Fue desarrollado en 1996 por Hans Dobbertin, Antoon Bosselaers y Bart Preneel como parte del proyecto europeo RACE.\n\n**Características clave:**\n- **Determinístico**: La misma entrada siempre produce el mismo hash\n- **Computación rápida**: Razonablemente rápido de calcular para cualquier entrada dada\n- **Efecto avalancha**: Pequeños cambios en la entrada producen salidas drásticamente diferentes\n- **Tamaño de salida fijo**: Siempre produce un hash de 160 bits independientemente del tamaño de entrada\n- **Estructura paralela de dos líneas**: Usa dos líneas de computación paralelas para seguridad mejorada\n\n**Estado de seguridad:**\n✅ **RIPEMD-160 se considera criptográficamente seguro** sin ataques prácticos conocidos. Proporciona un buen margen de seguridad y sigue siendo recomendado para aplicaciones criptográficas donde un hash de 160 bits es suficiente.\n\n**Usos comunes:**\n- Generación de direcciones Bitcoin (codificación Base58Check)\n- Firmas digitales y certificados\n- Verificación de integridad de datos\n- Protocolos criptográficos que requieren hashes de 160 bits\n- Alternativa a SHA-1 cuando sea necesario\n\n**Comparación con otros algoritmos:**\n- Más seguro que MD5 y SHA-1\n- Salida más pequeña que SHA-256 (160 bits vs 256 bits)\n- Buenas características de rendimiento\n- Bien estudiado y confiable en la comunidad criptográfica\n\n**Recomendado para:**\n- Aplicaciones que requieren seguridad de hash de 160 bits\n- Operaciones criptográficas relacionadas con Bitcoin\n- Compatibilidad con sistemas heredados donde se especifica RIPEMD-160"
  },
  "fr": {
    "what-is-ripemd160": "Qu'est-ce que RIPEMD-160 ?",
    "what-is-ripemd160-description-markdown": "RIPEMD-160 (RACE Integrity Primitives Evaluation Message Digest) est une fonction de hachage cryptographique qui produit une valeur de hachage de 160 bits (20 octets), généralement rendue sous forme d'un nombre hexadécimal de 40 caractères. Il a été développé en 1996 par Hans Dobbertin, Antoon Bosselaers et Bart Preneel dans le cadre du projet européen RACE.\n\n**Caractéristiques clés :**\n- **Déterministe** : La même entrée produit toujours le même hachage\n- **Calcul rapide** : Raisonnablement rapide à calculer pour toute entrée donnée\n- **Effet d'avalanche** : De petits changements dans l'entrée produisent des sorties drastiquement différentes\n- **Taille de sortie fixe** : Produit toujours un hachage de 160 bits quelle que soit la taille d'entrée\n- **Structure parallèle à deux lignes** : Utilise deux lignes de calcul parallèles pour une sécurité renforcée\n\n**État de sécurité :**\n✅ **RIPEMD-160 est considéré comme cryptographiquement sûr** sans attaques pratiques connues. Il fournit une bonne marge de sécurité et est toujours recommandé pour les applications cryptographiques où un hachage de 160 bits est suffisant.\n\n**Utilisations courantes :**\n- Génération d'adresses Bitcoin (encodage Base58Check)\n- Signatures numériques et certificats\n- Vérification d'intégrité des données\n- Protocoles cryptographiques nécessitant des hachages de 160 bits\n- Alternative à SHA-1 en cas de besoin\n\n**Comparaison avec d'autres algorithmes :**\n- Plus sûr que MD5 et SHA-1\n- Sortie plus petite que SHA-256 (160 bits vs 256 bits)\n- Bonnes caractéristiques de performance\n- Bien étudié et approuvé dans la communauté cryptographique\n\n**Recommandé pour :**\n- Applications nécessitant une sécurité de hachage de 160 bits\n- Opérations cryptographiques liées au Bitcoin\n- Compatibilité avec les systèmes hérités où RIPEMD-160 est spécifié"
  },
  "de": {
    "what-is-ripemd160": "Was ist RIPEMD-160?",
    "what-is-ripemd160-description-markdown": "RIPEMD-160 (RACE Integrity Primitives Evaluation Message Digest) ist eine kryptographische Hash-Funktion, die einen 160-Bit (20-Byte) Hash-Wert erzeugt, der typischerweise als 40-stellige Hexadezimalzahl dargestellt wird. Es wurde 1996 von Hans Dobbertin, Antoon Bosselaers und Bart Preneel als Teil des europäischen RACE-Projekts entwickelt.\n\n**Hauptmerkmale:**\n- **Deterministisch**: Dieselbe Eingabe erzeugt immer denselben Hash\n- **Schnelle Berechnung**: Angemessen schnell zu berechnen für jede gegebene Eingabe\n- **Lawineneffekt**: Kleine Änderungen in der Eingabe erzeugen drastisch unterschiedliche Ausgaben\n- **Feste Ausgabegröße**: Erzeugt immer einen 160-Bit Hash unabhängig von der Eingabegröße\n- **Zwei-Linien-Parallelstruktur**: Verwendet zwei parallele Berechnungslinien für erhöhte Sicherheit\n\n**Sicherheitsstatus:**\n✅ **RIPEMD-160 gilt als kryptographisch sicher** ohne bekannte praktische Angriffe. Es bietet eine gute Sicherheitsmarge und wird immer noch für kryptographische Anwendungen empfohlen, wo ein 160-Bit Hash ausreichend ist.\n\n**Häufige Verwendungen:**\n- Bitcoin-Adressgenerierung (Base58Check-Kodierung)\n- Digitale Signaturen und Zertifikate\n- Datenintegritätsprüfung\n- Kryptographische Protokolle, die 160-Bit Hashes erfordern\n- Alternative zu SHA-1 bei Bedarf\n\n**Vergleich mit anderen Algorithmen:**\n- Sicherer als MD5 und SHA-1\n- Kleinere Ausgabe als SHA-256 (160-Bit vs 256-Bit)\n- Gute Leistungsmerkmale\n- Gut untersucht und vertrauenswürdig in der kryptographischen Gemeinschaft\n\n**Empfohlen für:**\n- Anwendungen, die 160-Bit Hash-Sicherheit erfordern\n- Bitcoin-bezogene kryptographische Operationen\n- Legacy-System-Kompatibilität, wo RIPEMD-160 spezifiziert ist"
  },
  "it": {
    "what-is-ripemd160": "Cos'è RIPEMD-160?",
    "what-is-ripemd160-description-markdown": "RIPEMD-160 (RACE Integrity Primitives Evaluation Message Digest) è una funzione hash crittografica che produce un valore hash di 160 bit (20 byte), tipicamente rappresentato come un numero esadecimale di 40 caratteri. È stato sviluppato nel 1996 da Hans Dobbertin, Antoon Bosselaers e Bart Preneel come parte del progetto europeo RACE.\n\n**Caratteristiche chiave:**\n- **Deterministico**: Lo stesso input produce sempre lo stesso hash\n- **Calcolo veloce**: Ragionevolmente veloce da calcolare per qualsiasi input dato\n- **Effetto valanga**: Piccoli cambiamenti nell'input producono output drasticamente diversi\n- **Dimensione output fissa**: Produce sempre un hash di 160 bit indipendentemente dalla dimensione dell'input\n- **Struttura parallela a due linee**: Usa due linee di calcolo parallele per sicurezza migliorata\n\n**Stato di sicurezza:**\n✅ **RIPEMD-160 è considerato crittograficamente sicuro** senza attacchi pratici conosciuti. Fornisce un buon margine di sicurezza ed è ancora raccomandato per applicazioni crittografiche dove un hash di 160 bit è sufficiente.\n\n**Usi comuni:**\n- Generazione di indirizzi Bitcoin (codifica Base58Check)\n- Firme digitali e certificati\n- Verifica dell'integrità dei dati\n- Protocolli crittografici che richiedono hash di 160 bit\n- Alternativa a SHA-1 quando necessario\n\n**Confronto con altri algoritmi:**\n- Più sicuro di MD5 e SHA-1\n- Output più piccolo di SHA-256 (160 bit vs 256 bit)\n- Buone caratteristiche di prestazione\n- Ben studiato e fidato nella comunità crittografica\n\n**Raccomandato per:**\n- Applicazioni che richiedono sicurezza hash di 160 bit\n- Operazioni crittografiche relative a Bitcoin\n- Compatibilità con sistemi legacy dove RIPEMD-160 è specificato"
  },
  "ja": {
    "what-is-ripemd160": "RIPEMD-160とは？",
    "what-is-ripemd160-description-markdown": "RIPEMD-160（RACE Integrity Primitives Evaluation Message Digest）は、160ビット（20バイト）のハッシュ値を生成する暗号学的ハッシュ関数で、通常40文字の16進数として表示されます。1996年にHans Dobbertin、Antoon Bosselaers、Bart Preneelによって欧州RACEプロジェクトの一部として開発されました。\n\n**主な特徴：**\n- **決定論的**：同じ入力は常に同じハッシュを生成\n- **高速計算**：任意の入力に対して合理的に高速に計算\n- **雪崩効果**：入力の小さな変化が劇的に異なる出力を生成\n- **固定出力サイズ**：入力サイズに関係なく常に160ビットハッシュを生成\n- **2ライン並列構造**：セキュリティ強化のために2つの並列計算ラインを使用\n\n**セキュリティ状況：**\n✅ **RIPEMD-160は暗号学的に安全とされています**。既知の実用的な攻撃はありません。良好なセキュリティマージンを提供し、160ビットハッシュで十分な暗号学的アプリケーションに引き続き推奨されています。\n\n**一般的な用途：**\n- ビットコインアドレス生成（Base58Checkエンコーディング）\n- デジタル署名と証明書\n- データ整合性検証\n- 160ビットハッシュを必要とする暗号プロトコル\n- 必要に応じたSHA-1の代替\n\n**他のアルゴリズムとの比較：**\n- MD5やSHA-1より安全\n- SHA-256より小さい出力（160ビット vs 256ビット）\n- 良好な性能特性\n- 暗号学コミュニティで十分に研究され信頼されている\n\n**推奨される用途：**\n- 160ビットハッシュセキュリティを必要とするアプリケーション\n- ビットコイン関連の暗号操作\n- RIPEMD-160が指定されているレガシーシステムとの互換性"
  },
  "ko": {
    "what-is-ripemd160": "RIPEMD-160이란?",
    "what-is-ripemd160-description-markdown": "RIPEMD-160(RACE Integrity Primitives Evaluation Message Digest)은 160비트(20바이트) 해시 값을 생성하는 암호화 해시 함수로, 일반적으로 40자리 16진수로 표현됩니다. 1996년 Hans Dobbertin, Antoon Bosselaers, Bart Preneel이 유럽 RACE 프로젝트의 일환으로 개발했습니다.\n\n**주요 특징:**\n- **결정론적**: 동일한 입력은 항상 동일한 해시를 생성\n- **빠른 계산**: 주어진 입력에 대해 합리적으로 빠르게 계산\n- **눈사태 효과**: 입력의 작은 변화가 완전히 다른 출력을 생성\n- **고정 출력 크기**: 입력 크기에 관계없이 항상 160비트 해시를 생성\n- **2라인 병렬 구조**: 보안 강화를 위해 두 개의 병렬 계산 라인 사용\n\n**보안 상태:**\n✅ **RIPEMD-160은 암호학적으로 안전한 것으로 간주됩니다**. 알려진 실용적인 공격이 없습니다. 좋은 보안 마진을 제공하며 160비트 해시가 충분한 암호화 애플리케이션에 여전히 권장됩니다.\n\n**일반적인 용도:**\n- 비트코인 주소 생성(Base58Check 인코딩)\n- 디지털 서명 및 인증서\n- 데이터 무결성 검증\n- 160비트 해시가 필요한 암호화 프로토콜\n- 필요할 때 SHA-1의 대안\n\n**다른 알고리즘과의 비교:**\n- MD5와 SHA-1보다 안전\n- SHA-256보다 작은 출력(160비트 vs 256비트)\n- 좋은 성능 특성\n- 암호화 커뮤니티에서 잘 연구되고 신뢰받음\n\n**권장 사용처:**\n- 160비트 해시 보안이 필요한 애플리케이션\n- 비트코인 관련 암호화 작업\n- RIPEMD-160이 지정된 레거시 시스템 호환성"
  },
  "ru": {
    "what-is-ripemd160": "Что такое RIPEMD-160?",
    "what-is-ripemd160-description-markdown": "RIPEMD-160 (RACE Integrity Primitives Evaluation Message Digest) — это криптографическая хеш-функция, которая производит 160-битное (20-байтовое) хеш-значение, обычно представляемое как 40-символьное шестнадцатеричное число. Он был разработан в 1996 году Хансом Доббертином, Антооном Босселаерсом и Бартом Пренелем как часть европейского проекта RACE.\n\n**Ключевые характеристики:**\n- **Детерминированность**: Одинаковый ввод всегда производит одинаковый хеш\n- **Быстрое вычисление**: Разумно быстро вычисляется для любого заданного ввода\n- **Эффект лавины**: Небольшие изменения во вводе производят кардинально разные выводы\n- **Фиксированный размер вывода**: Всегда производит 160-битный хеш независимо от размера ввода\n- **Двухлинейная параллельная структура**: Использует две параллельные линии вычислений для повышенной безопасности\n\n**Статус безопасности:**\n✅ **RIPEMD-160 считается криптографически безопасным** без известных практических атак. Он обеспечивает хороший запас безопасности и по-прежнему рекомендуется для криптографических приложений, где достаточно 160-битного хеша.\n\n**Обычные применения:**\n- Генерация Bitcoin-адресов (кодирование Base58Check)\n- Цифровые подписи и сертификаты\n- Проверка целостности данных\n- Криптографические протоколы, требующие 160-битные хеши\n- Альтернатива SHA-1 при необходимости\n\n**Сравнение с другими алгоритмами:**\n- Более безопасен, чем MD5 и SHA-1\n- Меньший вывод, чем SHA-256 (160 бит против 256 бит)\n- Хорошие характеристики производительности\n- Хорошо изучен и доверен в криптографическом сообществе\n\n**Рекомендуется для:**\n- Приложений, требующих 160-битную безопасность хеша\n- Криптографических операций, связанных с Bitcoin\n- Совместимости с устаревшими системами, где указан RIPEMD-160"
  },
  "pt": {
    "what-is-ripemd160": "O que é RIPEMD-160?",
    "what-is-ripemd160-description-markdown": "RIPEMD-160 (RACE Integrity Primitives Evaluation Message Digest) é uma função hash criptográfica que produz um valor hash de 160 bits (20 bytes), tipicamente representado como um número hexadecimal de 40 caracteres. Foi desenvolvido em 1996 por Hans Dobbertin, Antoon Bosselaers e Bart Preneel como parte do projeto europeu RACE.\n\n**Características principais:**\n- **Determinístico**: A mesma entrada sempre produz o mesmo hash\n- **Computação rápida**: Razoavelmente rápido de calcular para qualquer entrada dada\n- **Efeito avalanche**: Pequenas mudanças na entrada produzem saídas drasticamente diferentes\n- **Tamanho de saída fixo**: Sempre produz um hash de 160 bits independentemente do tamanho da entrada\n- **Estrutura paralela de duas linhas**: Usa duas linhas de computação paralelas para segurança aprimorada\n\n**Status de segurança:**\n✅ **RIPEMD-160 é considerado criptograficamente seguro** sem ataques práticos conhecidos. Fornece uma boa margem de segurança e ainda é recomendado para aplicações criptográficas onde um hash de 160 bits é suficiente.\n\n**Usos comuns:**\n- Geração de endereços Bitcoin (codificação Base58Check)\n- Assinaturas digitais e certificados\n- Verificação de integridade de dados\n- Protocolos criptográficos que requerem hashes de 160 bits\n- Alternativa ao SHA-1 quando necessário\n\n**Comparação com outros algoritmos:**\n- Mais seguro que MD5 e SHA-1\n- Saída menor que SHA-256 (160 bits vs 256 bits)\n- Boas características de desempenho\n- Bem estudado e confiável na comunidade criptográfica\n\n**Recomendado para:**\n- Aplicações que requerem segurança de hash de 160 bits\n- Operações criptográficas relacionadas ao Bitcoin\n- Compatibilidade com sistemas legados onde RIPEMD-160 é especificado"
  },
  "ar": {
    "what-is-ripemd160": "ما هو RIPEMD-160؟",
    "what-is-ripemd160-description-markdown": "RIPEMD-160 (RACE Integrity Primitives Evaluation Message Digest) هي دالة تشفير تنتج قيمة تشفير بحجم 160 بت (20 بايت)، وتُعرض عادة كرقم سادس عشر مكون من 40 حرفاً. تم تطويرها في 1996 من قبل Hans Dobbertin وAntoon Bosselaers وBart Preneel كجزء من مشروع RACE الأوروبي.\n\n**الخصائص الرئيسية:**\n- **حتمية**: نفس المدخل ينتج دائماً نفس التشفير\n- **حوسبة سريعة**: سريعة بشكل معقول للحساب لأي مدخل معطى\n- **تأثير الانهيار الجليدي**: تغييرات صغيرة في المدخل تنتج مخرجات مختلفة تماماً\n- **حجم مخرجات ثابت**: ينتج دائماً تشفير 160 بت بغض النظر عن حجم المدخل\n- **هيكل متوازي ثنائي الخط**: يستخدم خطين حوسبيين متوازيين لأمان محسن\n\n**حالة الأمان:**\n✅ **RIPEMD-160 يُعتبر آمناً تشفيرياً** بدون هجمات عملية معروفة. يوفر هامش أمان جيد وما زال موصى به للتطبيقات التشفيرية حيث يكون تشفير 160 بت كافياً.\n\n**الاستخدامات الشائعة:**\n- توليد عناوين البيتكوين (ترميز Base58Check)\n- التوقيعات الرقمية والشهادات\n- التحقق من سلامة البيانات\n- البروتوكولات التشفيرية التي تتطلب تشفير 160 بت\n- بديل لـ SHA-1 عند الحاجة\n\n**المقارنة مع الخوارزميات الأخرى:**\n- أكثر أماناً من MD5 و SHA-1\n- مخرجات أصغر من SHA-256 (160 بت مقابل 256 بت)\n- خصائص أداء جيدة\n- مدروس جيداً وموثوق في المجتمع التشفيري\n\n**موصى به لـ:**\n- التطبيقات التي تتطلب أمان تشفير 160 بت\n- العمليات التشفيرية المتعلقة بالبيتكوين\n- التوافق مع الأنظمة القديمة حيث يُحدد RIPEMD-160"
  },
  "hi": {
    "what-is-ripemd160": "RIPEMD-160 क्या है?",
    "what-is-ripemd160-description-markdown": "RIPEMD-160 (RACE Integrity Primitives Evaluation Message Digest) एक क्रिप्टोग्राफिक हैश फ़ंक्शन है जो 160-बिट (20-बाइट) हैश वैल्यू उत्पन्न करता है, जो आमतौर पर 40-वर्ण हेक्साडेसिमल संख्या के रूप में प्रस्तुत होता है। इसे 1996 में Hans Dobbertin, Antoon Bosselaers, और Bart Preneel द्वारा यूरोपीय RACE परियोजना के भाग के रूप में विकसित किया गया था।\n\n**मुख्य विशेषताएं:**\n- **निर्धारक**: समान इनपुट हमेशा समान हैश उत्पन्न करता है\n- **तेज़ गणना**: किसी भी दिए गए इनपुट के लिए उचित रूप से तेज़ गणना\n- **हिमस्खलन प्रभाव**: इनपुट में छोटे बदलाव बेहद अलग आउटपुट उत्पन्न करते हैं\n- **निश्चित आउटपुट आकार**: इनपुट आकार की परवाह किए बिना हमेशा 160-बिट हैश उत्पन्न करता है\n- **दो-लाइन समानांतर संरचना**: बेहतर सुरक्षा के लिए दो समानांतर गणना लाइनों का उपयोग करता है\n\n**सुरक्षा स्थिति:**\n✅ **RIPEMD-160 को क्रिप्टोग्राफिक रूप से सुरक्षित माना जाता है** बिना किसी ज्ञात व्यावहारिक हमलों के। यह एक अच्छा सुरक्षा मार्जिन प्रदान करता है और अभी भी उन क्रिप्टोग्राफिक अनुप्रयोगों के लिए अनुशंसित है जहां 160-बिट हैश पर्याप्त है।\n\n**सामान्य उपयोग:**\n- बिटकॉइन पता पीढ़ी (Base58Check एन्कोडिंग)\n- डिजिटल हस्ताक्षर और प्रमाणपत्र\n- डेटा अखंडता सत्यापन\n- 160-बिट हैश की आवश्यकता वाले क्रिप्टोग्राफिक प्रोटोकॉल\n- आवश्यकता होने पर SHA-1 का विकल्प\n\n**अन्य एल्गोरिदम के साथ तुलना:**\n- MD5 और SHA-1 से अधिक सुरक्षित\n- SHA-256 से छोटा आउटपुट (160-बिट बनाम 256-बिट)\n- अच्छी प्रदर्शन विशेषताएं\n- क्रिप्टोग्राफिक समुदाय में अच्छी तरह से अध्ययनित और विश्वसनीय\n\n**इसके लिए अनुशंसित:**\n- 160-बिट हैश सुरक्षा की आवश्यकता वाले अनुप्रयोग\n- बिटकॉइन-संबंधित क्रिप्टोग्राफिक ऑपरेशन\n- लीगेसी सिस्टम संगतता जहां RIPEMD-160 निर्दिष्ट है"
  },
  "tr": {
    "what-is-ripemd160": "RIPEMD-160 nedir?",
    "what-is-ripemd160-description-markdown": "RIPEMD-160 (RACE Integrity Primitives Evaluation Message Digest), tipik olarak 40 karakterlik onaltılık sayı olarak gösterilen 160-bit (20-bayt) hash değeri üreten kriptografik bir hash fonksiyonudur. 1996 yılında Hans Dobbertin, Antoon Bosselaers ve Bart Preneel tarafından Avrupa RACE projesinin bir parçası olarak geliştirilmiştir.\n\n**Temel özellikler:**\n- **Deterministik**: Aynı girdi her zaman aynı hash'i üretir\n- **Hızlı hesaplama**: Herhangi bir verilen girdi için makul şekilde hızla hesaplanır\n- **Çığ etkisi**: Girdideki küçük değişiklikler büyük ölçüde farklı çıktılar üretir\n- **Sabit çıktı boyutu**: Girdi boyutuna bakılmaksızın her zaman 160-bit hash üretir\n- **İki çizgili paralel yapı**: Gelişmiş güvenlik için iki paralel hesaplama çizgisi kullanır\n\n**Güvenlik durumu:**\n✅ **RIPEMD-160 kriptografik olarak güvenli kabul edilir** bilinen pratik saldırılar olmadan. İyi bir güvenlik marjı sağlar ve 160-bit hash'in yeterli olduğu kriptografik uygulamalar için hala önerilir.\n\n**Yaygın kullanımlar:**\n- Bitcoin adres üretimi (Base58Check kodlaması)\n- Dijital imzalar ve sertifikalar\n- Veri bütünlüğü doğrulama\n- 160-bit hash gerektiren kriptografik protokoller\n- Gerektiğinde SHA-1'e alternatif\n\n**Diğer algoritmalarla karşılaştırma:**\n- MD5 ve SHA-1'den daha güvenli\n- SHA-256'dan daha küçük çıktı (160-bit vs 256-bit)\n- İyi performans özellikleri\n- Kriptografik toplulukta iyi çalışılmış ve güvenilir\n\n**Şunlar için önerilir:**\n- 160-bit hash güvenliği gerektiren uygulamalar\n- Bitcoin ile ilgili kriptografik işlemler\n- RIPEMD-160'ın belirtildiği eski sistem uyumluluğu"
  },
  "nl": {
    "what-is-ripemd160": "Wat is RIPEMD-160?",
    "what-is-ripemd160-description-markdown": "RIPEMD-160 (RACE Integrity Primitives Evaluation Message Digest) is een cryptografische hashfunctie die een 160-bit (20-byte) hashwaarde produceert, doorgaans weergegeven als een 40-karakter hexadecimaal getal. Het werd ontwikkeld in 1996 door Hans Dobbertin, Antoon Bosselaers en Bart Preneel als onderdeel van het Europese RACE-project.\n\n**Belangrijkste kenmerken:**\n- **Deterministisch**: Dezelfde invoer produceert altijd dezelfde hash\n- **Snelle berekening**: Redelijk snel te berekenen voor elke gegeven invoer\n- **Lawine-effect**: Kleine veranderingen in invoer produceren drastisch verschillende uitvoer\n- **Vaste uitvoergrootte**: Produceert altijd een 160-bit hash ongeacht invoergrootte\n- **Twee-lijn parallelle structuur**: Gebruikt twee parallelle berekeningslijnen voor verbeterde beveiliging\n\n**Beveiligingsstatus:**\n✅ **RIPEMD-160 wordt beschouwd als cryptografisch veilig** zonder bekende praktische aanvallen. Het biedt een goede veiligheidsmarge en wordt nog steeds aanbevolen voor cryptografische toepassingen waar een 160-bit hash voldoende is.\n\n**Veelvoorkomende toepassingen:**\n- Bitcoin-adresgeneratie (Base58Check-codering)\n- Digitale handtekeningen en certificaten\n- Gegevensintegriteitsverificatie\n- Cryptografische protocollen die 160-bit hashes vereisen\n- Alternatief voor SHA-1 indien nodig\n\n**Vergelijking met andere algoritmen:**\n- Veiliger dan MD5 en SHA-1\n- Kleinere uitvoer dan SHA-256 (160-bit vs 256-bit)\n- Goede prestatiekenmerken\n- Goed bestudeerd en vertrouwd in de cryptografische gemeenschap\n\n**Aanbevolen voor:**\n- Toepassingen die 160-bit hashbeveiliging vereisen\n- Bitcoin-gerelateerde cryptografische bewerkingen\n- Legacy systeemcompatibiliteit waar RIPEMD-160 is gespecificeerd"
  },
  "sv": {
    "what-is-ripemd160": "Vad är RIPEMD-160?",
    "what-is-ripemd160-description-markdown": "RIPEMD-160 (RACE Integrity Primitives Evaluation Message Digest) är en kryptografisk hash-funktion som producerar ett 160-bitars (20-byte) hash-värde, vanligtvis återgivet som ett 40-tecken heksadecimalt tal. Det utvecklades 1996 av Hans Dobbertin, Antoon Bosselaers och Bart Preneel som del av det europeiska RACE-projektet.\n\n**Nyckelegenskaper:**\n- **Deterministisk**: Samma inmatning producerar alltid samma hash\n- **Snabb beräkning**: Rimligt snabb att beräkna för vilken given inmatning som helst\n- **Lavineffekt**: Små förändringar i inmatningen producerar drastiskt olika utmatningar\n- **Fast utmatningsstorlek**: Producerar alltid en 160-bitars hash oavsett inmatningsstorlek\n- **Tvålinjers parallell struktur**: Använder två parallella beräkningslinjer för förbättrad säkerhet\n\n**Säkerhetsstatus:**\n✅ **RIPEMD-160 anses vara kryptografiskt säker** utan kända praktiska attacker. Det ger en bra säkerhetsmarginal och rekommenderas fortfarande för kryptografiska applikationer där en 160-bitars hash är tillräcklig.\n\n**Vanliga användningar:**\n- Bitcoin-adressgenerering (Base58Check-kodning)\n- Digitala signaturer och certifikat\n- Dataintegritetsverifiering\n- Kryptografiska protokoll som kräver 160-bitars hasher\n- Alternativ till SHA-1 vid behov\n\n**Jämförelse med andra algoritmer:**\n- Säkrare än MD5 och SHA-1\n- Mindre utmatning än SHA-256 (160-bitar vs 256-bitar)\n- Bra prestandaegenskaper\n- Väl studerad och betrodd i kryptografiska gemenskapen\n\n**Rekommenderas för:**\n- Applikationer som kräver 160-bitars hash-säkerhet\n- Bitcoin-relaterade kryptografiska operationer\n- Kompatibilitet med äldre system där RIPEMD-160 är specificerat"
  },
  "pl": {
    "what-is-ripemd160": "Czym jest RIPEMD-160?",
    "what-is-ripemd160-description-markdown": "RIPEMD-160 (RACE Integrity Primitives Evaluation Message Digest) to kryptograficzna funkcja skrótu, która produkuje 160-bitową (20-bajtową) wartość skrótu, zazwyczaj przedstawianą jako 40-znakową liczbę szesnastkową. Została opracowana w 1996 roku przez Hansa Dobbertina, Antoona Bosselaersa i Barta Preneela jako część europejskiego projektu RACE.\n\n**Kluczowe cechy:**\n- **Deterministyczna**: To samo wejście zawsze produkuje ten sam skrót\n- **Szybkie obliczenia**: Rozsądnie szybkie do obliczenia dla dowolnego danego wejścia\n- **Efekt lawiny**: Małe zmiany w wejściu powodują drastycznie różne wyjścia\n- **Stały rozmiar wyjścia**: Zawsze produkuje 160-bitowy skrót niezależnie od rozmiaru wejścia\n- **Dwuliniowa struktura równoległa**: Używa dwóch równoległych linii obliczeniowych dla zwiększonej bezpieczeństwa\n\n**Status bezpieczeństwa:**\n✅ **RIPEMD-160 jest uważane za kryptograficznie bezpieczne** bez znanych praktycznych ataków. Zapewnia dobry margines bezpieczeństwa i nadal jest zalecane dla aplikacji kryptograficznych, gdzie 160-bitowy skrót jest wystarczający.\n\n**Powszechne zastosowania:**\n- Generowanie adresów Bitcoin (kodowanie Base58Check)\n- Podpisy cyfrowe i certyfikaty\n- Weryfikacja integralności danych\n- Protokoły kryptograficzne wymagające 160-bitowych skrótów\n- Alternatywa dla SHA-1 w razie potrzeby\n\n**Porównanie z innymi algorytmami:**\n- Bezpieczniejsze niż MD5 i SHA-1\n- Mniejsze wyjście niż SHA-256 (160 bitów vs 256 bitów)\n- Dobre charakterystyki wydajności\n- Dobrze zbadane i zaufane w społeczności kryptograficznej\n\n**Zalecane dla:**\n- Aplikacji wymagających 160-bitowego bezpieczeństwa skrótu\n- Operacji kryptograficznych związanych z Bitcoin\n- Kompatybilności ze starszymi systemami, gdzie określono RIPEMD-160"
  },
  "vi": {
    "what-is-ripemd160": "RIPEMD-160 là gì?",
    "what-is-ripemd160-description-markdown": "RIPEMD-160 (RACE Integrity Primitives Evaluation Message Digest) là một hàm băm mật mã tạo ra giá trị băm 160-bit (20-byte), thường được hiển thị dưới dạng số thập lục phân 40 ký tự. Nó được phát triển năm 1996 bởi Hans Dobbertin, Antoon Bosselaers và Bart Preneel như một phần của dự án RACE châu Âu.\n\n**Đặc điểm chính:**\n- **Xác định**: Cùng một đầu vào luôn tạo ra cùng một băm\n- **Tính toán nhanh**: Tính toán hợp lý nhanh cho bất kỳ đầu vào nào\n- **Hiệu ứng tuyết lở**: Những thay đổi nhỏ trong đầu vào tạo ra đầu ra hoàn toàn khác biệt\n- **Kích thước đầu ra cố định**: Luôn tạo ra băm 160-bit bất kể kích thước đầu vào\n- **Cấu trúc song song hai dòng**: Sử dụng hai dòng tính toán song song để tăng cường bảo mật\n\n**Tình trạng bảo mật:**\n✅ **RIPEMD-160 được coi là an toàn về mặt mật mã** không có các cuộc tấn công thực tế nào được biết đến. Nó cung cấp một biên độ an toàn tốt và vẫn được khuyến nghị cho các ứng dụng mật mã nơi băm 160-bit là đủ.\n\n**Sử dụng phổ biến:**\n- Tạo địa chỉ Bitcoin (mã hóa Base58Check)\n- Chữ ký số và chứng chỉ\n- Xác minh tính toàn vẹn dữ liệu\n- Các giao thức mật mã yêu cầu băm 160-bit\n- Thay thế cho SHA-1 khi cần thiết\n\n**So sánh với các thuật toán khác:**\n- An toàn hơn MD5 và SHA-1\n- Đầu ra nhỏ hơn SHA-256 (160-bit vs 256-bit)\n- Đặc tính hiệu suất tốt\n- Được nghiên cứu kỹ và tin cậy trong cộng đồng mật mã\n\n**Được khuyến nghị cho:**\n- Các ứng dụng yêu cầu bảo mật băm 160-bit\n- Các hoạt động mật mã liên quan đến Bitcoin\n- Tương thích hệ thống cũ nơi RIPEMD-160 được chỉ định"
  },
  "th": {
    "what-is-ripemd160": "RIPEMD-160 คืออะไร?",
    "what-is-ripemd160-description-markdown": "RIPEMD-160 (RACE Integrity Primitives Evaluation Message Digest) เป็นฟังก์ชันแฮชเข้ารหัสที่สร้างค่าแฮช 160-บิต (20-ไบต์) ซึ่งมักแสดงเป็นตัวเลขฐานสิบหก 40 ตัวอักษร พัฒนาในปี 1996 โดย Hans Dobbertin, Antoon Bosselaers และ Bart Preneel เป็นส่วนหนึ่งของโครงการ RACE ของยุโรป\n\n**คุณลักษณะสำคัญ:**\n- **กำหนดได้**: อินพุตเดียวกันจะสร้างแฮชเดียวกันเสมอ\n- **การคำนวณที่รวดเร็ว**: คำนวณได้อย่างรวดเร็วพอสมควรสำหรับอินพุตใดก็ตาม\n- **เอฟเฟกต์หิมะถล่ม**: การเปลี่ยนแปลงเล็กน้อยในอินพุตจะสร้างเอาต์พุตที่แตกต่างอย่างมาก\n- **ขนาดเอาต์พุตคงที่**: สร้างแฮช 160-บิตเสมอไม่ว่าขนาดอินพุตจะเป็นเท่าใด\n- **โครงสร้างคู่ขนาน**: ใช้สองสายการคำนวณแบบขนานเพื่อความปลอดภัยที่เพิ่มขึ้น\n\n**สถานะความปลอดภัย:**\n✅ **RIPEMD-160 ถือว่าปลอดภัยทางการเข้ารหัส** โดยไม่มีการโจมตีที่ใช้งานได้จริงที่ทราบ มันให้ขอบเขตความปลอดภัยที่ดีและยังคงแนะนำสำหรับแอปพลิเคชันการเข้ารหัสที่แฮช 160-บิตเพียงพอ\n\n**การใช้งานทั่วไป:**\n- การสร้างที่อยู่ Bitcoin (การเข้ารหัส Base58Check)\n- ลายเซ็นดิจิทัลและใบรับรอง\n- การตรวจสอบความสมบูรณ์ของข้อมูล\n- โปรโตคอลการเข้ารหัสที่ต้องการแฮช 160-บิต\n- ทางเลือกแทน SHA-1 เมื่อจำเป็น\n\n**การเปรียบเทียบกับอัลกอริธึมอื่น:**\n- ปลอดภัยกว่า MD5 และ SHA-1\n- เอาต์พุตเล็กกว่า SHA-256 (160-บิต เทียบกับ 256-บิต)\n- ลักษณะประสิทธิภาพที่ดี\n- ได้รับการศึกษาดีและเชื่อถือได้ในชุมชนการเข้ารหัส\n\n**แนะนำสำหรับ:**\n- แอปพลิเคชันที่ต้องการความปลอดภัยแฮช 160-บิต\n- การดำเนินการเข้ารหัสที่เกี่ยวข้องกับ Bitcoin\n- ความเข้ากันได้ของระบบเก่าที่ระบุ RIPEMD-160"
  },
  "id": {
    "what-is-ripemd160": "Apa itu RIPEMD-160?",
    "what-is-ripemd160-description-markdown": "RIPEMD-160 (RACE Integrity Primitives Evaluation Message Digest) adalah fungsi hash kriptografi yang menghasilkan nilai hash 160-bit (20-byte), biasanya ditampilkan sebagai angka heksadesimal 40 karakter. Dikembangkan pada tahun 1996 oleh Hans Dobbertin, Antoon Bosselaers, dan Bart Preneel sebagai bagian dari proyek RACE Eropa.\n\n**Karakteristik utama:**\n- **Deterministik**: Input yang sama selalu menghasilkan hash yang sama\n- **Komputasi cepat**: Cukup cepat dihitung untuk input apa pun yang diberikan\n- **Efek longsor**: Perubahan kecil pada input menghasilkan output yang sangat berbeda\n- **Ukuran output tetap**: Selalu menghasilkan hash 160-bit terlepas dari ukuran input\n- **Struktur paralel dua jalur**: Menggunakan dua jalur komputasi paralel untuk keamanan yang ditingkatkan\n\n**Status keamanan:**\n✅ **RIPEMD-160 dianggap aman secara kriptografi** tanpa serangan praktis yang diketahui. Memberikan margin keamanan yang baik dan masih direkomendasikan untuk aplikasi kriptografi di mana hash 160-bit sudah cukup.\n\n**Penggunaan umum:**\n- Generasi alamat Bitcoin (encoding Base58Check)\n- Tanda tangan digital dan sertifikat\n- Verifikasi integritas data\n- Protokol kriptografi yang memerlukan hash 160-bit\n- Alternatif untuk SHA-1 saat diperlukan\n\n**Perbandingan dengan algoritma lain:**\n- Lebih aman dari MD5 dan SHA-1\n- Output lebih kecil dari SHA-256 (160-bit vs 256-bit)\n- Karakteristik kinerja yang baik\n- Dipelajari dengan baik dan dipercaya dalam komunitas kriptografi\n\n**Direkomendasikan untuk:**\n- Aplikasi yang memerlukan keamanan hash 160-bit\n- Operasi kriptografi terkait Bitcoin\n- Kompatibilitas sistem lama di mana RIPEMD-160 ditentukan"
  },
  "he": {
    "what-is-ripemd160": "מה זה RIPEMD-160?",
    "what-is-ripemd160-description-markdown": "RIPEMD-160 (RACE Integrity Primitives Evaluation Message Digest) הוא פונקציית האש קריפטוגרפית המייצרת ערך האש של 160-ביט (20-בייט), המוצג בדרך כלל כמספר הקסדצימלי של 40 תווים. הוא פותח ב-1996 על ידי הנס דוברטין, אנטון בוסלארס וברט פרניל כחלק מפרויקט RACE האירופי.\n\n**מאפיינים עיקריים:**\n- **דטרמיניסטי**: אותו קלט תמיד מייצר אותו האש\n- **חישוב מהיר**: מהיר באופן סביר לחישוב עבור כל קלט נתון\n- **אפקט מפולת**: שינויים קטנים בקלט מייצרים פלטים שונים בתכלית\n- **גודל פלט קבוע**: תמיד מייצר האש של 160-ביט ללא קשר לגודל הקלט\n- **מבנה מקביל דו-קווי**: משתמש בשני קווי חישוב מקבילים לאבטחה משופרת\n\n**מצב אבטחה:**\n✅ **RIPEMD-160 נחשב בטוח קריפטוגרפית** ללא התקפות מעשיות ידועות. הוא מספק מרווח אבטחה טוב ועדיין מומלץ ליישומים קריפטוגרפיים שבהם האש של 160-ביט מספיק.\n\n**שימושים נפוצים:**\n- יצירת כתובות ביטקוין (קידוד Base58Check)\n- חתימות דיגיטליות ותעודות\n- אימות תקינות נתונים\n- פרוטוקולים קריפטוגרפיים הדורשים האש של 160-ביט\n- חלופה ל-SHA-1 כאשר נדרש\n\n**השוואה עם אלגוריתמים אחרים:**\n- בטוח יותר מ-MD5 ו-SHA-1\n- פלט קטן יותר מ-SHA-256 (160-ביט לעומת 256-ביט)\n- מאפייני ביצועים טובים\n- נחקר היטב ומהימן בקהילה הקריפטוגרפית\n\n**מומלץ עבור:**\n- יישומים הדורשים אבטחת האש של 160-ביט\n- פעולות קריפטוגרפיות הקשורות לביטקוין\n- תאימות למערכות ישנות שבהן RIPEMD-160 מוגדר"
  },
  "ms": {
    "what-is-ripemd160": "Apakah RIPEMD-160?",
    "what-is-ripemd160-description-markdown": "RIPEMD-160 (RACE Integrity Primitives Evaluation Message Digest) adalah fungsi hash kriptografi yang menghasilkan nilai hash 160-bit (20-byte), biasanya dipaparkan sebagai nombor heksadesimal 40 aksara. Ia dibangunkan pada tahun 1996 oleh Hans Dobbertin, Antoon Bosselaers, dan Bart Preneel sebagai sebahagian daripada projek RACE Eropah.\n\n**Ciri-ciri utama:**\n- **Deterministik**: Input yang sama sentiasa menghasilkan hash yang sama\n- **Pengiraan pantas**: Agak pantas dikira untuk sebarang input yang diberikan\n- **Kesan runtuhan salji**: Perubahan kecil dalam input menghasilkan output yang sangat berbeza\n- **Saiz output tetap**: Sentiasa menghasilkan hash 160-bit tanpa mengira saiz input\n- **Struktur selari dua baris**: Menggunakan dua baris pengiraan selari untuk keselamatan yang dipertingkat\n\n**Status keselamatan:**\n✅ **RIPEMD-160 dianggap selamat secara kriptografi** tanpa serangan praktikal yang diketahui. Ia memberikan margin keselamatan yang baik dan masih disyorkan untuk aplikasi kriptografi di mana hash 160-bit mencukupi.\n\n**Kegunaan biasa:**\n- Penjanaan alamat Bitcoin (pengekodan Base58Check)\n- Tandatangan digital dan sijil\n- Pengesahan integriti data\n- Protokol kriptografi yang memerlukan hash 160-bit\n- Alternatif kepada SHA-1 apabila diperlukan\n\n**Perbandingan dengan algoritma lain:**\n- Lebih selamat daripada MD5 dan SHA-1\n- Output lebih kecil daripada SHA-256 (160-bit vs 256-bit)\n- Ciri prestasi yang baik\n- Dikaji dengan baik dan dipercayai dalam komuniti kriptografi\n\n**Disyorkan untuk:**\n- Aplikasi yang memerlukan keselamatan hash 160-bit\n- Operasi kriptografi berkaitan Bitcoin\n- Keserasian sistem lama di mana RIPEMD-160 dinyatakan"
  },
  "no": {
    "what-is-ripemd160": "Hva er RIPEMD-160?",
    "what-is-ripemd160-description-markdown": "RIPEMD-160 (RACE Integrity Primitives Evaluation Message Digest) er en kryptografisk hash-funksjon som produserer en 160-bits (20-byte) hash-verdi, vanligvis gjengitt som et 40-tegn heksadesimalt tall. Den ble utviklet i 1996 av Hans Dobbertin, Antoon Bosselaers og Bart Preneel som del av det europeiske RACE-prosjektet.\n\n**Nøkkelegenskaper:**\n- **Deterministisk**: Samme inndata produserer alltid samme hash\n- **Rask beregning**: Rimelig rask å beregne for enhver gitt inndata\n- **Snøskredeffekt**: Små endringer i inndata produserer drastisk forskjellige utdata\n- **Fast utdatastørrelse**: Produserer alltid en 160-bits hash uavhengig av inndata-størrelse\n- **To-linjes parallell struktur**: Bruker to parallelle beregningslinjer for forbedret sikkerhet\n\n**Sikkerhetsstatus:**\n✅ **RIPEMD-160 anses som kryptografisk sikker** uten kjente praktiske angrep. Det gir en god sikkerhetsmargin og anbefales fortsatt for kryptografiske applikasjoner der en 160-bits hash er tilstrekkelig.\n\n**Vanlige bruksområder:**\n- Bitcoin-adressegenerering (Base58Check-koding)\n- Digitale signaturer og sertifikater\n- Dataintegritetsverifisering\n- Kryptografiske protokoller som krever 160-bits hashes\n- Alternativ til SHA-1 ved behov\n\n**Sammenligning med andre algoritmer:**\n- Sikrere enn MD5 og SHA-1\n- Mindre utdata enn SHA-256 (160-bits vs 256-bits)\n- Gode ytelsesegenskaper\n- Godt studert og betrodd i kryptografiske miljøer\n\n**Anbefales for:**\n- Applikasjoner som krever 160-bits hash-sikkerhet\n- Bitcoin-relaterte kryptografiske operasjoner\n- Kompatibilitet med eldre systemer der RIPEMD-160 er spesifisert"
  }
}
</i18n>
