<template>
  <DescriptionMarkdown
    :title="t('what-is-md5')"
    :description="t('what-is-md5-description-markdown')"
  />
</template>

<script setup lang="ts">
import { DescriptionMarkdown } from '@shared/ui/base'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()
</script>

<i18n lang="json">
{
  "en": {
    "what-is-md5": "What is MD5?",
    "what-is-md5-description-markdown": "MD5 (Message Digest Algorithm 5) is a widely used cryptographic hash function that produces a 128-bit (16-byte) hash value, typically rendered as a 32-character hexadecimal number. It was designed by Ron Rivest in 1991 as a successor to MD4.\n\n**Key characteristics:**\n- **Deterministic**: The same input always produces the same hash\n- **Fast computation**: Quick to compute for any given input\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Fixed output size**: Always produces a 128-bit hash regardless of input size\n- **Collision vulnerable**: Known vulnerabilities make it possible to find collisions\n\n**Security status:**\n⚠️ **MD5 is cryptographically broken and should not be used for security-critical applications**. Collision attacks were demonstrated in 2004, and practical collision generation became feasible with modern computing power.\n\n**Common uses (current and historical):**\n- File integrity verification (non-security critical)\n- Checksums for data corruption detection\n- Legacy systems requiring MD5\n- Database key generation (non-cryptographic)\n- Some older protocols and systems\n\n**Recommended alternatives:**\n- SHA-256 or SHA-3 for new applications\n- SHA-512 for high-security requirements\n- BLAKE2 for high-performance applications"
  },
  "zh": {
    "what-is-md5": "什么是 MD5？",
    "what-is-md5-description-markdown": "MD5（消息摘要算法 5）是一种广泛使用的加密散列函数，产生 128 位（16 字节）的散列值，通常呈现为 32 个字符的十六进制数。它由 Ron Rivest 于 1991 年设计，作为 MD4 的后继者。\n\n**主要特征：**\n- **确定性**：相同的输入总是产生相同的散列\n- **快速计算**：对于任何给定输入都能快速计算\n- **雪崩效应**：输入的微小变化会产生截然不同的输出\n- **固定输出大小**：无论输入大小如何，始终产生 128 位散列\n- **碰撞脆弱性**：已知漏洞使得找到碰撞成为可能\n\n**安全状态：**\n⚠️ **MD5 在密码学上已被破解，不应用于安全关键应用**。碰撞攻击在 2004 年得到证明，现代计算能力使实际碰撞生成变得可行。\n\n**常见用途（当前和历史）：**\n- 文件完整性验证（非安全关键）\n- 数据损坏检测的校验和\n- 需要 MD5 的遗留系统\n- 数据库密钥生成（非加密）\n- 一些较老的协议和系统\n\n**推荐替代方案：**\n- 新应用使用 SHA-256 或 SHA-3\n- 高安全要求使用 SHA-512\n- 高性能应用使用 BLAKE2"
  },
  "zh-CN": {
    "what-is-md5": "什么是 MD5？",
    "what-is-md5-description-markdown": "MD5（消息摘要算法 5）是一种广泛使用的加密散列函数，产生 128 位（16 字节）的散列值，通常呈现为 32 个字符的十六进制数。它由 Ron Rivest 于 1991 年设计，作为 MD4 的后继者。\n\n**主要特征：**\n- **确定性**：相同的输入总是产生相同的散列\n- **快速计算**：对于任何给定输入都能快速计算\n- **雪崩效应**：输入的微小变化会产生截然不同的输出\n- **固定输出大小**：无论输入大小如何，始终产生 128 位散列\n- **碰撞脆弱性**：已知漏洞使得找到碰撞成为可能\n\n**安全状态：**\n⚠️ **MD5 在密码学上已被破解，不应用于安全关键应用**。碰撞攻击在 2004 年得到证明，现代计算能力使实际碰撞生成变得可行。\n\n**常见用途（当前和历史）：**\n- 文件完整性验证（非安全关键）\n- 数据损坏检测的校验和\n- 需要 MD5 的遗留系统\n- 数据库密钥生成（非加密）\n- 一些较老的协议和系统\n\n**推荐替代方案：**\n- 新应用使用 SHA-256 或 SHA-3\n- 高安全要求使用 SHA-512\n- 高性能应用使用 BLAKE2"
  },
  "zh-TW": {
    "what-is-md5": "什麼是 MD5？",
    "what-is-md5-description-markdown": "MD5（訊息摘要演算法 5）是一種廣泛使用的加密雜湊函數，產生 128 位元（16 位元組）的雜湊值，通常呈現為 32 個字元的十六進位數。它由 Ron Rivest 於 1991 年設計，作為 MD4 的後繼者。\n\n**主要特徵：**\n- **確定性**：相同的輸入總是產生相同的雜湊\n- **快速計算**：對於任何給定輸入都能快速計算\n- **雪崩效應**：輸入的微小變化會產生截然不同的輸出\n- **固定輸出大小**：無論輸入大小如何，始終產生 128 位元雜湊\n- **碰撞脆弱性**：已知漏洞使得找到碰撞成為可能\n\n**安全狀態：**\n⚠️ **MD5 在密碼學上已被破解，不應用於安全關鍵應用**。碰撞攻擊在 2004 年得到證明，現代計算能力使實際碰撞生成變得可行。\n\n**常見用途（當前和歷史）：**\n- 檔案完整性驗證（非安全關鍵）\n- 資料損壞檢測的校驗和\n- 需要 MD5 的遺留系統\n- 資料庫密鑰生成（非加密）\n- 一些較老的協定和系統\n\n**推薦替代方案：**\n- 新應用使用 SHA-256 或 SHA-3\n- 高安全要求使用 SHA-512\n- 高性能應用使用 BLAKE2"
  },
  "zh-HK": {
    "what-is-md5": "什麼是 MD5？",
    "what-is-md5-description-markdown": "MD5（訊息摘要演算法 5）是一種廣泛使用的加密雜湊函數，產生 128 位元（16 位元組）的雜湊值，通常呈現為 32 個字元的十六進位數。它由 Ron Rivest 於 1991 年設計，作為 MD4 的後繼者。\n\n**主要特徵：**\n- **確定性**：相同的輸入總是產生相同的雜湊\n- **快速計算**：對於任何給定輸入都能快速計算\n- **雪崩效應**：輸入的微小變化會產生截然不同的輸出\n- **固定輸出大小**：無論輸入大小如何，始終產生 128 位元雜湊\n- **碰撞脆弱性**：已知漏洞使得找到碰撞成為可能\n\n**安全狀態：**\n⚠️ **MD5 在密碼學上已被破解，不應用於安全關鍵應用**。碰撞攻擊在 2004 年得到證明，現代計算能力使實際碰撞生成變得可行。\n\n**常見用途（當前和歷史）：**\n- 檔案完整性驗證（非安全關鍵）\n- 資料損壞檢測的校驗和\n- 需要 MD5 的遺留系統\n- 資料庫密鑰生成（非加密）\n- 一些較老的協定和系統\n\n**推薦替代方案：**\n- 新應用使用 SHA-256 或 SHA-3\n- 高安全要求使用 SHA-512\n- 高性能應用使用 BLAKE2"
  },
  "es": {
    "what-is-md5": "¿Qué es MD5?",
    "what-is-md5-description-markdown": "MD5 (Algoritmo de Resumen de Mensaje 5) es una función hash criptográfica ampliamente utilizada que produce un valor hash de 128 bits (16 bytes), típicamente representado como un número hexadecimal de 32 caracteres. Fue diseñado por Ron Rivest en 1991 como sucesor de MD4.\n\n**Características clave:**\n- **Determinístico**: La misma entrada siempre produce el mismo hash\n- **Computación rápida**: Rápido de calcular para cualquier entrada dada\n- **Efecto avalancha**: Pequeños cambios en la entrada producen salidas drásticamente diferentes\n- **Tamaño de salida fijo**: Siempre produce un hash de 128 bits independientemente del tamaño de entrada\n- **Vulnerable a colisiones**: Las vulnerabilidades conocidas hacen posible encontrar colisiones\n\n**Estado de seguridad:**\n⚠️ **MD5 está criptográficamente roto y no debe usarse para aplicaciones críticas de seguridad**. Los ataques de colisión se demostraron en 2004, y la generación práctica de colisiones se hizo factible con el poder computacional moderno.\n\n**Usos comunes (actuales e históricos):**\n- Verificación de integridad de archivos (no crítico para seguridad)\n- Sumas de verificación para detección de corrupción de datos\n- Sistemas heredados que requieren MD5\n- Generación de claves de base de datos (no criptográfico)\n- Algunos protocolos y sistemas más antiguos\n\n**Alternativas recomendadas:**\n- SHA-256 o SHA-3 para nuevas aplicaciones\n- SHA-512 para requisitos de alta seguridad\n- BLAKE2 para aplicaciones de alto rendimiento"
  },
  "fr": {
    "what-is-md5": "Qu'est-ce que MD5 ?",
    "what-is-md5-description-markdown": "MD5 (Message Digest Algorithm 5) est une fonction de hachage cryptographique largement utilisée qui produit une valeur de hachage de 128 bits (16 octets), généralement rendue sous forme d'un nombre hexadécimal de 32 caractères. Il a été conçu par Ron Rivest en 1991 comme successeur de MD4.\n\n**Caractéristiques clés :**\n- **Déterministe** : La même entrée produit toujours le même hachage\n- **Calcul rapide** : Rapide à calculer pour toute entrée donnée\n- **Effet d'avalanche** : De petits changements dans l'entrée produisent des sorties drastiquement différentes\n- **Taille de sortie fixe** : Produit toujours un hachage de 128 bits quelle que soit la taille d'entrée\n- **Vulnérable aux collisions** : Les vulnérabilités connues rendent possible la recherche de collisions\n\n**État de sécurité :**\n⚠️ **MD5 est cryptographiquement cassé et ne devrait pas être utilisé pour des applications critiques de sécurité**. Les attaques de collision ont été démontrées en 2004, et la génération pratique de collisions est devenue réalisable avec la puissance de calcul moderne.\n\n**Utilisations courantes (actuelles et historiques) :**\n- Vérification d'intégrité de fichiers (non critique pour la sécurité)\n- Sommes de contrôle pour la détection de corruption de données\n- Systèmes hérités nécessitant MD5\n- Génération de clés de base de données (non cryptographique)\n- Certains protocoles et systèmes plus anciens\n\n**Alternatives recommandées :**\n- SHA-256 ou SHA-3 pour les nouvelles applications\n- SHA-512 pour les exigences de haute sécurité\n- BLAKE2 pour les applications haute performance"
  },
  "de": {
    "what-is-md5": "Was ist MD5?",
    "what-is-md5-description-markdown": "MD5 (Message Digest Algorithm 5) ist eine weit verbreitete kryptographische Hash-Funktion, die einen 128-Bit (16-Byte) Hash-Wert erzeugt, der typischerweise als 32-stellige Hexadezimalzahl dargestellt wird. Es wurde 1991 von Ron Rivest als Nachfolger von MD4 entworfen.\n\n**Hauptmerkmale:**\n- **Deterministisch**: Dieselbe Eingabe erzeugt immer denselben Hash\n- **Schnelle Berechnung**: Schnell zu berechnen für jede gegebene Eingabe\n- **Lawineneffekt**: Kleine Änderungen in der Eingabe erzeugen drastisch unterschiedliche Ausgaben\n- **Feste Ausgabegröße**: Erzeugt immer einen 128-Bit Hash unabhängig von der Eingabegröße\n- **Kollisionsvulnerabel**: Bekannte Schwachstellen machen es möglich, Kollisionen zu finden\n\n**Sicherheitsstatus:**\n⚠️ **MD5 ist kryptographisch gebrochen und sollte nicht für sicherheitskritische Anwendungen verwendet werden**. Kollisionsangriffe wurden 2004 demonstriert, und praktische Kollisionsgenerierung wurde mit moderner Rechenleistung machbar.\n\n**Häufige Verwendungen (aktuell und historisch):**\n- Datei-Integritätsprüfung (nicht sicherheitskritisch)\n- Prüfsummen zur Erkennung von Datenkorruption\n- Legacy-Systeme, die MD5 erfordern\n- Datenbank-Schlüsselgenerierung (nicht kryptographisch)\n- Einige ältere Protokolle und Systeme\n\n**Empfohlene Alternativen:**\n- SHA-256 oder SHA-3 für neue Anwendungen\n- SHA-512 für hohe Sicherheitsanforderungen\n- BLAKE2 für Hochleistungsanwendungen"
  },
  "it": {
    "what-is-md5": "Cos'è MD5?",
    "what-is-md5-description-markdown": "MD5 (Message Digest Algorithm 5) è una funzione hash crittografica ampiamente utilizzata che produce un valore hash di 128 bit (16 byte), tipicamente rappresentato come un numero esadecimale di 32 caratteri. È stato progettato da Ron Rivest nel 1991 come successore di MD4.\n\n**Caratteristiche chiave:**\n- **Deterministico**: Lo stesso input produce sempre lo stesso hash\n- **Calcolo veloce**: Veloce da calcolare per qualsiasi input dato\n- **Effetto valanga**: Piccoli cambiamenti nell'input producono output drasticamente diversi\n- **Dimensione output fissa**: Produce sempre un hash di 128 bit indipendentemente dalla dimensione dell'input\n- **Vulnerabile alle collisioni**: Le vulnerabilità note rendono possibile trovare collisioni\n\n**Stato di sicurezza:**\n⚠️ **MD5 è crittograficamente compromesso e non dovrebbe essere usato per applicazioni critiche per la sicurezza**. Gli attacchi di collisione sono stati dimostrati nel 2004, e la generazione pratica di collisioni è diventata fattibile con la potenza di calcolo moderna.\n\n**Usi comuni (attuali e storici):**\n- Verifica dell'integrità dei file (non critica per la sicurezza)\n- Checksum per la rilevazione della corruzione dei dati\n- Sistemi legacy che richiedono MD5\n- Generazione di chiavi del database (non crittografico)\n- Alcuni protocolli e sistemi più vecchi\n\n**Alternative raccomandate:**\n- SHA-256 o SHA-3 per nuove applicazioni\n- SHA-512 per requisiti di alta sicurezza\n- BLAKE2 per applicazioni ad alte prestazioni"
  },
  "ja": {
    "what-is-md5": "MD5とは？",
    "what-is-md5-description-markdown": "MD5（Message Digest Algorithm 5）は、128ビット（16バイト）のハッシュ値を生成する広く使用されている暗号学的ハッシュ関数で、通常32文字の16進数として表示されます。1991年にRon RivestによってMD4の後継として設計されました。\n\n**主な特徴：**\n- **決定論的**：同じ入力は常に同じハッシュを生成\n- **高速計算**：任意の入力に対して高速に計算\n- **雪崩効果**：入力の小さな変化が劇的に異なる出力を生成\n- **固定出力サイズ**：入力サイズに関係なく常に128ビットハッシュを生成\n- **衝突脆弱性**：既知の脆弱性により衝突を見つけることが可能\n\n**セキュリティ状況：**\n⚠️ **MD5は暗号学的に破られており、セキュリティが重要なアプリケーションでは使用すべきではありません**。衝突攻撃は2004年に実証され、現代の計算能力により実用的な衝突生成が実現可能になりました。\n\n**一般的な用途（現在と歴史的）：**\n- ファイル整合性検証（セキュリティ非重要）\n- データ破損検出のためのチェックサム\n- MD5を必要とするレガシーシステム\n- データベースキー生成（非暗号学的）\n- 一部の古いプロトコルとシステム\n\n**推奨される代替案：**\n- 新しいアプリケーションにはSHA-256またはSHA-3\n- 高セキュリティ要件にはSHA-512\n- 高性能アプリケーションにはBLAKE2"
  },
  "ko": {
    "what-is-md5": "MD5이란?",
    "what-is-md5-description-markdown": "MD5(Message Digest Algorithm 5)는 128비트(16바이트) 해시 값을 생성하는 널리 사용되는 암호화 해시 함수로, 일반적으로 32자리 16진수로 표현됩니다. 1991년 Ron Rivest가 MD4의 후속작으로 설계했습니다.\n\n**주요 특징:**\n- **결정론적**: 동일한 입력은 항상 동일한 해시를 생성\n- **빠른 계산**: 주어진 입력에 대해 빠르게 계산\n- **눈사태 효과**: 입력의 작은 변화가 완전히 다른 출력을 생성\n- **고정 출력 크기**: 입력 크기에 관계없이 항상 128비트 해시를 생성\n- **충돌 취약성**: 알려진 취약점으로 인해 충돌을 찾는 것이 가능\n\n**보안 상태:**\n⚠️ **MD5는 암호학적으로 깨졌으며 보안이 중요한 애플리케이션에서는 사용해서는 안 됩니다**. 충돌 공격은 2004년에 증명되었고, 현대 컴퓨팅 파워로 실용적인 충돌 생성이 실현 가능해졌습니다.\n\n**일반적인 용도(현재 및 역사적):**\n- 파일 무결성 검증(보안 비중요)\n- 데이터 손상 감지를 위한 체크섬\n- MD5가 필요한 레거시 시스템\n- 데이터베이스 키 생성(비암호화)\n- 일부 오래된 프로토콜 및 시스템\n\n**권장 대안:**\n- 새로운 애플리케이션에는 SHA-256 또는 SHA-3\n- 높은 보안 요구사항에는 SHA-512\n- 고성능 애플리케이션에는 BLAKE2"
  },
  "ru": {
    "what-is-md5": "Что такое MD5?",
    "what-is-md5-description-markdown": "MD5 (Message Digest Algorithm 5) — это широко используемая криптографическая хеш-функция, которая производит 128-битное (16-байтовое) хеш-значение, обычно представляемое как 32-символьное шестнадцатеричное число. Он был разработан Роном Ривестом в 1991 году как преемник MD4.\n\n**Ключевые характеристики:**\n- **Детерминированность**: Одинаковый ввод всегда производит одинаковый хеш\n- **Быстрое вычисление**: Быстро вычисляется для любого заданного ввода\n- **Эффект лавины**: Небольшие изменения во вводе производят кардинально разные выводы\n- **Фиксированный размер вывода**: Всегда производит 128-битный хеш независимо от размера ввода\n- **Уязвимость к коллизиям**: Известные уязвимости делают возможным поиск коллизий\n\n**Статус безопасности:**\n⚠️ **MD5 криптографически сломан и не должен использоваться для критически важных для безопасности приложений**. Атаки коллизий были продемонстрированы в 2004 году, и практическая генерация коллизий стала осуществимой с современной вычислительной мощностью.\n\n**Обычные применения (текущие и исторические):**\n- Проверка целостности файлов (не критично для безопасности)\n- Контрольные суммы для обнаружения повреждения данных\n- Устаревшие системы, требующие MD5\n- Генерация ключей базы данных (не криптографическая)\n- Некоторые старые протоколы и системы\n\n**Рекомендуемые альтернативы:**\n- SHA-256 или SHA-3 для новых приложений\n- SHA-512 для высоких требований безопасности\n- BLAKE2 для высокопроизводительных приложений"
  },
  "pt": {
    "what-is-md5": "O que é MD5?",
    "what-is-md5-description-markdown": "MD5 (Message Digest Algorithm 5) é uma função hash criptográfica amplamente utilizada que produz um valor hash de 128 bits (16 bytes), tipicamente representado como um número hexadecimal de 32 caracteres. Foi projetado por Ron Rivest em 1991 como sucessor do MD4.\n\n**Características principais:**\n- **Determinístico**: A mesma entrada sempre produz o mesmo hash\n- **Computação rápida**: Rápido de calcular para qualquer entrada dada\n- **Efeito avalanche**: Pequenas mudanças na entrada produzem saídas drasticamente diferentes\n- **Tamanho de saída fixo**: Sempre produz um hash de 128 bits independentemente do tamanho da entrada\n- **Vulnerável a colisões**: Vulnerabilidades conhecidas tornam possível encontrar colisões\n\n**Status de segurança:**\n⚠️ **MD5 está criptograficamente quebrado e não deve ser usado para aplicações críticas de segurança**. Ataques de colisão foram demonstrados em 2004, e a geração prática de colisões tornou-se viável com o poder computacional moderno.\n\n**Usos comuns (atuais e históricos):**\n- Verificação de integridade de arquivos (não crítico para segurança)\n- Checksums para detecção de corrupção de dados\n- Sistemas legados que requerem MD5\n- Geração de chaves de banco de dados (não criptográfico)\n- Alguns protocolos e sistemas mais antigos\n\n**Alternativas recomendadas:**\n- SHA-256 ou SHA-3 para novas aplicações\n- SHA-512 para requisitos de alta segurança\n- BLAKE2 para aplicações de alto desempenho"
  },
  "ar": {
    "what-is-md5": "ما هو MD5؟",
    "what-is-md5-description-markdown": "MD5 (خوارزمية تشفير الرسائل 5) هي دالة تشفير مستخدمة على نطاق واسع تنتج قيمة تشفير بحجم 128 بت (16 بايت)، وتُعرض عادة كرقم سادس عشر مكون من 32 حرفاً. صممها Ron Rivest في 1991 كخليفة لـ MD4.\n\n**الخصائص الرئيسية:**\n- **حتمية**: نفس المدخل ينتج دائماً نفس التشفير\n- **حوسبة سريعة**: سريعة الحساب لأي مدخل معطى\n- **تأثير الانهيار الجليدي**: تغييرات صغيرة في المدخل تنتج مخرجات مختلفة تماماً\n- **حجم مخرجات ثابت**: ينتج دائماً تشفير 128 بت بغض النظر عن حجم المدخل\n- **عرضة للتصادمات**: نقاط الضعف المعروفة تجعل إيجاد التصادمات ممكناً\n\n**حالة الأمان:**\n⚠️ **MD5 مكسور تشفيرياً ولا يجب استخدامه للتطبيقات الحرجة أمنياً**. هجمات التصادم تم إثباتها في 2004، وتوليد التصادمات العملي أصبح ممكناً مع القوة الحاسوبية الحديثة.\n\n**الاستخدامات الشائعة (الحالية والتاريخية):**\n- التحقق من سلامة الملفات (غير حرج أمنياً)\n- مجاميع التحقق لاكتشاف تلف البيانات\n- الأنظمة القديمة التي تتطلب MD5\n- توليد مفاتيح قاعدة البيانات (غير تشفيري)\n- بعض البروتوكولات والأنظمة الأقدم\n\n**البدائل الموصى بها:**\n- SHA-256 أو SHA-3 للتطبيقات الجديدة\n- SHA-512 لمتطلبات الأمان العالية\n- BLAKE2 للتطبيقات عالية الأداء"
  },
  "hi": {
    "what-is-md5": "MD5 क्या है?",
    "what-is-md5-description-markdown": "MD5 (Message Digest Algorithm 5) एक व्यापक रूप से उपयोग किया जाने वाला क्रिप्टोग्राफिक हैश फ़ंक्शन है जो 128-बिट (16-बाइट) हैश वैल्यू उत्पन्न करता है, जो आमतौर पर 32-वर्ण हेक्साडेसिमल संख्या के रूप में प्रस्तुत होता है। इसे 1991 में Ron Rivest द्वारा MD4 के उत्तराधिकारी के रूप में डिज़ाइन किया गया था।\n\n**मुख्य विशेषताएं:**\n- **निर्धारक**: समान इनपुट हमेशा समान हैश उत्पन्न करता है\n- **तेज़ गणना**: किसी भी दिए गए इनपुट के लिए तेज़ी से गणना\n- **हिमस्खलन प्रभाव**: इनपुट में छोटे बदलाव बेहद अलग आउटपुट उत्पन्न करते हैं\n- **निश्चित आउटपुट आकार**: इनपुट आकार की परवाह किए बिना हमेशा 128-बिट हैश उत्पन्न करता है\n- **टक्कर संवेदनशील**: ज्ञात कमजोरियां टकराव खोजना संभव बनाती हैं\n\n**सुरक्षा स्थिति:**\n⚠️ **MD5 क्रिप्टोग्राफिक रूप से टूटा हुआ है और सुरक्षा-महत्वपूर्ण अनुप्रयोगों के लिए उपयोग नहीं किया जाना चाहिए**। टकराव हमले 2004 में प्रदर्शित किए गए थे, और आधुनिक कंप्यूटिंग शक्ति के साथ व्यावहारिक टकराव पीढ़ी संभव हो गई।\n\n**सामान्य उपयोग (वर्तमान और ऐतिहासिक):**\n- फ़ाइल अखंडता सत्यापन (सुरक्षा गैर-महत्वपूर्ण)\n- डेटा भ्रष्टाचार का पता लगाने के लिए चेकसम\n- लीगेसी सिस्टम जिन्हें MD5 की आवश्यकता है\n- डेटाबेस कुंजी पीढ़ी (गैर-क्रिप्टोग्राफिक)\n- कुछ पुराने प्रोटोकॉल और सिस्टम\n\n**अनुशंसित विकल्प:**\n- नए अनुप्रयोगों के लिए SHA-256 या SHA-3\n- उच्च सुरक्षा आवश्यकताओं के लिए SHA-512\n- उच्च प्रदर्शन अनुप्रयोगों के लिए BLAKE2"
  },
  "tr": {
    "what-is-md5": "MD5 nedir?",
    "what-is-md5-description-markdown": "MD5 (Message Digest Algorithm 5), tipik olarak 32 karakterlik onaltılık sayı olarak gösterilen 128-bit (16-bayt) hash değeri üreten yaygın olarak kullanılan kriptografik bir hash fonksiyonudur. 1991 yılında Ron Rivest tarafından MD4'ün halefi olarak tasarlanmıştır.\n\n**Temel özellikler:**\n- **Deterministik**: Aynı girdi her zaman aynı hash'i üretir\n- **Hızlı hesaplama**: Herhangi bir verilen girdi için hızla hesaplanır\n- **Çığ etkisi**: Girdideki küçük değişiklikler büyük ölçüde farklı çıktılar üretir\n- **Sabit çıktı boyutu**: Girdi boyutuna bakılmaksızın her zaman 128-bit hash üretir\n- **Çarpışma açığı**: Bilinen güvenlik açıkları çarpışma bulmayı mümkün kılar\n\n**Güvenlik durumu:**\n⚠️ **MD5 kriptografik olarak kırılmıştır ve güvenlik açısından kritik uygulamalar için kullanılmamalıdır**. Çarpışma saldırıları 2004 yılında gösterilmiş ve modern hesaplama gücü ile pratik çarpışma üretimi mümkün hale gelmiştir.\n\n**Yaygın kullanımlar (mevcut ve tarihsel):**\n- Dosya bütünlüğü doğrulama (güvenlik açısından kritik değil)\n- Veri bozulması tespiti için kontrol toplamları\n- MD5 gerektiren eski sistemler\n- Veritabanı anahtar üretimi (kriptografik olmayan)\n- Bazı eski protokoller ve sistemler\n\n**Önerilen alternatifler:**\n- Yeni uygulamalar için SHA-256 veya SHA-3\n- Yüksek güvenlik gereksinimleri için SHA-512\n- Yüksek performans uygulamaları için BLAKE2"
  },
  "nl": {
    "what-is-md5": "Wat is MD5?",
    "what-is-md5-description-markdown": "MD5 (Message Digest Algorithm 5) is een veel gebruikte cryptografische hashfunctie die een 128-bit (16-byte) hashwaarde produceert, doorgaans weergegeven als een 32-karakter hexadecimaal getal. Het is ontworpen door Ron Rivest in 1991 als opvolger van MD4.\n\n**Belangrijkste kenmerken:**\n- **Deterministisch**: Dezelfde invoer produceert altijd dezelfde hash\n- **Snelle berekening**: Snel te berekenen voor elke gegeven invoer\n- **Lawine-effect**: Kleine veranderingen in invoer produceren drastisch verschillende uitvoer\n- **Vaste uitvoergrootte**: Produceert altijd een 128-bit hash ongeacht invoergrootte\n- **Botsingsgevoelig**: Bekende kwetsbaarheden maken het mogelijk om botsingen te vinden\n\n**Beveiligingsstatus:**\n⚠️ **MD5 is cryptografisch gebroken en mag niet worden gebruikt voor beveiligingskritische toepassingen**. Botsingsaanvallen werden gedemonstreerd in 2004, en praktische botsingsgeneratie werd haalbaar met moderne rekenkracht.\n\n**Veelvoorkomende toepassingen (huidig en historisch):**\n- Bestandsintegriteitsverificatie (niet beveiligingskritisch)\n- Checksums voor detectie van gegevenscorruptie\n- Legacy systemen die MD5 vereisen\n- Database sleutelgeneratie (niet-cryptografisch)\n- Sommige oudere protocollen en systemen\n\n**Aanbevolen alternatieven:**\n- SHA-256 of SHA-3 voor nieuwe toepassingen\n- SHA-512 voor hoge beveiligingseisen\n- BLAKE2 voor hoge prestatie toepassingen"
  },
  "sv": {
    "what-is-md5": "Vad är MD5?",
    "what-is-md5-description-markdown": "MD5 (Message Digest Algorithm 5) är en allmänt använd kryptografisk hash-funktion som producerar ett 128-bitars (16-byte) hash-värde, vanligtvis återgivet som ett 32-tecken heksadecimalt tal. Det designades av Ron Rivest 1991 som efterföljare till MD4.\n\n**Nyckelegenskaper:**\n- **Deterministisk**: Samma inmatning producerar alltid samma hash\n- **Snabb beräkning**: Snabb att beräkna för vilken given inmatning som helst\n- **Lavineffekt**: Små förändringar i inmatningen producerar drastiskt olika utmatningar\n- **Fast utmatningsstorlek**: Producerar alltid en 128-bitars hash oavsett inmatningsstorlek\n- **Kollisionssårbar**: Kända sårbarheter gör det möjligt att hitta kollisioner\n\n**Säkerhetsstatus:**\n⚠️ **MD5 är kryptografiskt brutet och bör inte användas för säkerhetskritiska applikationer**. Kollisionsattacker demonstrerades 2004, och praktisk kollisionsgenerering blev genomförbar med modern beräkningskraft.\n\n**Vanliga användningar (nuvarande och historiska):**\n- Filintegritetsverifiering (inte säkerhetskritiskt)\n- Kontrollsummor för upptäckt av datakorruption\n- Äldre system som kräver MD5\n- Databasnyckelgenerering (icke-kryptografisk)\n- Vissa äldre protokoll och system\n\n**Rekommenderade alternativ:**\n- SHA-256 eller SHA-3 för nya applikationer\n- SHA-512 för höga säkerhetskrav\n- BLAKE2 för högpresterande applikationer"
  },
  "pl": {
    "what-is-md5": "Czym jest MD5?",
    "what-is-md5-description-markdown": "MD5 (Message Digest Algorithm 5) to szeroko używana kryptograficzna funkcja skrótu, która produkuje 128-bitową (16-bajtową) wartość skrótu, zazwyczaj przedstawianą jako 32-znakową liczbę szesnastkową. Została zaprojektowana przez Rona Rivesta w 1991 roku jako następca MD4.\n\n**Kluczowe cechy:**\n- **Deterministyczna**: To samo wejście zawsze produkuje ten sam skrót\n- **Szybkie obliczenia**: Szybkie do obliczenia dla dowolnego danego wejścia\n- **Efekt lawiny**: Małe zmiany w wejściu powodują drastycznie różne wyjścia\n- **Stały rozmiar wyjścia**: Zawsze produkuje 128-bitowy skrót niezależnie od rozmiaru wejścia\n- **Podatna na kolizje**: Znane podatności umożliwiają znalezienie kolizji\n\n**Status bezpieczeństwa:**\n⚠️ **MD5 jest kryptograficznie złamane i nie powinno być używane do aplikacji krytycznych dla bezpieczeństwa**. Ataki kolizyjne zostały zademonstrowane w 2004 roku, a praktyczna generacja kolizji stała się możliwa dzięki nowoczesnej mocy obliczeniowej.\n\n**Powszechne zastosowania (obecne i historyczne):**\n- Weryfikacja integralności plików (niekrytyczna dla bezpieczeństwa)\n- Sumy kontrolne do wykrywania uszkodzeń danych\n- Starsze systemy wymagające MD5\n- Generowanie kluczy bazy danych (niekryptograficzne)\n- Niektóre starsze protokoły i systemy\n\n**Zalecane alternatywy:**\n- SHA-256 lub SHA-3 dla nowych aplikacji\n- SHA-512 dla wysokich wymagań bezpieczeństwa\n- BLAKE2 dla aplikacji o wysokiej wydajności"
  },
  "vi": {
    "what-is-md5": "MD5 là gì?",
    "what-is-md5-description-markdown": "MD5 (Message Digest Algorithm 5) là một hàm băm mật mã được sử dụng rộng rãi tạo ra giá trị băm 128-bit (16-byte), thường được hiển thị dưới dạng số thập lục phân 32 ký tự. Nó được thiết kế bởi Ron Rivest năm 1991 như người kế nhiệm MD4.\n\n**Đặc điểm chính:**\n- **Xác định**: Cùng một đầu vào luôn tạo ra cùng một băm\n- **Tính toán nhanh**: Nhanh chóng tính toán cho bất kỳ đầu vào nào\n- **Hiệu ứng tuyết lở**: Những thay đổi nhỏ trong đầu vào tạo ra đầu ra hoàn toàn khác biệt\n- **Kích thước đầu ra cố định**: Luôn tạo ra băm 128-bit bất kể kích thước đầu vào\n- **Dễ bị va chạm**: Các lỗ hổng đã biết làm cho việc tìm ra va chạm trở nên khả thi\n\n**Tình trạng bảo mật:**\n⚠️ **MD5 đã bị phá vỡ về mặt mật mã và không nên được sử dụng cho các ứng dụng quan trọng về bảo mật**. Các cuộc tấn công va chạm được chứng minh vào năm 2004, và việc tạo ra va chạm thực tế trở nên khả thi với sức mạnh tính toán hiện đại.\n\n**Sử dụng phổ biến (hiện tại và lịch sử):**\n- Xác minh tính toàn vẹn tệp (không quan trọng về bảo mật)\n- Checksum để phát hiện hỏng dữ liệu\n- Hệ thống cũ yêu cầu MD5\n- Tạo khóa cơ sở dữ liệu (không mật mã)\n- Một số giao thức và hệ thống cũ hơn\n\n**Các lựa chọn thay thế được đề xuất:**\n- SHA-256 hoặc SHA-3 cho các ứng dụng mới\n- SHA-512 cho yêu cầu bảo mật cao\n- BLAKE2 cho các ứng dụng hiệu suất cao"
  },
  "th": {
    "what-is-md5": "MD5 คืออะไร?",
    "what-is-md5-description-markdown": "MD5 (Message Digest Algorithm 5) เป็นฟังก์ชันแฮชเข้ารหัสที่ใช้กันอย่างแพร่หลายซึ่งสร้างค่าแฮช 128-บิต (16-ไบต์) ซึ่งมักแสดงเป็นตัวเลขฐานสิบหก 32 ตัวอักษร ออกแบบโดย Ron Rivest ในปี 1991 เป็นผู้สืบทอด MD4\n\n**คุณลักษณะสำคัญ:**\n- **กำหนดได้**: อินพุตเดียวกันจะสร้างแฮชเดียวกันเสมอ\n- **การคำนวณที่รวดเร็ว**: คำนวณได้อย่างรวดเร็วสำหรับอินพุตใดก็ตาม\n- **เอฟเฟกต์หิมะถล่ม**: การเปลี่ยนแปลงเล็กน้อยในอินพุตจะสร้างเอาต์พุตที่แตกต่างอย่างมาก\n- **ขนาดเอาต์พุตคงที่**: สร้างแฮช 128-บิตเสมอไม่ว่าขนาดอินพุตจะเป็นเท่าใด\n- **เสี่ยงต่อการชน**: ช่องโหว่ที่ทราบแล้วทำให้สามารถหาการชนได้\n\n**สถานะความปลอดภัย:**\n⚠️ **MD5 ถูกทำลายทางการเข้ารหัสแล้วและไม่ควรใช้สำหรับแอปพลิเคชันที่สำคัญด้านความปลอดภัย** การโจมตีการชนได้รับการพิสูจน์ในปี 2004 และการสร้างการชนในทางปฏิบัติกลายเป็นไปได้ด้วยพลังการคำนวณสมัยใหม่\n\n**การใช้งานทั่วไป (ปัจจุบันและประวัติศาสตร์):**\n- การตรวจสอบความสมบูรณ์ของไฟล์ (ไม่สำคัญด้านความปลอดภัย)\n- เช็คซัมสำหรับการตรวจจับความเสียหายของข้อมูล\n- ระบบเก่าที่ต้องการ MD5\n- การสร้างคีย์ฐานข้อมูล (ไม่ใช่การเข้ารหัส)\n- โปรโตคอลและระบบเก่าบางอย่าง\n\n**ทางเลือกที่แนะนำ:**\n- SHA-256 หรือ SHA-3 สำหรับแอปพลิเคชันใหม่\n- SHA-512 สำหรับความต้องการความปลอดภัยสูง\n- BLAKE2 สำหรับแอปพลิเคชันประสิทธิภาพสูง"
  },
  "id": {
    "what-is-md5": "Apa itu MD5?",
    "what-is-md5-description-markdown": "MD5 (Message Digest Algorithm 5) adalah fungsi hash kriptografi yang banyak digunakan yang menghasilkan nilai hash 128-bit (16-byte), biasanya ditampilkan sebagai angka heksadesimal 32 karakter. Dirancang oleh Ron Rivest pada tahun 1991 sebagai penerus MD4.\n\n**Karakteristik utama:**\n- **Deterministik**: Input yang sama selalu menghasilkan hash yang sama\n- **Komputasi cepat**: Cepat dihitung untuk input apa pun\n- **Efek longsor**: Perubahan kecil pada input menghasilkan output yang sangat berbeda\n- **Ukuran output tetap**: Selalu menghasilkan hash 128-bit terlepas dari ukuran input\n- **Rentan collision**: Kerentanan yang diketahui memungkinkan untuk menemukan collision\n\n**Status keamanan:**\n⚠️ **MD5 telah rusak secara kriptografi dan tidak boleh digunakan untuk aplikasi yang kritis keamanan**. Serangan collision didemonstrasikan pada tahun 2004, dan generasi collision praktis menjadi layak dengan kekuatan komputasi modern.\n\n**Penggunaan umum (saat ini dan historis):**\n- Verifikasi integritas file (tidak kritis keamanan)\n- Checksum untuk deteksi korupsi data\n- Sistem lama yang memerlukan MD5\n- Generasi kunci database (non-kriptografi)\n- Beberapa protokol dan sistem lama\n\n**Alternatif yang direkomendasikan:**\n- SHA-256 atau SHA-3 untuk aplikasi baru\n- SHA-512 untuk persyaratan keamanan tinggi\n- BLAKE2 untuk aplikasi performa tinggi"
  },
  "he": {
    "what-is-md5": "מה זה MD5?",
    "what-is-md5-description-markdown": "MD5 (Message Digest Algorithm 5) הוא פונקציית האש קריפטוגרפית נפוצה המייצרת ערך האש של 128-ביט (16-בייט), המוצג בדרך כלל כמספר הקסדצימלי של 32 תווים. הוא עוצב על ידי רון ריבסט ב-1991 כיורש ל-MD4.\n\n**מאפיינים עיקריים:**\n- **דטרמיניסטי**: אותו קלט תמיד מייצר אותו האש\n- **חישוב מהיר**: מהיר לחישוב עבור כל קלט נתון\n- **אפקט מפולת**: שינויים קטנים בקלט מייצרים פלטים שונים בתכלית\n- **גודל פלט קבוע**: תמיד מייצר האש של 128-ביט ללא קשר לגודל הקלט\n- **פגיע להתנגשויות**: פגיעויות ידועות מאפשרות למצוא התנגשויות\n\n**מצב אבטחה:**\n⚠️ **MD5 שבור קריפטוגרפית ולא צריך להיות בשימוש עבור יישומים קריטיים לאבטחה**. התקפות התנגשות הודגמו ב-2004, וייצור התנגשויות מעשי הפך לאפשרי עם כוח מחשוב מודרני.\n\n**שימושים נפוצים (נוכחיים והיסטוריים):**\n- אימות תקינות קבצים (לא קריטי לאבטחה)\n- סכומי בדיקה לזיהוי השחתת נתונים\n- מערכות ישנות הדורשות MD5\n- יצירת מפתחות מסד נתונים (לא קריפטוגרפי)\n- כמה פרוטוקולים ומערכות ישנים יותר\n\n**חלופות מומלצות:**\n- SHA-256 או SHA-3 ליישומים חדשים\n- SHA-512 לדרישות אבטחה גבוהות\n- BLAKE2 ליישומי ביצועים גבוהים"
  },
  "ms": {
    "what-is-md5": "Apakah MD5?",
    "what-is-md5-description-markdown": "MD5 (Message Digest Algorithm 5) adalah fungsi hash kriptografi yang digunakan secara meluas yang menghasilkan nilai hash 128-bit (16-byte), biasanya dipaparkan sebagai nombor heksadesimal 32 aksara. Ia direka oleh Ron Rivest pada tahun 1991 sebagai pengganti kepada MD4.\n\n**Ciri-ciri utama:**\n- **Deterministik**: Input yang sama sentiasa menghasilkan hash yang sama\n- **Pengiraan pantas**: Pantas dikira untuk sebarang input yang diberikan\n- **Kesan runtuhan salji**: Perubahan kecil dalam input menghasilkan output yang sangat berbeza\n- **Saiz output tetap**: Sentiasa menghasilkan hash 128-bit tanpa mengira saiz input\n- **Terdedah kepada perlanggaran**: Kelemahan yang diketahui membolehkan pencarian perlanggaran\n\n**Status keselamatan:**\n⚠️ **MD5 telah rosak secara kriptografi dan tidak sepatutnya digunakan untuk aplikasi kritikal keselamatan**. Serangan perlanggaran telah ditunjukkan pada tahun 2004, dan penjanaan perlanggaran praktikal menjadi boleh dilaksanakan dengan kuasa pengiraan moden.\n\n**Kegunaan biasa (semasa dan sejarah):**\n- Pengesahan integriti fail (tidak kritikal keselamatan)\n- Checksum untuk pengesanan rasuah data\n- Sistem lama yang memerlukan MD5\n- Penjanaan kunci pangkalan data (bukan kriptografi)\n- Beberapa protokol dan sistem lama\n\n**Alternatif yang disyorkan:**\n- SHA-256 atau SHA-3 untuk aplikasi baharu\n- SHA-512 untuk keperluan keselamatan tinggi\n- BLAKE2 untuk aplikasi prestasi tinggi"
  },
  "no": {
    "what-is-md5": "Hva er MD5?",
    "what-is-md5-description-markdown": "MD5 (Message Digest Algorithm 5) er en mye brukt kryptografisk hash-funksjon som produserer en 128-bits (16-byte) hash-verdi, vanligvis gjengitt som et 32-tegn heksadesimalt tall. Den ble designet av Ron Rivest i 1991 som en etterfølger til MD4.\n\n**Nøkkelegenskaper:**\n- **Deterministisk**: Samme inndata produserer alltid samme hash\n- **Rask beregning**: Rask å beregne for enhver gitt inndata\n- **Snøskredeffekt**: Små endringer i inndata produserer drastisk forskjellige utdata\n- **Fast utdatastørrelse**: Produserer alltid en 128-bits hash uavhengig av inndata-størrelse\n- **Sårbar for kollisjoner**: Kjente sårbarheter gjør det mulig å finne kollisjoner\n\n**Sikkerhetsstatus:**\n⚠️ **MD5 er kryptografisk ødelagt og bør ikke brukes for sikkerhetskritiske applikasjoner**. Kollisjonsangrep ble demonstrert i 2004, og praktisk kollisjonsgenerering ble mulig med moderne datakraft.\n\n**Vanlige bruksområder (nåværende og historiske):**\n- Filintegritetsverifisering (ikke sikkerhetskritisk)\n- Kontrollsummer for påvisning av datakorrupsjon\n- Eldre systemer som krever MD5\n- Databasenøkkelgenerering (ikke-kryptografisk)\n- Noen eldre protokoller og systemer\n\n**Anbefalte alternativer:**\n- SHA-256 eller SHA-3 for nye applikasjoner\n- SHA-512 for høye sikkerhetskrav\n- BLAKE2 for høyytelsesapplikasjoner"
  }
}
</i18n>
