export type { DesktopBrowserOptions } from './types'
export { generateFaviconPNG } from './generate-favicon-png'
export { generateFaviconICO } from './generate-favicon-ico'
export { getHTMLCode } from './get-html-code'
export { generateFaviconSVG } from './generate-favicon-svg'
export { generateAssets } from './generate-assets'
