<template>
  <DescriptionMarkdown
    :title="t('what-is-xxhash')"
    :description="t('what-is-xxhash-description-markdown')"
  />
</template>

<script setup lang="ts">
import { DescriptionMarkdown } from '@shared/ui/base'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()
</script>

<i18n lang="json">
{
  "en": {
    "what-is-xxhash": "What is xxHash (XXH32)?",
    "what-is-xxhash-description-markdown": "xxHash is an extremely fast non-cryptographic hash algorithm that focuses on speed and performance while maintaining good distribution properties. XXH32 is the 32-bit variant that produces a 32-bit (4-byte) hash value, typically displayed as an 8-character hexadecimal number.\n\n**Key characteristics:**\n- **Extremely fast**: Optimized for speed, much faster than cryptographic hash functions\n- **Deterministic**: The same input always produces the same hash\n- **Good distribution**: Provides excellent hash distribution for hash tables\n- **Non-cryptographic**: Not suitable for security purposes, designed for performance\n- **Small output**: 32-bit hash provides compact representation\n- **Platform optimized**: Uses SIMD instructions when available for maximum speed\n\n**Common uses:**\n- Hash tables and data structures\n- File integrity checks (non-security)\n- Data deduplication\n- Checksums for data transmission\n- Performance-critical applications\n- Database indexing\n- Cache keys generation"
  },
  "zh": {
    "what-is-xxhash": "什么是 xxHash (XXH32)？",
    "what-is-xxhash-description-markdown": "xxHash 是一种极快的非加密哈希算法，专注于速度和性能，同时保持良好的分布特性。XXH32 是产生 32 位（4 字节）哈希值的 32 位变体，通常显示为 8 个字符的十六进制数。\n\n**主要特征：**\n- **极快速度**：针对速度优化，比加密哈希函数快得多\n- **确定性**：相同的输入总是产生相同的哈希\n- **良好分布**：为哈希表提供优秀的哈希分布\n- **非加密**：不适用于安全目的，专为性能设计\n- **小输出**：32 位哈希提供紧凑的表示\n- **平台优化**：在可用时使用 SIMD 指令以获得最大速度\n\n**常见用途：**\n- 哈希表和数据结构\n- 文件完整性检查（非安全）\n- 数据去重\n- 数据传输校验和\n- 性能关键应用\n- 数据库索引\n- 缓存键生成"
  },
  "zh-CN": {
    "what-is-xxhash": "什么是 xxHash (XXH32)？",
    "what-is-xxhash-description-markdown": "xxHash 是一种极快的非加密哈希算法，专注于速度和性能，同时保持良好的分布特性。XXH32 是产生 32 位（4 字节）哈希值的 32 位变体，通常显示为 8 个字符的十六进制数。\n\n**主要特征：**\n- **极快速度**：针对速度优化，比加密哈希函数快得多\n- **确定性**：相同的输入总是产生相同的哈希\n- **良好分布**：为哈希表提供优秀的哈希分布\n- **非加密**：不适用于安全目的，专为性能设计\n- **小输出**：32 位哈希提供紧凑的表示\n- **平台优化**：在可用时使用 SIMD 指令以获得最大速度\n\n**常见用途：**\n- 哈希表和数据结构\n- 文件完整性检查（非安全）\n- 数据去重\n- 数据传输校验和\n- 性能关键应用\n- 数据库索引\n- 缓存键生成"
  },
  "zh-TW": {
    "what-is-xxhash": "什麼是 xxHash (XXH32)？",
    "what-is-xxhash-description-markdown": "xxHash 是一種極快的非加密雜湊演算法，專注於速度和效能，同時保持良好的分佈特性。XXH32 是產生 32 位元（4 位元組）雜湊值的 32 位元變體，通常顯示為 8 個字元的十六進位數。\n\n**主要特徵：**\n- **極快速度**：針對速度最佳化，比加密雜湊函數快得多\n- **確定性**：相同的輸入總是產生相同的雜湊\n- **良好分佈**：為雜湊表提供優秀的雜湊分佈\n- **非加密**：不適用於安全目的，專為效能設計\n- **小輸出**：32 位元雜湊提供緊湊的表示\n- **平台最佳化**：在可用時使用 SIMD 指令以獲得最大速度\n\n**常見用途：**\n- 雜湊表和資料結構\n- 檔案完整性檢查（非安全）\n- 資料去重\n- 資料傳輸校驗和\n- 效能關鍵應用\n- 資料庫索引\n- 快取鍵生成"
  },
  "zh-HK": {
    "what-is-xxhash": "什麼是 xxHash (XXH32)？",
    "what-is-xxhash-description-markdown": "xxHash 是一種極快的非加密雜湊演算法，專注於速度和效能，同時保持良好的分佈特性。XXH32 是產生 32 位元（4 位元組）雜湊值的 32 位元變體，通常顯示為 8 個字元的十六進位數。\n\n**主要特徵：**\n- **極快速度**：針對速度最佳化，比加密雜湊函數快得多\n- **確定性**：相同的輸入總是產生相同的雜湊\n- **良好分佈**：為雜湊表提供優秀的雜湊分佈\n- **非加密**：不適用於安全目的，專為效能設計\n- **小輸出**：32 位元雜湊提供緊湊的表示\n- **平台最佳化**：在可用時使用 SIMD 指令以獲得最大速度\n\n**常見用途：**\n- 雜湊表和資料結構\n- 檔案完整性檢查（非安全）\n- 資料去重\n- 資料傳輸校驗和\n- 效能關鍵應用\n- 資料庫索引\n- 快取鍵生成"
  },
  "es": {
    "what-is-xxhash": "¿Qué es xxHash (XXH32)?",
    "what-is-xxhash-description-markdown": "xxHash es un algoritmo de hash no criptográfico extremadamente rápido que se enfoca en la velocidad y el rendimiento mientras mantiene buenas propiedades de distribución. XXH32 es la variante de 32 bits que produce un valor hash de 32 bits (4 bytes), típicamente mostrado como un número hexadecimal de 8 caracteres.\n\n**Características clave:**\n- **Extremadamente rápido**: Optimizado para velocidad, mucho más rápido que las funciones hash criptográficas\n- **Determinístico**: La misma entrada siempre produce el mismo hash\n- **Buena distribución**: Proporciona excelente distribución hash para tablas hash\n- **No criptográfico**: No es adecuado para propósitos de seguridad, diseñado para rendimiento\n- **Salida pequeña**: El hash de 32 bits proporciona representación compacta\n- **Optimizado para plataforma**: Usa instrucciones SIMD cuando están disponibles para máxima velocidad\n\n**Usos comunes:**\n- Tablas hash y estructuras de datos\n- Verificaciones de integridad de archivos (no seguridad)\n- Deduplicación de datos\n- Checksums para transmisión de datos\n- Aplicaciones críticas de rendimiento\n- Indexación de bases de datos\n- Generación de claves de caché"
  },
  "fr": {
    "what-is-xxhash": "Qu'est-ce que xxHash (XXH32) ?",
    "what-is-xxhash-description-markdown": "xxHash est un algorithme de hachage non cryptographique extrêmement rapide qui se concentre sur la vitesse et les performances tout en maintenant de bonnes propriétés de distribution. XXH32 est la variante 32 bits qui produit une valeur de hachage de 32 bits (4 octets), généralement affichée comme un nombre hexadécimal de 8 caractères.\n\n**Caractéristiques clés :**\n- **Extrêmement rapide** : Optimisé pour la vitesse, beaucoup plus rapide que les fonctions de hachage cryptographiques\n- **Déterministe** : La même entrée produit toujours le même hachage\n- **Bonne distribution** : Fournit une excellente distribution de hachage pour les tables de hachage\n- **Non cryptographique** : Non adapté aux fins de sécurité, conçu pour les performances\n- **Sortie petite** : Le hachage 32 bits fournit une représentation compacte\n- **Optimisé pour la plateforme** : Utilise les instructions SIMD lorsqu'elles sont disponibles pour une vitesse maximale\n\n**Utilisations courantes :**\n- Tables de hachage et structures de données\n- Vérifications d'intégrité de fichiers (non-sécurité)\n- Déduplication de données\n- Sommes de contrôle pour la transmission de données\n- Applications critiques en performance\n- Indexation de base de données\n- Génération de clés de cache"
  },
  "de": {
    "what-is-xxhash": "Was ist xxHash (XXH32)?",
    "what-is-xxhash-description-markdown": "xxHash ist ein extrem schneller nicht-kryptographischer Hash-Algorithmus, der sich auf Geschwindigkeit und Leistung konzentriert, während er gute Verteilungseigenschaften beibehält. XXH32 ist die 32-Bit-Variante, die einen 32-Bit (4-Byte) Hash-Wert erzeugt, der typischerweise als 8-stellige Hexadezimalzahl angezeigt wird.\n\n**Hauptmerkmale:**\n- **Extrem schnell**: Für Geschwindigkeit optimiert, viel schneller als kryptographische Hash-Funktionen\n- **Deterministisch**: Dieselbe Eingabe erzeugt immer denselben Hash\n- **Gute Verteilung**: Bietet exzellente Hash-Verteilung für Hash-Tabellen\n- **Nicht-kryptographisch**: Nicht für Sicherheitszwecke geeignet, für Leistung entwickelt\n- **Kleine Ausgabe**: 32-Bit Hash bietet kompakte Darstellung\n- **Plattform-optimiert**: Verwendet SIMD-Anweisungen wenn verfügbar für maximale Geschwindigkeit\n\n**Häufige Verwendungen:**\n- Hash-Tabellen und Datenstrukturen\n- Datei-Integritätsprüfungen (nicht-sicherheit)\n- Datendeduplizierung\n- Prüfsummen für Datenübertragung\n- Leistungskritische Anwendungen\n- Datenbankindizierung\n- Cache-Schlüssel-Generierung"
  },
  "it": {
    "what-is-xxhash": "Cos'è xxHash (XXH32)?",
    "what-is-xxhash-description-markdown": "xxHash è un algoritmo hash non crittografico estremamente veloce che si concentra sulla velocità e le prestazioni mantenendo buone proprietà di distribuzione. XXH32 è la variante a 32 bit che produce un valore hash a 32 bit (4 byte), tipicamente visualizzato come numero esadecimale a 8 caratteri.\n\n**Caratteristiche chiave:**\n- **Estremamente veloce**: Ottimizzato per la velocità, molto più veloce delle funzioni hash crittografiche\n- **Deterministico**: Lo stesso input produce sempre lo stesso hash\n- **Buona distribuzione**: Fornisce eccellente distribuzione hash per tabelle hash\n- **Non crittografico**: Non adatto per scopi di sicurezza, progettato per le prestazioni\n- **Output piccolo**: L'hash a 32 bit fornisce rappresentazione compatta\n- **Ottimizzato per piattaforma**: Usa istruzioni SIMD quando disponibili per massima velocità\n\n**Usi comuni:**\n- Tabelle hash e strutture dati\n- Controlli integrità file (non-sicurezza)\n- Deduplicazione dati\n- Checksum per trasmissione dati\n- Applicazioni critiche per prestazioni\n- Indicizzazione database\n- Generazione chiavi cache"
  },
  "ja": {
    "what-is-xxhash": "xxHash (XXH32)とは？",
    "what-is-xxhash-description-markdown": "xxHashは、良好な分散特性を維持しながら速度とパフォーマンスに焦点を当てた極めて高速な非暗号化ハッシュアルゴリズムです。XXH32は32ビット（4バイト）のハッシュ値を生成する32ビット版で、通常8文字の16進数として表示されます。\n\n**主な特徴：**\n- **極めて高速**：速度に最適化されており、暗号化ハッシュ関数よりもはるかに高速\n- **決定論的**：同じ入力は常に同じハッシュを生成\n- **良好な分散**：ハッシュテーブル用の優秀なハッシュ分散を提供\n- **非暗号化**：セキュリティ目的には適さず、パフォーマンス用に設計\n- **小さな出力**：32ビットハッシュはコンパクトな表現を提供\n- **プラットフォーム最適化**：利用可能な場合にSIMD命令を使用して最大速度を実現\n\n**一般的な用途：**\n- ハッシュテーブルとデータ構造\n- ファイル整合性チェック（非セキュリティ）\n- データ重複排除\n- データ送信のチェックサム\n- パフォーマンス重視のアプリケーション\n- データベースインデックス\n- キャッシュキー生成"
  },
  "ko": {
    "what-is-xxhash": "xxHash (XXH32)란?",
    "what-is-xxhash-description-markdown": "xxHash는 좋은 분포 특성을 유지하면서 속도와 성능에 중점을 둔 매우 빠른 비암호화 해시 알고리즘입니다. XXH32는 32비트(4바이트) 해시 값을 생성하는 32비트 변형으로, 일반적으로 8자리 16진수로 표시됩니다.\n\n**주요 특징:**\n- **매우 빠름**: 속도에 최적화되어 암호화 해시 함수보다 훨씬 빠름\n- **결정론적**: 동일한 입력은 항상 동일한 해시를 생성\n- **좋은 분포**: 해시 테이블을 위한 우수한 해시 분포 제공\n- **비암호화**: 보안 목적에는 적합하지 않으며 성능을 위해 설계됨\n- **작은 출력**: 32비트 해시는 컴팩트한 표현 제공\n- **플랫폼 최적화**: 최대 속도를 위해 사용 가능할 때 SIMD 명령어 사용\n\n**일반적인 용도:**\n- 해시 테이블 및 데이터 구조\n- 파일 무결성 검사(비보안)\n- 데이터 중복 제거\n- 데이터 전송용 체크섬\n- 성능 중심 애플리케이션\n- 데이터베이스 인덱싱\n- 캐시 키 생성"
  },
  "ru": {
    "what-is-xxhash": "Что такое xxHash (XXH32)?",
    "what-is-xxhash-description-markdown": "xxHash — это чрезвычайно быстрый некриптографический алгоритм хеширования, который фокусируется на скорости и производительности, сохраняя при этом хорошие свойства распределения. XXH32 — это 32-битный вариант, который производит 32-битное (4-байтовое) хеш-значение, обычно отображаемое как 8-символьное шестнадцатеричное число.\n\n**Ключевые характеристики:**\n- **Чрезвычайно быстрый**: Оптимизирован для скорости, намного быстрее криптографических хеш-функций\n- **Детерминированный**: Одинаковый ввод всегда производит одинаковый хеш\n- **Хорошее распределение**: Обеспечивает отличное распределение хешей для хеш-таблиц\n- **Некриптографический**: Не подходит для целей безопасности, разработан для производительности\n- **Малый вывод**: 32-битный хеш обеспечивает компактное представление\n- **Оптимизирован под платформу**: Использует SIMD-инструкции при доступности для максимальной скорости\n\n**Обычные применения:**\n- Хеш-таблицы и структуры данных\n- Проверки целостности файлов (не безопасность)\n- Дедупликация данных\n- Контрольные суммы для передачи данных\n- Критичные по производительности приложения\n- Индексация баз данных\n- Генерация ключей кеша"
  },
  "pt": {
    "what-is-xxhash": "O que é xxHash (XXH32)?",
    "what-is-xxhash-description-markdown": "xxHash é um algoritmo de hash não criptográfico extremamente rápido que foca em velocidade e performance mantendo boas propriedades de distribuição. XXH32 é a variante de 32 bits que produz um valor hash de 32 bits (4 bytes), tipicamente exibido como número hexadecimal de 8 caracteres.\n\n**Características principais:**\n- **Extremamente rápido**: Otimizado para velocidade, muito mais rápido que funções hash criptográficas\n- **Determinístico**: A mesma entrada sempre produz o mesmo hash\n- **Boa distribuição**: Fornece excelente distribuição de hash para tabelas hash\n- **Não criptográfico**: Não adequado para propósitos de segurança, projetado para performance\n- **Saída pequena**: Hash de 32 bits fornece representação compacta\n- **Otimizado para plataforma**: Usa instruções SIMD quando disponíveis para velocidade máxima\n\n**Usos comuns:**\n- Tabelas hash e estruturas de dados\n- Verificações de integridade de arquivos (não-segurança)\n- Deduplicação de dados\n- Checksums para transmissão de dados\n- Aplicações críticas de performance\n- Indexação de banco de dados\n- Geração de chaves de cache"
  },
  "ar": {
    "what-is-xxhash": "ما هو xxHash (XXH32)؟",
    "what-is-xxhash-description-markdown": "xxHash هو خوارزمية تشفير غير تشفيرية سريعة للغاية تركز على السرعة والأداء مع الحفاظ على خصائص التوزيع الجيدة. XXH32 هو المتغير 32-بت الذي ينتج قيمة تشفير 32-بت (4 بايت)، والتي تعرض عادة كرقم سادس عشر من 8 أحرف.\n\n**الخصائص الرئيسية:**\n- **سريع للغاية**: محسن للسرعة، أسرع بكثير من دوال التشفير التشفيرية\n- **حتمي**: نفس المدخل ينتج دائماً نفس التشفير\n- **توزيع جيد**: يوفر توزيع تشفير ممتاز لجداول التشفير\n- **غير تشفيري**: غير مناسب لأغراض الأمان، مصمم للأداء\n- **مخرجات صغيرة**: التشفير 32-بت يوفر تمثيل مضغوط\n- **محسن للمنصة**: يستخدم تعليمات SIMD عند توفرها للسرعة القصوى\n\n**الاستخدامات الشائعة:**\n- جداول التشفير وهياكل البيانات\n- فحوصات سلامة الملفات (غير أمنية)\n- إلغاء تكرار البيانات\n- مجاميع التحقق لنقل البيانات\n- التطبيقات الحساسة للأداء\n- فهرسة قواعد البيانات\n- إنتاج مفاتيح التخزين المؤقت"
  },
  "hi": {
    "what-is-xxhash": "xxHash (XXH32) क्या है?",
    "what-is-xxhash-description-markdown": "xxHash एक अत्यंत तेज़ गैर-क्रिप्टोग्राफिक हैश एल्गोरिदम है जो अच्छे वितरण गुणों को बनाए रखते हुए गति और प्रदर्शन पर केंद्रित है। XXH32 32-बिट वेरिएंट है जो 32-बिट (4-बाइट) हैश वैल्यू उत्पन्न करता है, आमतौर पर 8-वर्ण हेक्साडेसिमल संख्या के रूप में प्रदर्शित होता है।\n\n**मुख्य विशेषताएं:**\n- **अत्यंत तेज़**: गति के लिए अनुकूलित, क्रिप्टोग्राफिक हैश फंक्शन से बहुत तेज़\n- **निर्धारक**: समान इनपुट हमेशा समान हैश उत्पन्न करता है\n- **अच्छा वितरण**: हैश टेबल के लिए उत्कृष्ट हैश वितरण प्रदान करता है\n- **गैर-क्रिप्टोग्राफिक**: सुरक्षा उद्देश्यों के लिए उपयुक्त नहीं, प्रदर्शन के लिए डिज़ाइन किया गया\n- **छोटा आउटपुट**: 32-बिट हैश कॉम्पैक्ट प्रतिनिधित्व प्रदान करता है\n- **प्लेटफॉर्म अनुकूलित**: अधिकतम गति के लिए उपलब्ध होने पर SIMD निर्देशों का उपयोग करता है\n\n**सामान्य उपयोग:**\n- हैश टेबल और डेटा संरचनाएं\n- फ़ाइल अखंडता जांच (गैर-सुरक्षा)\n- डेटा डुप्लिकेशन हटाना\n- डेटा ट्रांसमिशन के लिए चेकसम\n- प्रदर्शन-महत्वपूर्ण एप्लिकेशन\n- डेटाबेस इंडेक्सिंग\n- कैश की जेनरेशन"
  },
  "tr": {
    "what-is-xxhash": "xxHash (XXH32) nedir?",
    "what-is-xxhash-description-markdown": "xxHash, iyi dağıtım özelliklerini korurken hız ve performansa odaklanan son derece hızlı bir kriptografik olmayan hash algoritmasıdır. XXH32, tipik olarak 8 karakterlik onaltılık sayı olarak görüntülenen 32-bit (4-bayt) hash değeri üreten 32-bit varyantıdır.\n\n**Temel özellikler:**\n- **Son derece hızlı**: Hız için optimize edilmiş, kriptografik hash fonksiyonlarından çok daha hızlı\n- **Deterministik**: Aynı girdi her zaman aynı hash'i üretir\n- **İyi dağıtım**: Hash tabloları için mükemmel hash dağıtımı sağlar\n- **Kriptografik olmayan**: Güvenlik amaçları için uygun değil, performans için tasarlanmış\n- **Küçük çıktı**: 32-bit hash kompakt temsil sağlar\n- **Platform optimize**: Maksimum hız için mevcut olduğunda SIMD talimatlarını kullanır\n\n**Yaygın kullanımlar:**\n- Hash tabloları ve veri yapıları\n- Dosya bütünlüğü kontrolleri (güvenlik dışı)\n- Veri tekilleştirme\n- Veri iletimi için sağlama toplamları\n- Performans kritik uygulamalar\n- Veritabanı indeksleme\n- Önbellek anahtarı üretimi"
  },
  "nl": {
    "what-is-xxhash": "Wat is xxHash (XXH32)?",
    "what-is-xxhash-description-markdown": "xxHash is een extreem snelle niet-cryptografische hash-algoritme dat zich richt op snelheid en prestaties terwijl het goede distributie-eigenschappen behoudt. XXH32 is de 32-bits variant die een 32-bits (4-byte) hash-waarde produceert, doorgaans weergegeven als een 8-karakter hexadecimaal getal.\n\n**Belangrijkste kenmerken:**\n- **Extreem snel**: Geoptimaliseerd voor snelheid, veel sneller dan cryptografische hash-functies\n- **Deterministisch**: Dezelfde invoer produceert altijd dezelfde hash\n- **Goede distributie**: Biedt uitstekende hash-distributie voor hash-tabellen\n- **Niet-cryptografisch**: Niet geschikt voor beveiligingsdoeleinden, ontworpen voor prestaties\n- **Kleine uitvoer**: 32-bits hash biedt compacte representatie\n- **Platform geoptimaliseerd**: Gebruikt SIMD-instructies wanneer beschikbaar voor maximale snelheid\n\n**Veelvoorkomende toepassingen:**\n- Hash-tabellen en datastructuren\n- Bestandsintegriteitscontroles (niet-beveiliging)\n- Data-deduplicatie\n- Checksums voor datatransmissie\n- Prestatiekritieke toepassingen\n- Database-indexering\n- Cache-sleutelgeneratie"
  },
  "sv": {
    "what-is-xxhash": "Vad är xxHash (XXH32)?",
    "what-is-xxhash-description-markdown": "xxHash är en extremt snabb icke-kryptografisk hash-algoritm som fokuserar på hastighet och prestanda samtidigt som den bibehåller goda distributionsegenskaper. XXH32 är 32-bitarsvarianten som producerar ett 32-bitars (4-byte) hash-värde, vanligtvis visat som ett 8-tecken hexadecimalt nummer.\n\n**Nyckelegenskaper:**\n- **Extremt snabb**: Optimerad för hastighet, mycket snabbare än kryptografiska hash-funktioner\n- **Deterministisk**: Samma inmatning producerar alltid samma hash\n- **God distribution**: Ger utmärkt hash-distribution för hash-tabeller\n- **Icke-kryptografisk**: Inte lämplig för säkerhetsändamål, designad för prestanda\n- **Liten utmatning**: 32-bitars hash ger kompakt representation\n- **Plattformsoptimerad**: Använder SIMD-instruktioner när tillgängliga för maximal hastighet\n\n**Vanliga användningar:**\n- Hash-tabeller och datastrukturer\n- Filintegritetskontroller (icke-säkerhet)\n- Datadeduplicering\n- Checksummor för dataöverföring\n- Prestandakritiska applikationer\n- Databasindexering\n- Cache-nyckelgenerering"
  },
  "pl": {
    "what-is-xxhash": "Czym jest xxHash (XXH32)?",
    "what-is-xxhash-description-markdown": "xxHash to niezwykle szybki nie-kryptograficzny algorytm skrótu, który skupia się na szybkości i wydajności, zachowując jednocześnie dobre właściwości dystrybucji. XXH32 to 32-bitowa wersja, która produkuje 32-bitową (4-bajtową) wartość skrótu, zazwyczaj wyświetlaną jako 8-znakowa liczba szesnastkowa.\n\n**Kluczowe cechy:**\n- **Niezwykle szybki**: Zoptymalizowany pod kątem szybkości, znacznie szybszy niż kryptograficzne funkcje skrótu\n- **Deterministyczny**: To samo wejście zawsze produkuje ten sam skrót\n- **Dobra dystrybucja**: Zapewnia doskonałą dystrybucję skrótu dla tabel skrótu\n- **Nie-kryptograficzny**: Nieodpowiedni do celów bezpieczeństwa, zaprojektowany dla wydajności\n- **Małe wyjście**: 32-bitowy skrót zapewnia kompaktową reprezentację\n- **Zoptymalizowany pod platformę**: Używa instrukcji SIMD gdy dostępne dla maksymalnej szybkości\n\n**Powszechne zastosowania:**\n- Tabele skrótu i struktury danych\n- Kontrole integralności plików (nie-bezpieczeństwo)\n- Deduplikacja danych\n- Sumy kontrolne dla transmisji danych\n- Aplikacje krytyczne dla wydajności\n- Indeksowanie baz danych\n- Generowanie kluczy cache"
  },
  "vi": {
    "what-is-xxhash": "xxHash (XXH32) là gì?",
    "what-is-xxhash-description-markdown": "xxHash là một thuật toán băm phi mã hóa cực kỳ nhanh tập trung vào tốc độ và hiệu suất trong khi vẫn duy trì các đặc tính phân phối tốt. XXH32 là biến thể 32-bit tạo ra giá trị băm 32-bit (4-byte), thường được hiển thị dưới dạng số thập lục phân 8 ký tự.\n\n**Đặc điểm chính:**\n- **Cực kỳ nhanh**: Được tối ưu hóa cho tốc độ, nhanh hơn nhiều so với các hàm băm mã hóa\n- **Xác định**: Cùng một đầu vào luôn tạo ra cùng một băm\n- **Phân phối tốt**: Cung cấp phân phối băm xuất sắc cho bảng băm\n- **Phi mã hóa**: Không phù hợp cho mục đích bảo mật, được thiết kế cho hiệu suất\n- **Đầu ra nhỏ**: Băm 32-bit cung cấp biểu diễn compact\n- **Tối ưu hóa nền tảng**: Sử dụng các lệnh SIMD khi có sẵn để đạt tốc độ tối đa\n\n**Sử dụng phổ biến:**\n- Bảng băm và cấu trúc dữ liệu\n- Kiểm tra tính toàn vẹn tệp (không bảo mật)\n- Khử trùng lặp dữ liệu\n- Checksum cho truyền dữ liệu\n- Ứng dụng quan trọng về hiệu suất\n- Lập chỉ mục cơ sở dữ liệu\n- Tạo khóa cache"
  },
  "th": {
    "what-is-xxhash": "xxHash (XXH32) คืออะไร?",
    "what-is-xxhash-description-markdown": "xxHash เป็นอัลกอริทึมแฮชที่ไม่ใช่การเข้ารหัสที่เร็วมากซึ่งเน้นความเร็วและประสิทธิภาพในขณะที่รักษาคุณสมบัติการกระจายที่ดี XXH32 เป็นตัวแปร 32-บิตที่สร้างค่าแฮช 32-บิต (4-ไบต์) ซึ่งมักแสดงเป็นตัวเลขฐานสิบหก 8 ตัวอักษร\n\n**คุณลักษณะสำคัญ:**\n- **เร็วมาก**: ปรับให้เหมาะสมสำหรับความเร็ว เร็วกว่าฟังก์ชันแฮชเข้ารหัสมาก\n- **กำหนดได้**: อินพุตเดียวกันจะสร้างแฮชเดียวกันเสมอ\n- **การกระจายที่ดี**: ให้การกระจายแฮชที่ยอดเยี่ยมสำหรับตารางแฮช\n- **ไม่ใช่การเข้ารหัส**: ไม่เหมาะสำหรับวัตถุประสงค์ด้านความปลอดภัย ออกแบบสำหรับประสิทธิภาพ\n- **เอาต์พุตเล็ก**: แฮช 32-บิตให้การแสดงที่กะทัดรัด\n- **ปรับให้เหมาะสมกับแพลตฟอร์ม**: ใช้คำสั่ง SIMD เมื่อมีให้เพื่อความเร็วสูงสุด\n\n**การใช้งานทั่วไป:**\n- ตารางแฮชและโครงสร้างข้อมูล\n- การตรวจสอบความสมบูรณ์ของไฟล์ (ไม่ใช่ความปลอดภัย)\n- การลบข้อมูลซ้ำ\n- เช็คซัมสำหรับการส่งข้อมูล\n- แอปพลิเคชันที่สำคัญต่อประสิทธิภาพ\n- การทำดัชนีฐานข้อมูล\n- การสร้างคีย์แคช"
  },
  "id": {
    "what-is-xxhash": "Apa itu xxHash (XXH32)?",
    "what-is-xxhash-description-markdown": "xxHash adalah algoritma hash non-kriptografi yang sangat cepat yang berfokus pada kecepatan dan kinerja sambil mempertahankan properti distribusi yang baik. XXH32 adalah varian 32-bit yang menghasilkan nilai hash 32-bit (4-byte), biasanya ditampilkan sebagai angka heksadesimal 8 karakter.\n\n**Karakteristik utama:**\n- **Sangat cepat**: Dioptimalkan untuk kecepatan, jauh lebih cepat dari fungsi hash kriptografi\n- **Deterministik**: Input yang sama selalu menghasilkan hash yang sama\n- **Distribusi baik**: Memberikan distribusi hash yang sangat baik untuk tabel hash\n- **Non-kriptografi**: Tidak cocok untuk tujuan keamanan, dirancang untuk kinerja\n- **Output kecil**: Hash 32-bit memberikan representasi yang kompak\n- **Dioptimalkan platform**: Menggunakan instruksi SIMD saat tersedia untuk kecepatan maksimum\n\n**Penggunaan umum:**\n- Tabel hash dan struktur data\n- Pemeriksaan integritas file (non-keamanan)\n- Deduplikasi data\n- Checksum untuk transmisi data\n- Aplikasi kritis kinerja\n- Pengindeksan database\n- Generasi kunci cache"
  },
  "he": {
    "what-is-xxhash": "מה זה xxHash (XXH32)?",
    "what-is-xxhash-description-markdown": "xxHash הוא אלגוריתם האש לא-קריפטוגרפי מהיר ביותר המתמקד במהירות וביצועים תוך שמירה על תכונות התפלגות טובות. XXH32 הוא הגרסה של 32-ביט המייצרת ערך האש של 32-ביט (4-בייט), המוצג בדרך כלל כמספר הקסדצימלי של 8 תווים.\n\n**מאפיינים עיקריים:**\n- **מהיר במיוחד**: מותאם למהירות, הרבה יותר מהיר מפונקציות האש קריפטוגרפיות\n- **דטרמיניסטי**: אותו קלט תמיד מייצר אותו האש\n- **התפלגות טובה**: מספק התפלגות האש מצוינת עבור טבלאות האש\n- **לא-קריפטוגרפי**: לא מתאים למטרות אבטחה, מעוצב לביצועים\n- **פלט קטן**: האש 32-ביט מספק ייצוג קומפקטי\n- **מותאם פלטפורמה**: משתמש בהוראות SIMD כאשר זמינות למהירות מקסימלית\n\n**שימושים נפוצים:**\n- טבלאות האש ומבני נתונים\n- בדיקות תקינות קבצים (לא-אבטחה)\n- הסרת כפילויות נתונים\n- סכומי בדיקה להעברת נתונים\n- יישומים קריטיים לביצועים\n- אינדוקס מסדי נתונים\n- יצירת מפתחות מטמון"
  },
  "ms": {
    "what-is-xxhash": "Apakah xxHash (XXH32)?",
    "what-is-xxhash-description-markdown": "xxHash ialah algoritma hash bukan kriptografi yang sangat pantas yang memberi tumpuan kepada kelajuan dan prestasi sambil mengekalkan sifat pengedaran yang baik. XXH32 ialah varian 32-bit yang menghasilkan nilai hash 32-bit (4-byte), biasanya dipaparkan sebagai nombor heksadesimal 8 aksara.\n\n**Ciri-ciri utama:**\n- **Sangat pantas**: Dioptimumkan untuk kelajuan, jauh lebih pantas daripada fungsi hash kriptografi\n- **Deterministik**: Input yang sama sentiasa menghasilkan hash yang sama\n- **Pengedaran baik**: Memberikan pengedaran hash yang sangat baik untuk jadual hash\n- **Bukan kriptografi**: Tidak sesuai untuk tujuan keselamatan, direka untuk prestasi\n- **Output kecil**: Hash 32-bit memberikan perwakilan padat\n- **Dioptimumkan platform**: Menggunakan arahan SIMD apabila tersedia untuk kelajuan maksimum\n\n**Kegunaan biasa:**\n- Jadual hash dan struktur data\n- Pemeriksaan integriti fail (bukan keselamatan)\n- Deduplikasi data\n- Checksum untuk penghantaran data\n- Aplikasi kritikal prestasi\n- Pengindeksan pangkalan data\n- Penjanaan kunci cache"
  },
  "no": {
    "what-is-xxhash": "Hva er xxHash (XXH32)?",
    "what-is-xxhash-description-markdown": "xxHash er en ekstremt rask ikke-kryptografisk hash-algoritme som fokuserer på hastighet og ytelse mens den opprettholder gode distribusjonsegenskaper. XXH32 er 32-bits varianten som produserer en 32-bits (4-byte) hash-verdi, vanligvis vist som et 8-tegn heksadesimalt tall.\n\n**Nøkkelegenskaper:**\n- **Ekstremt rask**: Optimalisert for hastighet, mye raskere enn kryptografiske hash-funksjoner\n- **Deterministisk**: Samme inndata produserer alltid samme hash\n- **God distribusjon**: Gir utmerket hash-distribusjon for hash-tabeller\n- **Ikke-kryptografisk**: Ikke egnet for sikkerhetsformål, designet for ytelse\n- **Liten utdata**: 32-bits hash gir kompakt representasjon\n- **Plattformoptimalisert**: Bruker SIMD-instruksjoner når tilgjengelig for maksimal hastighet\n\n**Vanlige bruksområder:**\n- Hash-tabeller og datastrukturer\n- Filintegritetssjekker (ikke-sikkerhet)\n- Datadeduplisering\n- Sjekksummer for dataoverføring\n- Ytelseskritiske applikasjoner\n- Databaseindeksering\n- Cache-nøkkelgenerering"
  }
}
</i18n>
